/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dac */

#ifndef _Included_Dac
#define _Included_Dac
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dac
 * Method:    dac_pl_cal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Dac_dac_1pl_1cal
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
