connect to escore user escorap1 using escorap1;

export to /home/escorap1/archive_prod/aas001.del of del select * from aas001;
export to /home/escorap1/archive_prod/aps001.del of del select * from aps001;
export to /home/escorap1/archive_prod/bam086.del of del select * from bam086;
export to /home/escorap1/archive_prod/bam302.del of del select * from bam302;
export to /home/escorap1/archive_prod/bam303.del of del select * from bam303;
export to /home/escorap1/archive_prod/bam304.del of del select * from bam304;
export to /home/escorap1/archive_prod/bas001.del of del select * from bas001;
export to /home/escorap1/archive_prod/dam103.del of del select * from dam103;
export to /home/escorap1/archive_prod/dam203.del of del select * from dam203;
export to /home/escorap1/archive_prod/das006.del of del select * from das006;
export to /home/escorap1/archive_prod/jas002.del of del select * from jas002;
export to /home/escorap1/archive_prod/krm001.del of del select * from krm001;
export to /home/escorap1/archive_prod/krm023.del of del select * from krm023;
export to /home/escorap1/archive_prod/krm037.del of del select * from krm037;
export to /home/escorap1/archive_prod/stm001.del of del select * from stm001;
export to /home/escorap1/archive_prod/vam102.del of del select * from vam102;
export to /home/escorap1/archive_prod/app_info.del of del select * from app_info;
export to /home/escorap1/archive_prod/app_result.del of del select * from app_result;
