USE BOOC
GO

CREATE TABLE APP_INFO (
Case_SN Char(12) NOT NULL,
IDN Char(11) NOT NULL,
Application_Date Char(8)NOT NULL,
Product_Code Int NOT NULL default 1,
BT_Amount Int NOT NULL default 0,
No_of_BT Int NOT NULL default 0,
Teaser_Period Int NOT NULL default 0,
BT_Fee_Code Int NOT NULL default 0,
BT_Fee  Int NOT NULL default 0,
BT_Fee_Percentage Float NOT NULL default 0,
CC_Interest_Rate Float NOT NULL,
Gender Int NOT NULL,
Channel Char(12) NOT NULL,
Zip Char(3) NOT NULL,
Card_Type Char(1) NOT NULL,
DOB Char(8) NOT NULL,
Income Int NOT NULL,
Education CHAR(1) NOT NULL,
Company_Name NVARCHAR(24) NOT NULL,
Job_Tiltle NVARCHAR(16) NOT NULL,
Tenure Int NOT NULL,
BT_Fee_Month Int NOT NULL default 0,
Martial_Status CHAR(1) NOT NULL)

GO
CREATE TABLE APP_I(
CASE_SN Char(12) NOT NULL,
IDN Char(11) NOT NULL,
SEQ Int NOT NULL,
APR Float NOT NULL,
Periods Int NOT NULL)
GO
DROP TABLE RESULT
GO
CREATE TABLE RESULT(
CASE_SN	Char(12) NOT NULL,
IDN	Char(11) NOT NULL,
Application_Date	Char(8) NOT NULL,
Suggested_Line	Int NOT NULL,
Product_Code	Int NOT NULL,
Result_Code	Int NOT NULL,
Result_Message	Char(256) NOT NULL,
EV	Decimal(16,2),
PB	Decimal(5,4))
go

INSERT INTO APP_INFO
(Case_SN, IDN, Application_Date, CC_Interest_Rate, Gender, Channel, Zip, Card_Type, DOB,
 Income, Education, Company_Name, Job_Tiltle, Tenure, BT_Fee_Month, Martial_Status)
SELECT IDN, IDN, INQUIRY_DATE, 0.1899, GENDER, '000', '110', 'G', '19800101', 1000000, '4', 'xyz', 'XXX', 10, 12, 'M'
FROM DRIVER_Card
WHERE GENDER IS NOT NULL

DELETE FROM DRIVER

INSERT INTO DRIVER(IDN, Gender, Tranche, Inquiry_Date, Account) 
SELECT IDN, Gender, Tranche, Inquiry_Date, Account FROM DRIVER_CARD
WHERE GENDER IS NOT NULL


DELETE FROM KRM001
DELETE FROM KRM023
DELETE FROM STM001
DELETE FROM BAM086
DELETE FROM JAS002
GO
exec sp_rename 'dbo.KRM001.app_sn', 'CASE_SN'
exec sp_rename 'dbo.KRM023.app_sn', 'CASE_SN'
exec sp_rename 'dbo.BAM086.app_sn', 'CASE_SN'
exec sp_rename 'dbo.STM001.app_sn', 'CASE_SN'
exec sp_rename 'dbo.JAS002.app_sn', 'CASE_SN'
GO
INSERT INTO KRM001(IDN, INQUIRY_DATE, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, LIMIT_TYPE, USAGE_TYPE, SECURE, CASE_SN)
SELECT IDN, INQUIRY_DATE, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, LIMIT_TYPE, USAGE_TYPE, SECURE, IDN
FROM KRM001_24_DEDUP
GO
INSERT INTO KRM023(IDN, INQUIRY_DATE, YRMON, ISSUE, ISSUE_NAME, KR_CODE, LIMIT, PAYMENT, CASH, PAY_CODE, Case_SN)
SELECT IDN, INQUIRY_DATE, YRMON, ISSUE, ISSUE_NAME, KR_CODE, LIMIT, PAYMENT, CASH, PAY_CODE, IDN
FROM KRM023_24_DEDUP
GO
INSERT INTO BAM086(IDN, INQUIRY_DATE, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, CASE_SN)
SELECT IDN, INQUIRY_DATE, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, IDN
FROM BAM085_24_DEDUP
GO
INSERT INTO STM001(IDN, INQUIRY_DATE, QUERY_DATE, BANK_CODE, BANK_NAME, ITEM_LIST, CASE_SN)
SELECT IDN, INQUIRY_DATE, QUERY_DATE, BANK_CODE, BANK_NAME, ITEM_LIST, IDN
FROM STM001_24_DEDUP
GO
INSERT INTO JAS002(IDN, INQUIRY_DATE, EVER_DELINQUENT, DELINQUENT_DATE, EVER_BAD_CHECK, BAD_CHECK_DATE, EVER_REJECT, REJECT_DATE, EVER_STOP_CARD, STOP_CARD_DATE, CASE_SN)
SELECT IDN, INQUIRY_DATE, EVER_DELINQUENT, DELINQUENT_DATE, EVER_BAD_CHECK, BAD_CHECK_DATE, EVER_REJECT, REJECT_DATE, EVER_STOP_CARD, STOP_CARD_DATE, IDN
FROM JAS002_24_DEDUP
GO

/*
DELETE FROM RESULT
SELECT EXCLUSION FROM DACO_V4_1_CAL_Credit_Card_X WHERE APP_SN = '28509969685'
*/
