USE PLOAN_MKT
GO

DROP TABLE DRIVER
GO
CREATE TABLE DRIVER(MSN CHAR(14), IDN CHAR(11), INPUT_TIME CHAR(12), INQUIRY_DATE CHAR(8), GENDER INT)
GO

INSERT INTO DRIVER(MSN, IDN, INPUT_TIME, INQUIRY_DATE, GENDER)
SELECT A.MSN, A.IDN, A.INPUT_TIME, MAX(B.INQUIRY_DATE), ABS(CONVERT(INT, SUBSTRING(A.IDN, 2, 1)) - 2)
FROM APPLICANT AS A INNER JOIN JAS002 AS B
ON A.IDN = B.IDN AND
   A.INPUT_TIME = B.INPUT_TIME AND
   A.MSN = B.MSN
GROUP BY A.MSN, A.IDN, A.INPUT_TIME
GO
