--USE KTB_PLOAN_20060710
GO

/* CREATE_WORKING_TABLE */

 IF OBJECT_ID('tempdb..BAM086_DEDUP') IS NOT NULL
    DROP TABLE BAM086_DEDUP;
 CREATE TABLE BAM086_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN 		CHAR(11),
	DATA_YYY        CHAR(3),
	DATA_MM         CHAR(2),
	BANK_CODE       CHAR(7),
	BANK_NAME       CHAR(40),
	ACCOUNT_CODE    CHAR(1),
	ACCOUNT_CODE2   CHAR(1),
	PURPOSE_CODE    CHAR(1),
	CONTRACT_AMT    DECIMAL (10),
	LOAN_AMT        DECIMAL (10),
	PASS_DUE_AMT    DECIMAL (10),
	PAY_CODE_12     CHAR(12),
	CO_LOAN         CHAR(1),
	UN_MARK         CHAR(1),
	U_YYYMMDD       CHAR(8),
	U_RATE          CHAR(3),
	IB_MARK         CHAR(1),
	IAB_BAN         CHAR(8),
	IAB_NAME        CHAR(60),
	R_YYYMMDD       CHAR(7),
	REFUND_AMT      CHAR(10),
	CK_REF          CHAR(1),
 	BANK_CODE2	CHAR (3),
 	MON_SINCE	INT,
 	CYCLE		INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 IF OBJECT_ID('tempdb..BAM086_BUCKET') IS NOT NULL
    DROP TABLE BAM086_BUCKET;
 CREATE TABLE BAM086_BUCKET (
 	IDN		CHAR(14),
 	BANK_CODE	CHAR(3),
 	MON_SINCE	INT,
 	BUCKET		FLOAT);
 IF OBJECT_ID('tempdb..KRM021_DEDUP') IS NOT NULL
    DROP TABLE KRM021_DEDUP;
 CREATE TABLE KRM021_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN		CHAR (11),
 	CARD_BRAND	CHAR (1),
 	CARD_TYPE	CHAR (1),
 	ISSUE		CHAR (3),
 	ISSUE_NAME	CHAR (40),
 	START_DATE	CHAR (7),
 	STOP_DATE	CHAR (7),
 	STOP_CODE	CHAR (1),
 	AB_CODE		CHAR (1),
 	M_S		CHAR (1),
        RELA		CHAR(1),
        LIMIT		CHAR(6),
        RISK		CHAR(6),
        CLEAR_DATE	CHAR(7),
        IDN_PRI		CHAR(10),
        CNAME		CHAR(12),
        REMARK		CHAR(40),
 	START_MON_SINCE	INT,
 	END_MON_SINCE	INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 IF OBJECT_ID('tempdb..KRM023_DEDUP') IS NOT NULL
    DROP TABLE KRM023_DEDUP;
 CREATE TABLE KRM023_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN		CHAR (11),
	YRMON 		CHAR (5),
	ISSUE 		CHAR (3),
	ISSUE_NAME 	CHAR (40),
	KR_CODE 	CHAR (7),
	LIMIT 		CHAR (5),
	PAYMENT 	CHAR (3),
	CASH 		CHAR (1),
	PAY_CODE 	CHAR (1),
 	MON_SINCE	INT,
 	PAYMENT_AMT	FLOAT,
	SPREAD_PAYMENT	FLOAT,
 	BUCKET_DEF_1K	INT DEFAULT 0,
 	BUCKET_EF_1K	INT DEFAULT 0,
 	BUCKET_F_1K	INT DEFAULT 0,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 IF OBJECT_ID('tempdb..KRM037_DEDUP') IS NOT NULL
    DROP TABLE KRM037_DEDUP;
 CREATE TABLE KRM037_DEDUP (
	MSN		VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
	IDN		CHAR(10),
	IDN_BAN		CHAR(10),
	BILL_DATE	CHAR(7),
	ISSUE		CHAR(3),
	ISSUE_NAME 	CHAR(40),
	CARD_TYPE 	CHAR(7),
	PERM_LIMIT 	DECIMAL(7),
	TEMP_LIMIT 	DECIMAL(7),
	CASH_LIMIT 	DECIMAL(7),
	PAYABLE 	CHAR(3),
	CASH_LENT 	DECIMAL(8),
	LAST_PAYA 	CHAR(3),
	REVOL_BAL 	DECIMAL(9),
	PAY_STAT 	CHAR(1),
	PAY_CODE 	CHAR(1),
	REVOL_RATE 	DECIMAL(4),
	PRE_OWED 	DECIMAL(8),
	DEBT_CODE 	CHAR(1),
	CLOSE_CODE 	CHAR(1),
	CLEAR_DATE 	CHAR(7),
	MON_SINCE	INT,
 	PAYMENT_AMT	FLOAT,
 	BUCKET_DEF_1K	INT DEFAULT 0,
 	BUCKET_EF_1K	INT DEFAULT 0,
 	BUCKET_F_1K	INT DEFAULT 0,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 IF OBJECT_ID('tempdb..STM007_DEDUP') IS NOT NULL
    DROP TABLE STM007_DEDUP;
 CREATE TABLE STM007_DEDUP (
 	MSN VARCHAR(20),
 	INQUIRY_DATE	    CHAR(10),
 	IDN CHAR (11),
 	BANK_CODE CHAR (7),
 	BANK_NAME CHAR (40),
 	QUERY_DATE CHAR (7),
 	ITEM_LIST CHAR (10),
	INQ_PURPOSE_1	CHAR(1),
	INQ_PURPOSE	CHAR(30),
 	QUERY_MON_SINCE INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT INT);
 IF OBJECT_ID('tempdb..JAS002_T') IS NOT NULL
    DROP TABLE JAS002_T;
 CREATE TABLE JAS002_T (
 	MSN VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
 	IDN CHAR (11),
 	REASON CHAR (1),
 	DATE_HAPPEN CHAR (7),
 	MON_SINCE INT);
 IF OBJECT_ID('tempdb..JAS002_T_DEDUP') IS NOT NULL
    DROP TABLE JAS002_T_DEDUP;
 CREATE TABLE JAS002_T_DEDUP (
 	MSN VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
 	IDN CHAR (11),
 	REASON CHAR (1),
 	DATE_HAPPEN CHAR (7),
 	MON_SINCE INT,
 	INQUIRY_MON	INT,
 	CNT INT);
 IF OBJECT_ID('tempdb..BASE') IS NOT NULL
    DROP TABLE BASE;
 CREATE TABLE BASE (
  	IDN VARCHAR (11),
 	AVAIL_FLAG INT DEFAULT 0,
 	JAS002_DEFECT INT DEFAULT 0,
 	KRM021_HIT INT DEFAULT 0,
 	KRM023_HIT INT DEFAULT 0,
 	MAX_BUCKET INT DEFAULT 0,
 	FS044 INT DEFAULT 0,
 	CASH_MAX_BUCKET INT DEFAULT 0,
 	CASH_UTILIZATION INT DEFAULT 0,
        IND001 INT DEFAULT 0);
 IF OBJECT_ID('tempdb..TMP') IS NOT NULL
    DROP TABLE TMP;
 CREATE TABLE TMP (
	IDN CHAR(11),
	MON INT,
	V1 DECIMAL (16, 8),
	V2 DECIMAL (16, 8),
	V3 DECIMAL (16, 8));
 IF OBJECT_ID('tempdb..TMP1') IS NOT NULL
    DROP TABLE TMP1;
 CREATE TABLE TMP1 (
	IDN CHAR(11),
	MON INT,
	V1 DECIMAL (16, 8));
 IF OBJECT_ID('tempdb..OPEN_ISSUE') IS NOT NULL
    DROP TABLE OPEN_ISSUE;
 CREATE TABLE OPEN_ISSUE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT);
 IF OBJECT_ID('tempdb..OPEN_CARD') IS NOT NULL
    DROP TABLE OPEN_CARD;
 CREATE TABLE OPEN_CARD (
	IDN CHAR(11),
	ISSUE CHAR(3),
	NOW   INT,
	MON INT);
 IF OBJECT_ID('tempdb..OPEN_LINE') IS NOT NULL
    DROP TABLE OPEN_LINE;
 CREATE TABLE OPEN_LINE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT,
	NOW   INT,
	CARDS INT,
	BUCKET INT);
 IF OBJECT_ID('tempdb..LATEST_STMT_MON') IS NOT NULL
    DROP TABLE LATEST_STMT_MON;
 CREATE TABLE LATEST_STMT_MON (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT);
 IF OBJECT_ID('tempdb..LATEST_LINE') IS NOT NULL
    DROP TABLE LATEST_LINE;
 CREATE TABLE LATEST_LINE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT,
	MOB INT);
 IF OBJECT_ID('tempdb..KRM023_TMP') IS NOT NULL
    DROP TABLE KRM023_TMP;
 CREATE TABLE KRM023_TMP (
	MSN VARCHAR(20),
	IDN CHAR(11),
	INQUIRY_DATE	CHAR(10),
        YRMON CHAR(5),
	MON_SINCE INT,
	ISSUE CHAR(3),
	ISSUE_NAME CHAR(40),
	LIMIT CHAR(5),
	PAYMENT CHAR(3),
	PAYMENT_AMT FLOAT,
	CASH CHAR,
	PAY_CODE CHAR,
	SPREAD_PAYMENT FLOAT);
 IF OBJECT_ID('tempdb..KRM023_TMP1') IS NOT NULL
    DROP TABLE KRM023_TMP1;
 CREATE TABLE KRM023_TMP1 (
	MSN VARCHAR(20),
	IDN CHAR(11),
	INQUIRY_DATE	CHAR(10),
        YRMON CHAR(5),
	MON_SINCE INT,
	ISSUE CHAR(3),
	ISSUE_NAME CHAR(40),
	LIMIT CHAR(5),
	PAYMENT_AMT FLOAT,
	CASH CHAR,
	PAY_CODE CHAR,
	SPREAD_PAYMENT FLOAT,
        INQUIRY_MON INT);
 IF OBJECT_ID('tempdb..PDACO_V6_1') IS NOT NULL
    DROP TABLE PDACO_V6_1;
 CREATE TABLE PDACO_V6_1 (
	MSN		VARCHAR(20),
	INPUT_TIME	CHAR(12),
	IDN		CHAR (11),
	INQUIRY_DATE	CHAR(8),
	NOW		INT,
	REQUEST_AMT	INT,
	APR		DECIMAL(6,5),
	TOTAL_TERM	INT,
	APPROVED_AMT	INT,	
	AVAIL_FLAG	INT,
	JAS002_DEFECT	INT,
	KRM021_HIT	INT DEFAULT 0,
	KRM023_HIT	INT DEFAULT 0,
	BAM086_HIT	INT DEFAULT 0,
	MAX_BUCKET	INT DEFAULT 0,
	FS044		INT DEFAULT 0,
	FS059_1K_12M	INT DEFAULT 0,
	FS302		INT DEFAULT 0,
	FS334		INT DEFAULT 0,
	CARD_FORCE_STOP INT DEFAULT 0,
	CASH_MAX_BUCKET INT DEFAULT 0,
	CASH_UTILIZATION INT DEFAULT 0,
	IND001		INT DEFAULT 0,
	CARD_REV_BAL	FLOAT DEFAULT 0,
	MS105		FLOAT DEFAULT 0,
	REVOLVING_AMT	FLOAT DEFAULT 0, -- MS602
	P0_SCORE	DECIMAL(16,8), -- P0 Related
	FS302_FG	DECIMAL(16,8), 
	P2_SCORE	DECIMAL(16,8), -- P2 Related
	FS016C_9M_T1	DECIMAL(16,8),
	LN001_9M	DECIMAL(16,8),
	LN001_9M_T2	DECIMAL(16,8),
	P3_SCORE	DECIMAL(16,8), -- P3 Related
	SECURE_FLAG	DECIMAL(16,8),
	UNSECURE_FLAG	DECIMAL(16,8),
	LU_FLAG		DECIMAL(16,8),
	P4_SCORE	DECIMAL(16,8), -- P4 Related
	MS604		DECIMAL(16,8),
	FS061_6M_1K	DECIMAL(16,8),
	FS018_12M_Z	DECIMAL(16,8),
	FS309_Z		DECIMAL(16,8),
	INT053_6	DECIMAL(16,8),
	INT053_6_Q	DECIMAL(16,8),
	LN004_9M	DECIMAL(16,8),
	LN004_9M_Q	DECIMAL(16,8),
	FS546_9M_TRAN	DECIMAL(16,8),
	FS3036_T5	DECIMAL(16,8),
	FS031_TRAN4	DECIMAL(16,8),
	P5_SCORE	DECIMAL(16,8), -- P5 Related
        RS017_R		DECIMAL(16,8),
        RS017_R_TRAN2	DECIMAL(16,8),
        MS074_T2	DECIMAL(16,8),
        MS074_T3	DECIMAL(16,8),
        FS205_3M_1K_Q	DECIMAL(16,8),
        FS205_3M_1K_Q_TRAN2	DECIMAL(16,8),
        WI003_9M_T	DECIMAL(16,8),
        LN003_9M_T	DECIMAL(16,8),
        FS031_1M_Q	DECIMAL(16,8),
        FS031_1M_Q_TRAN2 DECIMAL(16,8),
        FS073B_12M_R	DECIMAL(16,8),
        PDACO_TWEN 	DECIMAL(16,8),  -- Twentile
	MS093		DECIMAL(16,8),
	MS094B		DECIMAL(16,8),
	AMORTIZATION_RATE DECIMAL(16,8),
	MONTHLY_PAYMENT	DECIMAL(16,8),
	MS101		DECIMAL(16,8),			
	FS031		DECIMAL(16,8) DEFAULT 0.0,	-- STM001 Related 
	FS031_1M	DECIMAL(16,8) DEFAULT 0.0,
	RS017		DECIMAL(16,8),	-- KRM021 Related
	STOP_CODE_FLAG	DECIMAL(16,8),
	FS036		DECIMAL(16,8),	-- BAM086 Related
	FS040		DECIMAL(16,8),
	MS063		DECIMAL(16,8),
	MS074		DECIMAL(16,8),
	FS309		DECIMAL(16,8),
	FS334B_1M	DECIMAL(16,8),
	FS546_9M	DECIMAL(16,8),
	FS314B		DECIMAL(16,8),
	APP_MAX_BUCKET	DECIMAL(16,8),  -- KRM023 related
	CDEF_FLAG_1M	DECIMAL(16,8),
	FS002_3M_1K	DECIMAL(16,8),
	FS014_6M	DECIMAL(16,8),
	FS016C_9M	DECIMAL(16,8),
	FS016F_12M	DECIMAL(16,8),
	FS018_12M	DECIMAL(16,8),
	FS021_9M	DECIMAL(16,8),
	FS059_12M_1K	DECIMAL(16,8),
	FS059_3M_1K	DECIMAL(16,8),
	FS073B_12M	DECIMAL(16,8),
	FS101_6M	DECIMAL(16,8),
	FS205_3M_1K	DECIMAL(16,8),
	MS001_12M_1K	DECIMAL(16,8),
	MS118_9M	DECIMAL(16,8),
	MS601		DECIMAL(16,8),
	MS605		DECIMAL(16,8),
	WI001_9M	DECIMAL(16,8),
	WI003_9M	DECIMAL(16,8),
	WI004_9M	DECIMAL(16,8));

/* DROP_WORKING_TABLES */
 DROP TABLE BAM086_DEDUP;
 DROP TABLE BAM086_BUCKET;
 DROP TABLE KRM021_DEDUP;
 DROP TABLE KRM023_DEDUP;
 DROP TABLE KRM037_DEDUP;
 DROP TABLE STM007_DEDUP;
 DROP TABLE JAS002_T;
 DROP TABLE JAS002_T_DEDUP;
 DROP TABLE BASE;
 DROP TABLE TMP;
 DROP TABLE TMP1;
 DROP TABLE OPEN_CARD;
 DROP TABLE OPEN_LINE;
 DROP TABLE LATEST_STMT_MON;
 DROP TABLE LATEST_LINE;
 DROP TABLE KRM023_TMP;
 DROP TABLE KRM023_TMP1;
 DROP TABLE PDACO_V6_1;
GO
/* CREATE_PROCEDURE_PREPARE_JCIC_DATA */
 CREATE PROCEDURE PREPARE_PDACO_JCIC_DATA
  (@MSN VARCHAR(20),
   @INPUT_TIME CHAR(12))
  AS
 INSERT INTO PDACO_V6_1(MSN, IDN, INPUT_TIME)
    SELECT	MSN,IDN, INPUT_TIME
    FROM	APPLICANT
    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
/*
DELETE FROM PDACO_V6_1;

INSERT INTO PDACO_V6_1 (MSN, IDN, INPUT_TIME)
SELECT	MSN,IDN, MAX(INPUT_TIME)
FROM	APPLICANT
GROUP BY MSN, IDN
--3776
*/
 INSERT INTO KRM021_DEDUP (MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME, COUNT(*)
  FROM KRM021
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME;

 INSERT INTO KRM023_DEDUP (MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME, COUNT(*)
  FROM KRM023
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME;
 INSERT INTO STM007_DEDUP (MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME, COUNT(*)
  FROM STM007
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME;
 INSERT INTO BAM086_DEDUP (MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CAST(CONTRACT_AMT AS INT), CAST(LOAN_AMT AS INT), CAST(PASS_DUE_AMT AS INT), PAY_CODE_12, CO_LOAN, INPUT_TIME, COUNT(*)
  FROM BAM086
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, INPUT_TIME;
 INSERT INTO KRM037_DEDUP(MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME)
  SELECT MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME
  FROM KRM037
  WHERE ISSUE != 'TOT'
--    AND MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME
 UPDATE KRM021_DEDUP
    SET MSN      = (CASE WHEN MSN =      '' THEN NULL ELSE MSN END),
        INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
        IDN          = (CASE WHEN IDN =          '' THEN NULL ELSE IDN END),
        CARD_BRAND   = (CASE WHEN CARD_BRAND   = '' THEN NULL ELSE CARD_BRAND END),
        CARD_TYPE    = (CASE WHEN CARD_TYPE    = '' THEN NULL ELSE CARD_TYPE  END),
        ISSUE        = (CASE WHEN ISSUE        = '' THEN NULL ELSE ISSUE      END),
        ISSUE_NAME   = (CASE WHEN ISSUE_NAME   = '' THEN NULL ELSE ISSUE_NAME END),
        START_DATE   = (CASE WHEN START_DATE   = '' THEN NULL ELSE START_DATE END),
        STOP_DATE    = (CASE WHEN STOP_DATE    = '' THEN NULL ELSE STOP_DATE  END),
        STOP_CODE    = (CASE WHEN STOP_CODE    = '' THEN NULL ELSE STOP_CODE  END),
        AB_CODE      = (CASE WHEN AB_CODE      = '' THEN NULL ELSE AB_CODE    END),
        M_S          = (CASE WHEN M_S          = '' THEN NULL ELSE M_S        END),
        LIMIT        = (CASE WHEN LIMIT        = '' THEN NULL ELSE LIMIT      END)
 UPDATE KRM023_DEDUP
   SET MSN      = (CASE WHEN MSN =      '' THEN NULL ELSE MSN END),
       INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN          = (CASE WHEN IDN =          '' THEN NULL ELSE IDN END),
       YRMON        = (CASE WHEN YRMON =        '' THEN NULL ELSE YRMON END),
       ISSUE        = (CASE WHEN ISSUE =        '' THEN NULL ELSE ISSUE END),
       ISSUE_NAME   = (CASE WHEN ISSUE_NAME =   '' THEN NULL ELSE ISSUE_NAME END),
       KR_CODE      = (CASE WHEN KR_CODE =      '' THEN NULL ELSE KR_CODE END),
       LIMIT        = (CASE WHEN LIMIT =        '' THEN NULL ELSE LIMIT END),
       PAYMENT      = (CASE WHEN PAYMENT =      '' THEN NULL ELSE PAYMENT END),
       CASH         = (CASE WHEN CASH =         '' THEN NULL ELSE CASH END),
       PAY_CODE     = (CASE WHEN PAY_CODE =     '' THEN NULL ELSE PAY_CODE END);
 UPDATE STM007_DEDUP
   SET MSN     = (CASE WHEN MSN      = '' THEN NULL ELSE MSN END),
       INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN          = (CASE WHEN IDN          = '' THEN NULL ELSE IDN END),
       BANK_CODE    = (CASE WHEN BANK_CODE    = '' THEN NULL ELSE BANK_CODE  END),
       BANK_NAME    = (CASE WHEN BANK_NAME    = '' THEN NULL ELSE BANK_NAME  END),
       QUERY_DATE   = (CASE WHEN QUERY_DATE   = '' THEN NULL ELSE QUERY_DATE END),
       ITEM_LIST    = (CASE WHEN ITEM_LIST    = '' THEN NULL ELSE ITEM_LIST  END)
 UPDATE BAM086_DEDUP
   SET MSN      = (CASE WHEN MSN       = '' THEN NULL ELSE MSN END),
       INQUIRY_DATE  = (CASE WHEN INQUIRY_DATE  = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN           = (CASE WHEN IDN           = '' THEN NULL ELSE IDN END),
       DATA_YYY      = (CASE WHEN DATA_YYY      = '' THEN NULL ELSE DATA_YYY      END),
       DATA_MM       = (CASE WHEN DATA_MM       = '' THEN NULL ELSE DATA_MM       END),
       BANK_CODE     = (CASE WHEN BANK_CODE     = '' THEN NULL ELSE BANK_CODE     END),
       BANK_NAME     = (CASE WHEN BANK_NAME     = '' THEN NULL ELSE BANK_NAME     END),
       ACCOUNT_CODE  = (CASE WHEN ACCOUNT_CODE  = '' THEN NULL ELSE ACCOUNT_CODE  END),
       ACCOUNT_CODE2 = (CASE WHEN ACCOUNT_CODE2 = '' THEN NULL ELSE ACCOUNT_CODE2 END),
       PURPOSE_CODE  = (CASE WHEN PURPOSE_CODE  = '' THEN NULL ELSE PURPOSE_CODE  END),
       PAY_CODE_12   = (CASE WHEN PAY_CODE_12   = '' THEN NULL ELSE PAY_CODE_12   END),
       CO_LOAN       = (CASE WHEN CO_LOAN       = '' THEN NULL ELSE CO_LOAN       END);
 UPDATE KRM037_DEDUP
   SET BILL_DATE  = (CASE WHEN LTRIM(BILL_DATE)  = '' THEN NULL ELSE LTRIM(RTRIM(BILL_DATE)) END),
       ISSUE      = (CASE WHEN LTRIM(ISSUE)      = '' THEN NULL ELSE ISSUE END),
       ISSUE_NAME = (CASE WHEN LTRIM(ISSUE_NAME) = '' THEN NULL ELSE ISSUE_NAME END),
       CARD_TYPE  = (CASE WHEN LTRIM(CARD_TYPE)  = '' THEN NULL ELSE CARD_TYPE END),
       PERM_LIMIT = (CASE WHEN LTRIM(PERM_LIMIT) = '' THEN NULL ELSE PERM_LIMIT END),
       TEMP_LIMIT = (CASE WHEN LTRIM(TEMP_LIMIT) = '' THEN NULL ELSE TEMP_LIMIT END),
       CASH_LIMIT = (CASE WHEN LTRIM(CASH_LIMIT) = '' THEN NULL ELSE CASH_LIMIT END),
       PAYABLE    = (CASE WHEN LTRIM(PAYABLE)    = '' THEN NULL ELSE PAYABLE END),
       CASH_LENT  = (CASE WHEN LTRIM(CASH_LENT)  = '' THEN NULL ELSE CASH_LENT END),
       LAST_PAYA  = (CASE WHEN LTRIM(LAST_PAYA)  = '' THEN NULL ELSE LAST_PAYA END),
       REVOL_BAL  = (CASE WHEN LTRIM(REVOL_BAL)  = '' THEN NULL ELSE REVOL_BAL END),
       PAY_STAT   = (CASE WHEN LTRIM(PAY_STAT)   = '' THEN NULL ELSE PAY_STAT END),
       PAY_CODE   = (CASE WHEN LTRIM(PAY_CODE)   = '' THEN NULL ELSE PAY_CODE END),
       REVOL_RATE = (CASE WHEN LTRIM(REVOL_RATE) = '' THEN NULL ELSE REVOL_RATE END),
       PRE_OWED   = (CASE WHEN LTRIM(PRE_OWED)   = '' THEN NULL ELSE PRE_OWED END),
       DEBT_CODE  = (CASE WHEN LTRIM(DEBT_CODE)  = '' THEN NULL ELSE DEBT_CODE END),
       CLOSE_CODE = (CASE WHEN LTRIM(CLOSE_CODE) = '' THEN NULL ELSE CLOSE_CODE END),
       CLEAR_DATE = (CASE WHEN LTRIM(CLEAR_DATE) = '' THEN NULL ELSE CLEAR_DATE END);
 INSERT INTO KRM023_TMP (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT)
   SELECT MSN, INQUIRY_DATE, IDN,
          (CASE WHEN LEFT(BILL_DATE,1) = '*' THEN NULL
                WHEN LEN(BILL_DATE) = 4 AND LEFT(BILL_DATE,1) BETWEEN '1' AND '9'
                     THEN '0'+BILL_DATE
                WHEN LEN(BILL_DATE) = 5 AND LEFT(BILL_DATE,1) BETWEEN '0' AND '9'
                     THEN BILL_DATE
                WHEN LEN(BILL_DATE) = 7
                     THEN LEFT(BILL_DATE, 5)
                ELSE NULL END),
          (CASE WHEN LEFT(BILL_DATE,1) = '*' THEN NULL
                WHEN LEN(BILL_DATE) = 4 AND LEFT(BILL_DATE,1) BETWEEN '1' AND '9'
                     THEN CONVERT(INT, LEFT(BILL_DATE, 2)) * 12 + CONVERT(INT, RIGHT(BILL_DATE, 2))
                WHEN LEN(BILL_DATE) = 5 AND LEFT(BILL_DATE,1) BETWEEN '0' AND '9'
                     THEN CONVERT(INT, LEFT(BILL_DATE, 3)) * 12 + CONVERT(INT, RIGHT(BILL_DATE, 2))
                WHEN LEN(BILL_DATE) = 7
                     THEN CONVERT(INT, LEFT(BILL_DATE, 3)) * 12 + CONVERT(INT, SUBSTRING(BILL_DATE, 4, 2))
                ELSE NULL END),
          (CASE WHEN ISSUE = '021' AND CARD_TYPE = 'V' THEN 'CTV'
                WHEN ISSUE = '021' AND CARD_TYPE = 'M' THEN 'CTM'
                WHEN ISSUE = '021' AND CARD_TYPE = 'D' THEN 'CTD'
                WHEN ISSUE = 'A82' AND CARD_TYPE = 'A' THEN 'AEA'
                WHEN ISSUE = 'A82' AND CARD_TYPE = 'E' THEN 'AEE' ELSE ISSUE END),
          ISSUE_NAME, PERM_LIMIT, LAST_PAYA, REVOL_BAL / 1000.0,
          (CASE WHEN CASH_LENT > 0 THEN 'Y' ELSE 'N' END),
          (CASE WHEN DEBT_CODE IN ('A', 'B') THEN 'F'
                WHEN PAY_STAT = 'X' AND PAY_CODE = 'X' THEN 'X'
                WHEN PAY_STAT = '1' AND PAY_CODE = 'N' THEN 'A'
                WHEN PAY_STAT = '1' AND PAY_CODE = '0' THEN 'B'
                WHEN PAY_STAT = '2' AND PAY_CODE = 'N' THEN 'C'
                WHEN PAY_STAT = '2' AND PAY_CODE = '0' THEN 'D'
                WHEN PAY_STAT = '3' AND PAY_CODE BETWEEN '1' AND '7' THEN 'E'
                WHEN PAY_STAT = '4' AND PAY_CODE BETWEEN '1' AND '7' THEN 'F' ELSE NULL END),
          PRE_OWED / 1000.0
   FROM KRM037_DEDUP;
 UPDATE KRM023_TMP
   SET PAYMENT_AMT = (CASE RIGHT(PAYMENT,1) WHEN 'L' THEN 2 WHEN 'M' THEN 5 WHEN 'H' THEN 8
                      ELSE 0 END) * POWER(10, ISNULL(LEFT(PAYMENT,2),0)-1) / 1000.0
   WHERE ((PAYMENT_AMT IS NULL) OR (PAYMENT_AMT = 0))
 INSERT INTO KRM023_TMP1 (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT)
   SELECT MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, SUM(CONVERT(INT, LIMIT)), SUM(PAYMENT_AMT),
           MAX(CASH), MAX(CASE WHEN PAY_CODE = 'X' THEN '0' ELSE PAY_CODE END), SUM(SPREAD_PAYMENT)
   FROM KRM023_TMP
   GROUP BY MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME
 UPDATE KRM023_TMP1
   SET CASH = A.CASH
   FROM KRM023_TMP1 AS A INNER JOIN KRM023_TMP1
   ON KRM023_TMP1.IDN = A.IDN AND
      KRM023_TMP1.MON_SINCE = A.MON_SINCE + 1 AND
      KRM023_TMP1.ISSUE = A.ISSUE AND
      KRM023_TMP1.MSN = A.MSN
 UPDATE KRM023_TMP1
    SET INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 INSERT INTO JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'D', DELINQUENT_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_DELINQUENT = 'Y';
    WHERE  EVER_DELINQUENT = 'Y';
 INSERT INTO JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'B', BAD_CHECK_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_BAD_CHECK = 'Y';
    WHERE  EVER_BAD_CHECK = 'Y';
 INSERT INTO JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'R', REJECT_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_REJECT = 'Y';
    WHERE EVER_REJECT = 'Y';
 INSERT INTO JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'S', STOP_CARD_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_STOP_CARD = 'Y';
    WHERE  EVER_STOP_CARD = 'Y';
 INSERT INTO JAS002_T_DEDUP (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN, CNT)
    SELECT MSN, INQUIRY_DATE, IDN, REASON, DATE_HAPPEN, COUNT(*)
    FROM JAS002_T
    GROUP BY MSN, INQUIRY_DATE, IDN, REASON, DATE_HAPPEN;
 UPDATE KRM021_DEDUP
  SET START_DATE = (CASE WHEN (LEFT(LTRIM(RTRIM(START_DATE)),1) BETWEEN '1' AND '9') AND (LEN(LTRIM(RTRIM(START_DATE)))<7)
                         THEN '0' + LTRIM(RTRIM(START_DATE)) ELSE LTRIM(RTRIM(START_DATE)) END),
      STOP_DATE =  (CASE WHEN (LEFT(LTRIM(RTRIM(STOP_DATE)),1) BETWEEN '1' AND '9') AND
                         (LEN(LTRIM(RTRIM(STOP_DATE)))<7) AND STOP_DATE != '9991231'
                          THEN '0' + LTRIM(RTRIM(STOP_DATE)) ELSE LTRIM(RTRIM(STOP_DATE)) END)
 UPDATE KRM021_DEDUP SET STOP_DATE = '9991231'
  WHERE ((STOP_DATE = '') OR (STOP_DATE IS NULL))
 UPDATE KRM021_DEDUP
   SET START_MON_SINCE = (CASE WHEN LEFT(START_DATE,1) NOT BETWEEN '0' AND '9' THEN NULL
                         ELSE CAST(LEFT(START_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(START_DATE, 5), 2) AS INT) END),
      END_MON_SINCE =   (CASE WHEN LEFT(STOP_DATE, 1) NOT BETWEEN '0' AND '9' THEN NULL
                         ELSE CAST(LEFT(STOP_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(STOP_DATE, 5), 2) AS INT) END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE JAS002_T_DEDUP
   SET DATE_HAPPEN = (CASE
 		    WHEN LEFT(LTRIM(DATE_HAPPEN),1) NOT IN ('1', '0', '*') THEN '0' + (LTRIM(DATE_HAPPEN))
  		    ELSE DATE_HAPPEN
  		   END);
 UPDATE JAS002_T_DEDUP
   SET MON_SINCE = (CASE
    		  WHEN LEFT(LTRIM(DATE_HAPPEN),1) = '*' THEN NULL
    		  ELSE CAST(LEFT(LTRIM(DATE_HAPPEN), 3) AS INT) * 12 + CAST(RIGHT(LEFT(RTRIM(DATE_HAPPEN), 5), 2) AS INT)
  		 END),
       INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE KRM023_DEDUP
 SET YRMON = (CASE
 	      WHEN LEFT(LTRIM(RTRIM(YRMON)),1) NOT IN ('1', '0', '*') THEN '0' + LTRIM(RTRIM(YRMON))
 	      ELSE LTRIM(RTRIM(YRMON))
 	     END);
 UPDATE KRM023_DEDUP
 SET MON_SINCE = (CASE
 		   WHEN LEFT(YRMON,1) = '*' THEN NULL
 		   ELSE CAST(LEFT(YRMON, 3) AS INT) * 12 + CAST(RIGHT(LEFT(YRMON, 5), 2) AS INT)
 		 END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE STM007_DEDUP
   SET QUERY_DATE = (CASE
 		   WHEN LEFT(QUERY_DATE,1) NOT IN ('1', '0', '*') THEN '0' + LTRIM(RTRIM(QUERY_DATE))
 		   ELSE QUERY_DATE
 		  END);
 UPDATE STM007_DEDUP
   SET QUERY_MON_SINCE = (CASE
 			WHEN LEFT(QUERY_DATE,1) = '*' THEN NULL
 			ELSE CAST(LEFT(QUERY_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(QUERY_DATE, 5), 2) AS INT)
 		       END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE KRM023_DEDUP
  SET PAYMENT =
   (CASE WHEN RIGHT(LEFT(PAYMENT,2),1) IN ('H', 'M', 'L') THEN '0' + (LEFT(PAYMENT,2))
         ELSE PAYMENT END);
 UPDATE KRM023_DEDUP
  SET PAYMENT_AMT =
   (CASE RIGHT(PAYMENT,1) WHEN 'L' THEN 2 WHEN 'M' THEN 5 WHEN 'H' THEN 8
   ELSE 0 END) * POWER(10, ISNULL(LEFT(PAYMENT,2),0)-1) / 1000.0;
 INSERT INTO KRM023_DEDUP (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT)
   SELECT MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT
   FROM KRM023_TMP1
   WHERE MON_SINCE > 1140
 UPDATE KRM023_DEDUP
   SET PAYMENT_AMT = CAST(LIMIT AS INT)
   WHERE PAYMENT_AMT > CAST(LIMIT AS INT)
     AND CAST(LIMIT AS INT) > 0;
 UPDATE  KRM023_DEDUP
 SET BUCKET_DEF_1K = (CASE WHEN PAY_CODE IN ('D', 'E', 'F') AND (PAYMENT_AMT + SPREAD_PAYMENT)> 1 THEN 1
                       ELSE 0 END),
     BUCKET_EF_1K = (CASE WHEN PAY_CODE IN ('E', 'F') AND (PAYMENT_AMT + SPREAD_PAYMENT) > 1 THEN 1
                      ELSE 0 END),
     BUCKET_F_1K = (CASE WHEN PAY_CODE = 'F' AND (PAYMENT_AMT + SPREAD_PAYMENT) > 1 THEN 1
                     ELSE 0 END);
 DECLARE @I INT
 SET @I=12
 WHILE @I >= 0
 BEGIN
   UPDATE KRM023_DEDUP
   SET
   BUCKET_DEF_1K =(CASE WHEN KRM023_DEDUP.PAY_CODE IN ('D', 'E', 'F') AND
                             (KRM023_DEDUP.PAYMENT_AMT + KRM023_DEDUP.SPREAD_PAYMENT)> 1
                        THEN A.BUCKET_DEF_1K + 1
                        ELSE 0 END),
   BUCKET_EF_1K =(CASE WHEN  KRM023_DEDUP.PAY_CODE IN ('E', 'F') AND
                             (KRM023_DEDUP.PAYMENT_AMT + KRM023_DEDUP.SPREAD_PAYMENT)> 1
                       THEN A.BUCKET_EF_1K + 1
                       ELSE 0 END),
   BUCKET_F_1K =(CASE WHEN  KRM023_DEDUP.PAY_CODE = 'F' AND
                            (KRM023_DEDUP.PAYMENT_AMT + KRM023_DEDUP.SPREAD_PAYMENT) > 1
                      THEN A.BUCKET_F_1K + 1
                      ELSE 0 END)
   FROM  KRM023_DEDUP AS A INNER JOIN  KRM023_DEDUP ON
         A.IDN =  KRM023_DEDUP.IDN AND
         A.ISSUE =  KRM023_DEDUP.ISSUE AND
         A.MON_SINCE = ( KRM023_DEDUP.MON_SINCE - 1)
   WHERE (A.INQUIRY_MON - A.MON_SINCE) = @I
 SET @I = @I - 1
 END;
 UPDATE BAM086_DEDUP
  SET BANK_CODE2 = LEFT(BANK_CODE,3),
      MON_SINCE = CAST(DATA_YYY AS INT)* 12 + CAST(DATA_MM AS INT),
      CYCLE = LEN(LTRIM(RTRIM(PAY_CODE_12)));
 SET @I=1;
 WHILE @I <= 12
    BEGIN
       INSERT INTO BAM086_BUCKET (IDN, BANK_CODE, MON_SINCE, BUCKET)
          SELECT IDN, BANK_CODE2, (MON_SINCE - @I + 1),
                 (CASE WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'A' THEN 0.25
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'B' THEN 0.5
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'X' THEN 0
                       ELSE CONVERT(FLOAT, SUBSTRING(RTRIM(PAY_CODE_12), @I, 1)) END)
          FROM BAM086_DEDUP
          WHERE CYCLE >= @I
       SET @I = @I + 1
    END
/*
-- ALTER TABLE BAM086_DEDUP ADD MON_SINCE INT

 DECLARE @I INT
 UPDATE BAM086_DEDUP
  SET BANK_CODE2 = LEFT(BANK_CODE,3),
      MON_SINCE = CAST(DATA_YYY AS INT)* 12 + CAST(DATA_MM AS INT),
      CYCLES = LEN(LTRIM(RTRIM(PAY_CODE_12)));
 SET @I=1;
 WHILE @I <= 12
    BEGIN
       INSERT INTO BAM086_BUCKET (IDN, BANK_CODE, MON_SINCE, BUCKET)
          SELECT IDN, BANK_CODE2, (MON_SINCE - @I + 1),
                 (CASE WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'A' THEN 0.25
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'B' THEN 0.5
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'X' THEN 0
                       ELSE CONVERT(FLOAT, SUBSTRING(RTRIM(PAY_CODE_12), @I, 1)) END)
          FROM BAM086_DEDUP
          WHERE CYCLES >= @I
       SET @I = @I + 1
    END
*/
 /* RISK FILTER PROCESS */
 IF OBJECT_ID('tempdb..BASE_TMP') IS NOT NULL
    DROP TABLE BASE_TMP;
 CREATE TABLE BASE_TMP (
 	IDN CHAR (11),
 	AVAIL_FLAG INT
 );
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
    SELECT IDN, 0 FROM PDACO_V6_1
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 1
   FROM KRM023_DEDUP;
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 2
   FROM KRM021_DEDUP;
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 4
   FROM BAM086_DEDUP;
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 8
   FROM JAS002_T
 INSERT INTO BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 16
   FROM STM007_DEDUP;
 INSERT INTO BASE (IDN, AVAIL_FLAG)
   SELECT IDN, SUM(AVAIL_FLAG)
   FROM BASE_TMP
  GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET AVAIL_FLAG = A.AVAIL_FLAG
   FROM BASE A
   WHERE A.IDN = PDACO_V6_1.IDN;
 UPDATE PDACO_V6_1
   SET KRM023_HIT = 1
   WHERE AVAIL_FLAG & 0X01 = 0X01;
 UPDATE PDACO_V6_1
   SET KRM021_HIT = 1
   WHERE AVAIL_FLAG & 0X02 = 0X02;
 UPDATE PDACO_V6_1
   SET BAM086_HIT = 1
   WHERE AVAIL_FLAG & 0X04 = 0X04;
-- INITIALIZATION
 UPDATE PDACO_V6_1
    SET FS036 = 0,
	FS040 = 0,
	FS044 = 0,
	MS063 = 0,
	MS074 = 0,
	MS093 = 0,
	FS302 = 0,
	FS309 = 0,
	FS334 = 0,
	FS334B_1M = 0,
	FS546_9M = 0,
	FS314B = 0
 WHERE	BAM086_HIT = 1
 /*INIT KRM023 VARIABLES*/
 UPDATE PDACO_V6_1
 SET APP_MAX_BUCKET = 0,
     CDEF_FLAG_1M   = 0,
     FS002_3M_1K    = 0,
     FS014_6M	    = 0,
     FS016C_9M	    = 0,
     FS016F_12M	    = 0,
     FS018_12M	    = 0,
     FS021_9M	    = 0,
     FS059_12M_1K   = 0,
     FS059_3M_1K    = 0,
     FS061_6M_1K    = 0,
     FS073B_12M	    = 0,
     FS101_6M	    = 0,
     FS205_3M_1K    = 0,
     MS001_12M_1K   = 0,
     MS094B	    = 0,
     MS118_9M	    = 0,
     MS601	    = 0,
     MS605	    = 0,
     WI001_9M	    = 0,
     WI003_9M	    = 0,
     WI004_9M	    = 0
 WHERE KRM023_HIT = 1;
 /*INIT KRM021 AND KRM023 VARIABLES*/
 UPDATE PDACO_V6_1
   SET FS205_3M_1K = 0
   FROM KRM021_DEDUP AS A, KRM023_DEDUP AS B
   WHERE A.IDN = B.IDN
     AND A.IDN = PDACO_V6_1.IDN
     AND ((A.ISSUE = B.ISSUE)
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'V') AND (B.ISSUE = 'CTV'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'M') AND (B.ISSUE = 'CTM'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'D') AND (B.ISSUE = 'CTD'))
           OR ((A.ISSUE = 'A82' AND A.CARD_BRAND = 'A') AND (B.ISSUE = 'AEA'))
         );
 /* UPDATE PRESCREEN VARIABLE*/
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
 SELECT IDN, COUNT(*)
   FROM JAS002_T_DEDUP
   WHERE INQUIRY_MON - MON_SINCE <= 36
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET JAS002_DEFECT = 1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN AND
         A.V1 > 0;
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
   SELECT IDN, MAX(BUCKET_EF_1K)
   FROM KRM023_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET MAX_BUCKET = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN
 /*----FS044----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
  SELECT IDN, COUNT(*)
  FROM BAM086_DEDUP
  WHERE PASS_DUE_AMT > 0
  GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS044 = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN, MAX(BUCKET)
     FROM BAM086_BUCKET
     GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS334 = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN, SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X')
                     THEN 1 ELSE 0 END)
   FROM BAM086_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS302 = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 /*----CASH CARD MAX BUCKET----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN, COUNT(*)
   FROM BAM086_DEDUP
   WHERE ACCOUNT_CODE = 'Y'
     AND ISNULL(LEFT(PAY_CODE_12, 1),'0') NOT IN ('0', 'X')
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET CASH_MAX_BUCKET = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 /*----CASH CARD UTILIZATION----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN, COUNT(*)
   FROM BAM086_DEDUP
   WHERE ACCOUNT_CODE = 'Y'
     AND (ISNULL(LOAN_AMT,0)+ ISNULL(PASS_DUE_AMT,0))/ CAST(CONTRACT_AMT AS FLOAT) >= 0.95
     AND CONTRACT_AMT > 0
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET CASH_UTILIZATION = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 /*----CREDIT CARD FORCE STOP ----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
    SELECT IDN, COUNT(*)
    FROM KRM021_DEDUP
    WHERE STOP_CODE = '3' GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET CARD_FORCE_STOP = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 /*----CREDIT CARD FORCE STOP ----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, MON, V1)
   SELECT IDN, 12, COUNT(DISTINCT ISSUE)
   FROM KRM023_DEDUP
   WHERE BUCKET_EF_1K >= 1
     AND (INQUIRY_MON - MON_SINCE) <=12
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS059_1K_12M = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN AND MON = 12
 /*----CREDIT CARD REVOLVING BALANCE ----*/
 IF OBJECT_ID('tempdb..KRM023_RANGE_TMP') IS NOT NULL
    DROP TABLE KRM023_RANGE_TMP;
 CREATE TABLE KRM023_RANGE_TMP
   (IDN CHAR(11), ISSUE CHAR(3), MON INT);
 INSERT INTO KRM023_RANGE_TMP(IDN, ISSUE, MON)
   SELECT IDN, ISSUE, MAX(MON_SINCE)
   FROM KRM023_DEDUP
   WHERE INQUIRY_MON - MON_SINCE <= 3
   GROUP BY IDN, ISSUE;
 DELETE FROM TMP;
 DELETE FROM TMP1;
 INSERT INTO TMP (IDN, V1, V2)
   SELECT A.IDN,
        SUM((CASE WHEN PAY_CODE IN ('C', 'D', 'E', 'F') THEN PAYMENT_AMT ELSE 0 END) +
            (CASE WHEN PAY_CODE IN ('C', 'D', 'E', 'F') OR (PAY_CODE IN ('A', 'B', 'X') AND CASH='Y')
                  THEN ISNULL(SPREAD_PAYMENT, 0) ELSE 0 END)),
        SUM(CONVERT(FLOAT, LIMIT))
   FROM KRM023_DEDUP AS A, KRM023_RANGE_TMP AS B
   WHERE A.IDN = B.IDN
     AND A.ISSUE = B.ISSUE
     AND A.MON_SINCE = B.MON
   GROUP BY A.IDN;
 UPDATE PDACO_V6_1
   SET CARD_REV_BAL = A.V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 /*----CASH CARD REVOLVING BALANCE ----*/
 UPDATE PDACO_V6_1
       SET MS105 = 
           (SELECT SUM(CAST(ISNULL(LOAN_AMT, 0) AS INT) + CAST(ISNULL(PASS_DUE_AMT, 0) AS INT))
            FROM BAM086_DEDUP S
            WHERE ACCOUNT_CODE = 'Y'
              AND PDACO_V6_1.IDN = S.IDN
            GROUP BY S.IDN)
       WHERE EXISTS (SELECT *
                     FROM BAM086_DEDUP S
                     WHERE ACCOUNT_CODE = 'Y'
                       AND PDACO_V6_1.IDN = S.IDN);
-- REVOLVING_AMT (MS602)
 UPDATE PDACO_V6_1
   SET REVOLVING_AMT = CARD_REV_BAL + MS105;
 /*----IND001----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1, V2)
   SELECT IDN, MIN(INQUIRY_MON)-1 - MIN(MON_SINCE), MAX(INQUIRY_MON) - MAX(MON_SINCE)
   FROM KRM023_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET IND001 = (CASE WHEN A.V1 < 6 OR A.V2 >= 3 THEN 1 ELSE 0 END)
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN;
 INSERT INTO TMP1 (IDN, V1)
   SELECT IDN, (CASE WHEN (MIN(INQUIRY_MON)-1 - MIN(START_MON_SINCE)) <= 6 THEN 1 ELSE 0 END)
   FROM KRM021_DEDUP
--   WHERE END_MON_SINCE > INQUIRY_MON
--     AND M_S = 'Y'
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET IND001 = (CASE WHEN (IND001 + A.V1) > 0 THEN 1 ELSE 0 END)
   FROM TMP1 AS A
   WHERE A.IDN = PDACO_V6_1.IDN;

 DROP TABLE BASE_TMP;
 DROP TABLE KRM023_RANGE_TMP;

GO
/* END_OF_CREATE_PROCEDURE_PREPARE_JCIC_DATA */


-----------------------------------------------------------------------------------------------------------------------
-- P0, Screen #1-5
 UPDATE PDACO_V6_1
   SET FS302_FG = (CASE WHEN FS302 >= 1 THEN 1 ELSE 0 END);
 UPDATE PDACO_V6_1
   SET P0_SCORE= 0.11920		+
   	     FS302_FG		*	0.16259 +
   	     JAS002_DEFEAT	*	0.08236 ;
 UPDATE PDACO_V6_1
   SET PDACO_TWEN = (CASE
                     WHEN P0_SCORE IS NULL    THEN 0
                     WHEN P0_SCORE <= 0.1192  THEN 2
                     WHEN P0_SCORE <= 0.20156 THEN 3
                     ELSE 4
   		  END);
GO   		  
-----------------------------------------------------------------------------------------------------------------------
-- P2, w/o guarantor, CC limit (MS605) <=50K
 /*----MONTHLY DEBT ----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM BAM086_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN; 
-- MS094B Average credit card revolving balance in last 3 months
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
         THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
         ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE PDACO_V6_1
    SET MS094B = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 /*----CASH CARD REVOLVING BALANCE ----*/
 UPDATE PDACO_V6_1
       SET MS105 = 
           (SELECT SUM(CAST(ISNULL(LOAN_AMT, 0) AS INT) + CAST(ISNULL(PASS_DUE_AMT, 0) AS INT))
            FROM BAM086_DEDUP S
            WHERE ACCOUNT_CODE = 'Y'
              AND PDACO_V6_1.IDN = S.IDN
            GROUP BY S.IDN)
       WHERE EXISTS (SELECT *
                     FROM BAM086_DEDUP S
                     WHERE ACCOUNT_CODE = 'Y'
                       AND PDACO_V6_1.IDN = S.IDN);
 /* WI001_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, COUNT(DISTINCT ISSUE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI001_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 UPDATE PDACO_V6_1
    SET AMORTIZATION_RATE = (CASE WHEN APR = 0 THEN 1/TOTAL_TERM
                                  ELSE POWER ((1 + (APR / 12)), TOTAL_TERM) * (APR / 12)
                                       / (POWER ((1 + (APR / 12)), TOTAL_TERM) - 1) END);
 UPDATE PDACO_V6_1
    SET MONTHLY_PAYMENT = ISNULL(REQUEST_AMT * AMORTIZATION_RATE, 0);
 UPDATE PDACO_V6_1
   SET FS016C_9M_T1 = (CASE WHEN FS016C_9M = 0 THEN 0 ELSE 1 END),
       LN001_9M = (MONTHLY_PAYMENT/1000.0 + MS093 + (MS094B + MS105)* 0.35)/ WI001_9M;
 UPDATE PDACO_V6_1
   SET LN001_9M_T2 = LN001_9M * (1-FS016C_9M_T1);
 UPDATE PDACO_V6_1
   SET P2_SCORE= -0.02923	+
   	     FS016C_9M_T1	*	0.15400 +
   	     LN001_9M_T2	*	0.00316 +
   	     CDEF_FLAG_1M	*	0.06766;
 UPDATE PDACO_V6_1
   SET PDACO_TWEN = (CASE
                     WHEN P2_SCORE IS NULL     THEN 0
                     WHEN P2_SCORE <= -0.01551 THEN 1
                     WHEN P2_SCORE <= -0.00549 THEN 2
                     WHEN P2_SCORE <= 0.00562  THEN 3
                     WHEN P2_SCORE <= 0.01940  THEN 4
                     WHEN P2_SCORE <= 0.04620  THEN 5
                     WHEN P2_SCORE <= 0.05837  THEN 6
                     WHEN P2_SCORE <= 0.07083  THEN 7
                     WHEN P2_SCORE <= 0.07631  THEN 8
                     WHEN P2_SCORE <= 0.08300  THEN 9
                     WHEN P2_SCORE <= 0.09374  THEN 10
                     WHEN P2_SCORE <= 0.10974  THEN 11
                     WHEN P2_SCORE <= 0.12477  THEN 12
                     WHEN P2_SCORE <= 0.14445  THEN 13
                     WHEN P2_SCORE <= 0.18946  THEN 14
                     WHEN P2_SCORE <= 0.19243  THEN 17
                     ELSE 20
   		  END);
GO
-----------------------------------------------------------------------------------------------------------------------
-- P3, w/o guarantor, 50K < CC limit (MS605) <= 100K, not revolve in last month (CDEF_FLAG_1M = 0)
 UPDATE PDACO_V6_1
    SET FS036 = A.FS036,
	FS040 = A.FS040
 FROM (SELECT IDN, 
	SUM(CASE WHEN ((ACCOUNT_CODE2 IN ('S', 'W', 'M')) OR 
			       (ACCOUNT_CODE = 'K'))
		 THEN 1
		 ELSE 0 END) AS FS036,
	SUM(CASE WHEN (((ACCOUNT_CODE2 IS NULL) OR 
				    (ACCOUNT_CODE2 = '') OR 
				    (ACCOUNT_CODE2 = 'N')) AND 
				     ACCOUNT_CODE != 'K') 
		 THEN 1
		 ELSE 0 END) AS FS040
       FROM	BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = PDACO_V6_1.IDN;
 /* MS118_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      MIN((ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)) / CAST(LIMIT AS FLOAT))
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=9  /* NO   30-DAY RULE */
    AND  CAST(LIMIT AS FLOAT) > 0
    AND  PAY_CODE IN ('C','D','E','F')
    AND  PAYMENT_AMT+ISNULL(SPREAD_PAYMENT,0) > 1    /* TO ELIMINATE THOSE SMALL REVOLING LINES */
    GROUP BY IDN;
 UPDATE PDACO_V6_1
    SET MS118_9M = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 /* FS014_6M       */
 UPDATE PDACO_V6_1
 SET FS014_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = PDACO_V6_1.IDN);
 /* FS021_9M       */
 UPDATE PDACO_V6_1
     SET FS021_9M = (SELECT COUNT(DISTINCT MON_SINCE)
                     FROM KRM023_DEDUP
                     WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND  PAY_CODE IN ('C','D','E','F')
                     AND IDN = PDACO_V6_1.IDN)
     WHERE EXISTS (SELECT COUNT(DISTINCT MON_SINCE)
                     FROM KRM023_DEDUP
                     WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND  PAY_CODE IN ('C','D','E','F')
                     AND IDN = PDACO_V6_1.IDN);
 UPDATE PDACO_V6_1
   SET SECURE_FLAG = (CASE WHEN FS036 > 0 THEN 1 ELSE 0 END),
       UNSECURE_FLAG = (CASE WHEN FS040 > 0 THEN 1 ELSE 0 END);
 UPDATE PDACO_V6_1
   SET LU_FLAG = (CASE WHEN (MS118_9M <= 0.2 AND FS014_6M >= 2) OR
                            (SECURE_FLAG = 1 AND UNSECURE_FLAG = 0) THEN 1 ELSE 0 END);
GO
-----------------------------------------------------------------------------------------------------------------------
-- P4, w/o guarantor, 50K < CC limit (MS605) <= 100K, revolve in last month (CDEF_FLAG_1M = 1)
 /*----MS063 UNSECURED LOAN BALANCE ----*/
 UPDATE PDACO_V6_1
       SET MS063 = 
           (SELECT SUM(CAST(ISNULL(LOAN_AMT, 0) AS INT) + CAST(ISNULL(PASS_DUE_AMT, 0) AS INT))
            FROM BAM086_DEDUP S
            WHERE ((ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE = 'N'))
              AND PDACO_V6_1.IDN = S.IDN
            GROUP BY S.IDN)
       WHERE EXISTS (SELECT *
                     FROM BAM086_DEDUP S
                     WHERE ((ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE = 'N'))
                       AND PDACO_V6_1.IDN = S.IDN);
-- CREDIT CARD AND UNSECURED REVOLVING_AMT (MS604)
 UPDATE PDACO_V6_1
   SET MS604 = CARD_REV_BAL + MS063;
/* RS017 */ 
 UPDATE PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = PDACO_V6_1.IDN);
 /* MS001_12M_1K   */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0))
    FROM KRM023_DEDUP
    WHERE BUCKET_EF_1K > 0
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET MS001_12M_1K = (SELECT MAX(V1)
                        FROM TMP
                        WHERE IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT MAX(V1)
                        FROM TMP
                        WHERE IDN = PDACO_V6_1.IDN);
 /* FS018_12M    */
 UPDATE PDACO_V6_1
    SET FS018_12M = (SELECT COUNT(DISTINCT MON_SINCE)
                      FROM KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT COUNT(DISTINCT MON_SINCE)
                      FROM KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = PDACO_V6_1.IDN);
 /*----FS309 °Ê¥Îµ§¼Æ----*/
 UPDATE PDACO_V6_1
    SET FS309 = (SELECT COUNT(*)
                 FROM BAM086_DEDUP AS A
                 WHERE ACCOUNT_CODE = 'Y' AND
                       (CAST(ISNULL(LOAN_AMT,0) AS INT) + CAST(ISNULL(PASS_DUE_AMT,0) AS INT)) > 0
                   AND A.IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT COUNT(*)
                 FROM BAM086_DEDUP AS A
                 WHERE ACCOUNT_CODE = 'Y' AND
                       (CAST(ISNULL(LOAN_AMT,0) AS INT) + CAST(ISNULL(PASS_DUE_AMT,0) AS INT)) > 0
                   AND A.IDN = PDACO_V6_1.IDN);
 /*---START MAKING FS031---*/
 UPDATE PDACO_V6_1
   SET FS031 = (SELECT COUNT(*)
                FROM STM007_DEDUP A
                WHERE ITEM_LIST IS NOT NULL
                  AND ITEM_LIST <> ''
                  AND A.IDN = PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = PDACO_V6_1.IDN);
/* FS061_6M_1K    */
 UPDATE PDACO_V6_1
 SET FS061_6M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = PDACO_V6_1.IDN);
 /* FS101_6M       */
 UPDATE PDACO_V6_1
 SET FS101_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                   AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                   AND IDN = PDACO_V6_1.IDN);
 /*----MONTHLY DEBT ----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM BAM086_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN; 
-- MS094B Average credit card revolving balance in last 3 months
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
         THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
         ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE PDACO_V6_1
    SET MS094B = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 /* WI004_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CAST(LIMIT AS FLOAT))
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI004_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 UPDATE PDACO_V6_1
    SET AMORTIZATION_RATE = (CASE WHEN APR = 0 THEN 1/TOTAL_TERM
                                  ELSE POWER ((1 + (APR / 12)), TOTAL_TERM) * (APR / 12)
                                       / (POWER ((1 + (APR / 12)), TOTAL_TERM) - 1) END);
 UPDATE PDACO_V6_1
    SET MONTHLY_PAYMENT = ISNULL(REQUEST_AMT * AMORTIZATION_RATE, 0);
 UPDATE PDACO_V6_1
    SET FS546_9M = A.FS546_9M
    FROM (SELECT IDN, 
   	  SUM(CASE WHEN PURPOSE_CODE = '4' AND
   		      LEN(LTRIM(RTRIM(PAY_CODE_12))) + INQUIRY_MON - 1 -
   	  	      CAST(ISNULL(DATA_YYY, 0) AS INT)*12-CAST(ISNULL(DATA_MM, 0) AS INT) <= 9
   		 THEN 1
   		 ELSE 0 END) AS FS546_9M
          FROM	BAM086_DEDUP
          GROUP BY IDN) AS A
    WHERE  A.IDN = PDACO_V6_1.IDN;	
 UPDATE PDACO_V6_1
   SET FS018_12M_Z = (CASE WHEN FS018_12M = 0 THEN 1 ELSE 0 END),
       FS309_Z = (CASE WHEN FS309 = 0 THEN 1 ELSE 0 END),
       INT053_6 = FS061_6M_1K / FS101_6M,
       LN004_9M = (MONTHLY_PAYMENT/1000.0 + MS093 + (MS094B + MS105)* 0.35)/ WI004_9M,
       FS546_9M_TRAN = ISNULL(FS546_9M, 0);
 UPDATE PDACO_V6_1
   SET FS3036_T5 = (CASE WHEN BAM086_HIT = 1 AND (FS018_12M_Z = 0 OR FS309_Z = 0) THEN 1
                         WHEN BAM086_HIT = 0 AND FS018_12M_Z = 0 THEN 1 
                         ELSE 0 END),
       FS031_TRAN4 = (CASE WHEN FS031 IS NULL THEN 0
                           WHEN FS031 > 10 THEN 10
                           ELSE FS031 END),
       INT053_6_Q = INT053_6 * INT053_6,
       LN004_9M_Q = LN004_9M * LN004_9M;
 UPDATE PDACO_V6_1
   SET P4_SCORE= 0.39859	+
   	     MS604_R		*	0.00364 +
   	     RS017_R_TRAN	*	-0.09671 +  
   	     MS001_12M_1K_Q	*	0.00000207 +
   	     FS3036_T5		*	0.04757 +   
   	     FS031_TRAN4	*	0.00872 +   
   	     INT053_6_Q		*	0.09296 +   
   	     LN004_9M_Q		*	0.04015 +   
   	     FS546_9M_TRAN	*	0.01141;   
 UPDATE PDACO_V6_1
   SET PDACO_TWEN = (CASE
                     WHEN P4_SCORE IS NULL     THEN 0
                     WHEN P4_SCORE <= -0.02452 THEN 1
                     WHEN P4_SCORE <= 0.00056  THEN 2
                     WHEN P4_SCORE <= 0.01786  THEN 3
                     WHEN P4_SCORE <= 0.03197  THEN 4
                     WHEN P4_SCORE <= 0.04325  THEN 5
                     WHEN P4_SCORE <= 0.05431  THEN 6
                     WHEN P4_SCORE <= 0.06485  THEN 7
                     WHEN P4_SCORE <= 0.07343  THEN 8
                     WHEN P4_SCORE <= 0.08346  THEN 9
                     WHEN P4_SCORE <= 0.09181  THEN 10
                     WHEN P4_SCORE <= 0.10081  THEN 11
                     WHEN P4_SCORE <= 0.11041  THEN 12
                     WHEN P4_SCORE <= 0.12171  THEN 13
                     WHEN P4_SCORE <= 0.13461  THEN 14
                     WHEN P4_SCORE <= 0.14597  THEN 15
                     WHEN P4_SCORE <= 0.16077  THEN 16
                     WHEN P4_SCORE <= 0.18534  THEN 17
                     WHEN P4_SCORE <= 0.20890  THEN 18
                     WHEN P4_SCORE <= 0.25620  THEN 19
                     ELSE 20            
   		  END);
GO   		  
-----------------------------------------------------------------------------------------------------------------------
-- P5, w/o guarantor, 100K < CC limit (MS605) <= 100K
 CREATE PROCEDURE PDACO61_P5
  AS
 /* FS016F_12M  */
 UPDATE PDACO_V6_1
 SET FS016F_12M = (SELECT COUNT(*)
                   FROM KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(*)
               FROM KRM023_DEDUP AS A
               WHERE CASH = 'Y'
                 AND A.IDN = PDACO_V6_1.IDN);
 UPDATE PDACO_V6_1
   SET FS031_1M = (SELECT SUM(CASE WHEN DATEDIFF(DAY,
				CAST(RTRIM(CAST(CAST(LEFT(QUERY_DATE,3) AS INT)+1911 AS CHAR)) + SUBSTRING(QUERY_DATE,4,4) AS DATETIME),
				CAST(INQUIRY_DATE AS DATETIME)) < = 31
				THEN 1
				ELSE 0
			      END)
                   FROM STM007_DEDUP A
                   WHERE ITEM_LIST IS NOT NULL
                     AND ITEM_LIST <> ''
                     AND A.IDN = PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = PDACO_V6_1.IDN);
/* RS017 */ 
 UPDATE PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = PDACO_V6_1.IDN);
 -- MS074
 UPDATE PDACO_V6_1
    SET MS074 = A.MS074
 FROM (SELECT IDN, 
	SUM(CASE WHEN PURPOSE_CODE = '4'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS074
       FROM	BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = PDACO_V6_1.IDN;
 /* FS073B_12M     */
 DELETE FROM OPEN_LINE;
 DELETE FROM TMP;
 INSERT INTO OPEN_LINE(IDN, ISSUE, BUCKET)
    SELECT IDN, ISSUE, MAX(BUCKET_EF_1K) 
    FROM KRM023_DEDUP
    GROUP BY IDN, ISSUE; 
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, SUM(BUCKET)
    FROM OPEN_LINE
    GROUP BY IDN;
 UPDATE PDACO_V6_1
    SET FS073B_12M = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 /* ---PREPARE INTERMEDIATE TABLES FOR KRM023 AND KRM021 VARIABLES --- */
 DECLARE @I INT
   SET @I = 0;
   WHILE @I <= 13
    BEGIN
     INSERT INTO OPEN_CARD (IDN, ISSUE, MON, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'A' AND ISSUE = 'A82' THEN 'AEA'
                   ELSE ISSUE END),
             (INQUIRY_MON - @I), INQUIRY_MON
      FROM KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON - @I))
        AND ISSUE != '021'
     SET @I = @I + 1
    END;
   INSERT INTO OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
    SELECT IDN, ISSUE, MON, COUNT(*), NOW
    FROM OPEN_CARD
    GROUP BY IDN, ISSUE, MON, NOW;
   SET @I = 0
   WHILE @I <= 13
    BEGIN
     INSERT INTO OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'M' THEN 'CTM'
                   WHEN CARD_BRAND = 'V' THEN 'CTV'
                   WHEN CARD_BRAND = 'D' THEN 'CTD' END),
             (INQUIRY_MON - @I), 1, INQUIRY_MON
      FROM KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON - @I))
        AND ISSUE = '021'
     SET @I = @I + 1
    END;
   UPDATE OPEN_LINE
    SET BUCKET = 1;
 /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
   UPDATE OPEN_LINE
    SET BUCKET = 100  /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
    WHERE MON = (NOW - 13);
   SET @I = 13;
   WHILE @I > 0
    BEGIN
     UPDATE OPEN_LINE
      SET BUCKET = A.BUCKET + 1
      FROM OPEN_LINE AS A INNER JOIN OPEN_LINE
        ON A.IDN = OPEN_LINE.IDN
       AND A.ISSUE = OPEN_LINE.ISSUE
       AND A.MON = (OPEN_LINE.MON - 1)
      WHERE (A.NOW - A.MON) = @I
     SET @I = @I - 1
    END;
   INSERT INTO LATEST_STMT_MON (IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON)
    FROM OPEN_LINE
    WHERE MON <= NOW
    GROUP BY IDN, ISSUE;
   INSERT INTO LATEST_LINE (IDN, ISSUE, MON, MOB)
    SELECT A.IDN, A.ISSUE, A.MON, A.BUCKET
    FROM OPEN_LINE AS A INNER JOIN LATEST_STMT_MON AS B
      ON A.IDN = B.IDN
     AND A.ISSUE = B.ISSUE
     AND A.MON = B.MON;
 /* FS205_3M_1K_Q_TRAN	 OF DELINQUNT LINES OPENED LESS THAN A YEAR */
 /*----FS205_1K----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, MON, V1)
   SELECT IDN, 3, COUNT(*)
   FROM KRM023_DEDUP AS A
   WHERE ISSUE IN
   (SELECT ISSUE FROM LATEST_LINE
    WHERE MOB <= 12 AND IDN = A.IDN)
      AND PAY_CODE IN ('C', 'D', 'E', 'F')
      AND PAYMENT_AMT > 1
      AND (INQUIRY_MON - MON_SINCE) <= 3
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS205_3M_1K = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN
     AND A.MON = 3;
 /*----MONTHLY DEBT ----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM BAM086_DEDUP
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN; 
-- MS094B Average credit card revolving balance in last 3 months
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
         THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
         ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE PDACO_V6_1
    SET MS094B = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 /* WI003_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CASE WHEN CAST(LIMIT AS FLOAT) > 200 THEN 1.0 ELSE 0.0 END)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI003_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 UPDATE PDACO_V6_1
    SET AMORTIZATION_RATE = (CASE WHEN APR = 0 THEN 1/TOTAL_TERM
                                  ELSE POWER ((1 + (APR / 12)), TOTAL_TERM) * (APR / 12)
                                       / (POWER ((1 + (APR / 12)), TOTAL_TERM) - 1) END);
 UPDATE PDACO_V6_1
    SET MONTHLY_PAYMENT = ISNULL(REQUEST_AMT * AMORTIZATION_RATE, 0);
 UPDATE PDACO_V6_1
   SET RS017_R = POWER((CASE WHEN RS017 < 0 THEN NULL ELSE RS017 END), 0.5),
       MS074_T2 = REQUEST_AMT/1000.0 + ISNULL(MS074, 0),
       FS205_3M_1K_Q = FS205_3M_1K * FS205_3M_1K,
       WI003_9M_T = (CASE WHEN WI003_9M = 0 THEN 0.1 ELSE WI003_9M END),
       FS546_9M_TRAN = ISNULL(FS546_9M, 0),
       FS031_1M_Q = FS031_1M * FS031_1M,
       FS073B_12M_R = POWER((CASE WHEN FS073B_12M < 0 THEN NULL ELSE FS073B_12M END), 0.5);
 UPDATE PDACO_V6_1
   SET RS017_R_TRAN2 = (CASE WHEN RS017_R > 8 THEN 8
                         ELSE RS017_R END),
       MS074_T3 = (CASE WHEN MS074_T2 > 2250 THEN 2250
                           ELSE MS074_T2 END),
       FS205_3M_1K_Q_TRAN2 = ISNULL(FS205_3M_1K_Q, 0),
       LN003_9M_T = (MONTHLY_PAYMENT/1000.0 + MS093 + (MS094B + MS105)* 0.35)/ WI003_9M_T,
       FS031_1M_Q_TRAN2 = (CASE WHEN FS031_1M_Q IS NULL THEN 0
                                WHEN FS031_1M_Q > 100 THEN 100
                                ELSE FS031_1M_Q END);

 UPDATE PDACO_V6_1
   SET P5_SCORE= 0.25612	+
   	     FS016F_12M         *	0.00321   +
   	     RS017_R_TRAN2      *	-0.03459  +
   	     MS074_T3           *	0.00003294+
   	     FS205_3M_1K_Q_TRAN2*	0.00225   +
   	     LN003_9M_T         *	0.00003516+
   	     FS031_1M_Q_TRAN2   *	0.00171   +
   	     FS073B_12M_R       *	0.02631;
 UPDATE PDACO_V6_1
   SET PDACO_TWEN = (CASE
                     WHEN P5_SCORE IS NULL    THEN 0
                     WHEN P5_SCORE <= 0.00317 THEN 1
                     WHEN P5_SCORE <= 0.01542 THEN 2
                     WHEN P5_SCORE <= 0.02500 THEN 3
                     WHEN P5_SCORE <= 0.03280 THEN 4
                     WHEN P5_SCORE <= 0.04108 THEN 5
                     WHEN P5_SCORE <= 0.04851 THEN 6
                     WHEN P5_SCORE <= 0.05467 THEN 7
                     WHEN P5_SCORE <= 0.06031 THEN 8
                     WHEN P5_SCORE <= 0.06764 THEN 9
                     WHEN P5_SCORE <= 0.07515 THEN 10
                     WHEN P5_SCORE <= 0.08255 THEN 11
                     WHEN P5_SCORE <= 0.09187 THEN 12
                     WHEN P5_SCORE <= 0.10131 THEN 13
                     WHEN P5_SCORE <= 0.11072 THEN 14
                     WHEN P5_SCORE <= 0.12268 THEN 15
                     WHEN P5_SCORE <= 0.13652 THEN 16
                     WHEN P5_SCORE <= 0.15577 THEN 17
                     WHEN P5_SCORE <= 0.17960 THEN 18
                     WHEN P5_SCORE <= 0.21736 THEN 19
                     ELSE 20     
   		  END);
GO

/* CREATE_PROCEDURE_GENERATE_PDACO_SCORE */
 CREATE PROCEDURE GENERATE_PDACO6_1_SCORE
  AS
 /* CREATE TEMPORTARY INTERMEDIATE TABLES */
 UPDATE	PDACO_V6_1
    SET	REQUEST_AMT = (
	SELECT	MAX(APPLICATION_AMOUNT)
	FROM	APPLICANT
	WHERE	MSN = PDACO_V6_1.MSN
	AND	INPUT_TIME = PDACO_V6_1.INPUT_TIME
	GROUP BY MSN),
	APR = (
	SELECT	MAX(APPLICATION_RATE)
	FROM	APPLICANT
	WHERE	MSN = PDACO_V6_1.MSN
	AND	INPUT_TIME = PDACO_V6_1.INPUT_TIME
	GROUP BY MSN),
	TOTAL_TERM = (
	SELECT	MAX(APPLICATION_TERMS)
	FROM	APPLICANT
	WHERE	MSN = PDACO_V6_1.MSN
	AND	INPUT_TIME = PDACO_V6_1.INPUT_TIME
	GROUP BY MSN)

 /*INIT VARIABLES*/
 /*INIT BAM086 VARIABLES*/
 UPDATE PDACO_V6_1
    SET FS036 = 0,
	FS040 = 0,
	FS044 = 0,
	MS063 = 0,
	MS074 = 0,
	MS093 = 0,
	MS105 = 0,
	FS302 = 0,
	FS309 = 0,
	FS334 = 0,
	FS334B_1M = 0,
	FS546_9M = 0,
	FS314B = 0
 WHERE	IDN IN (SELECT	IDN
		FROM	BAM086_DEDUP)
 /*INIT KRM023 VARIABLES*/
 UPDATE PDACO_V6_1
 SET APP_MAX_BUCKET = 0,
     CDEF_FLAG_1M   = 0,
     FS002_3M_1K    = 0,
     FS014_6M	    = 0,
     FS016C_9M	    = 0,
     FS016F_12M	    = 0,
     FS018_12M	    = 0,
     FS021_9M	    = 0,
     FS059_12M_1K   = 0,
     FS059_3M_1K    = 0,
     FS061_6M_1K    = 0,
     FS073B_12M	    = 0,
     FS101_6M	    = 0,
     FS205_3M_1K    = 0,
     MS001_12M_1K   = 0,
     MS094B	    = 0,
     MS118_9M	    = 0,
     MS601	    = 0,
     MS605	    = 0,
     WI001_9M	    = 0,
     WI003_9M	    = 0,
     WI004_9M	    = 0
 FROM KRM023_DEDUP AS A
 WHERE A.IDN = PDACO_V6_1.IDN;
 /*INIT KRM021 AND KRM023 VARIABLES*/
 UPDATE PDACO_V6_1
   SET FS205_3M_1K = 0
   FROM KRM021_DEDUP AS A, KRM023_DEDUP AS B
   WHERE A.IDN = B.IDN
     AND A.IDN = PDACO_V6_1.IDN
     AND ((A.ISSUE = B.ISSUE)
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'V') AND (B.ISSUE = 'CTV'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'M') AND (B.ISSUE = 'CTM'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'D') AND (B.ISSUE = 'CTD'))
           OR ((A.ISSUE = 'A82' AND A.CARD_BRAND = 'A') AND (B.ISSUE = 'AEA'))
         );
 /*---START MAKING FS031---*/
 UPDATE PDACO_V6_1
   SET FS031 = (SELECT COUNT(*)
                FROM STM007_DEDUP A
                WHERE ITEM_LIST IS NOT NULL
                  AND ITEM_LIST <> ''
                  AND A.IDN = PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = PDACO_V6_1.IDN)
 UPDATE PDACO_V6_1
   SET FS031_1M = (SELECT SUM(CASE WHEN DATEDIFF(DAY,
				CAST(RTRIM(CAST(CAST(LEFT(QUERY_DATE,3) AS INT)+1911 AS CHAR)) + SUBSTRING(QUERY_DATE,4,4) AS DATETIME),
				CAST(INQUIRY_DATE AS DATETIME)) < = 31
				THEN 1
				ELSE 0
			      END)
                   FROM STM007_DEDUP A
                   WHERE ITEM_LIST IS NOT NULL
                     AND ITEM_LIST <> ''
                     AND A.IDN = PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = PDACO_V6_1.IDN)
/*BEGINNING KRM021-RELATED *****************************************/
/* RS017 */
 
 UPDATE PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = PDACO_V6_1.IDN)

/*BEGINNING BAM086-RELATED *****************************************/
 UPDATE PDACO_V6_1
    SET FS036 = A.FS036,
	FS040 = A.FS040,
	FS044 = A.FS044,
	MS063 = A.MS063,
	MS074 = A.MS074,
	MS093 = A.MS093,
	MS105 = A.MS105,
	FS302 = A.FS302,
	FS309 = A.FS309,
	FS334B_1M = A.FS334B_1M,
	FS546_9M = A.FS546_9M,
	FS314B = A.FS314B
 FROM (SELECT IDN, 
	SUM(CASE WHEN ((ACCOUNT_CODE2 IN ('S', 'W', 'M')) OR 
			       (ACCOUNT_CODE = 'K'))
		 THEN 1
		 ELSE 0 END) AS FS036,
	SUM(CASE WHEN (((ACCOUNT_CODE2 IS NULL) OR 
				    (ACCOUNT_CODE2 = '') OR 
				    (ACCOUNT_CODE2 = 'N')) AND 
				     ACCOUNT_CODE != 'K') 
		 THEN 1
		 ELSE 0 END) AS FS040,
	SUM(CASE WHEN PASS_DUE_AMT > 0 
		 THEN 1
		 ELSE 0 END) AS FS044,
	SUM(CASE WHEN ((ACCOUNT_CODE2 = '') OR
				   (ACCOUNT_CODE2 IS NULL) OR 
				   (ACCOUNT_CODE = 'N'))
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS063,
	SUM(CASE WHEN PURPOSE_CODE = '4'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS074,
        SUM(CASE   /* MONTHLY PAYMENT IN K PER 10K LOAN  */
			 WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10* 150 / 1000
			 WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 100 / 1000
			 WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 150 / 1000
			 WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 100 / 1000          
			 WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 238 / 1000
			 WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 177 / 1000
			 WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 127 / 1000
			 WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 72 / 1000
			 WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 177 / 1000
			 WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 238 / 1000
			 WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10 * 17 / 1000
			 WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10 * 213 / 1000
			 ELSE 0 END) AS MS093,
	SUM(CASE WHEN ACCOUNT_CODE='Y'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS105,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X') 
		 THEN 1
		 ELSE 0 END) AS FS302,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND
		         (ISNULL(LOAN_AMT,0) + ISNULL(PASS_DUE_AMT,0)) > 0
		 THEN 1
		 ELSE 0 END) AS FS309,
	SUM(CASE WHEN ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X')
		 THEN 1
		 ELSE 0 END) AS FS334B_1M,
	SUM(CASE WHEN PURPOSE_CODE = '4' AND
		      LEN(LTRIM(RTRIM(PAY_CODE_12))) + INQUIRY_MON - 1 -
	  	      CAST(ISNULL(DATA_YYY, 0) AS INT)*12-CAST(ISNULL(DATA_MM, 0) AS INT) <= 9
		 THEN 1
		 ELSE 0 END) AS FS546_9M,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND
	            (CAST(ISNULL(LOAN_AMT,0) + ISNULL(PASS_DUE_AMT,0) AS DECIMAL) / 
                    (CASE WHEN ISNULL(CONTRACT_AMT,0) = 0 THEN NULL
					   ELSE CONTRACT_AMT END)) >= 0.95
		 THEN 1
		 ELSE 0 END) AS FS314B
       FROM	BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = PDACO_V6_1.IDN	
	
 /* SEX_TRAN	GENDER */
-- UPDATE PDACO_V6_1
--   SET SEX = SUBSTRING(IDN, 2, 1)
 /* APP_MAX_BUCKET */
 UPDATE PDACO_V6_1
 SET	APP_MAX_BUCKET = (
 	SELECT MAX(BUCKET_EF_1K)
 	FROM	KRM023_DEDUP
 	WHERE	IDN = PDACO_V6_1.IDN)
 WHERE	EXISTS (
 	SELECT *
 	FROM	KRM023_DEDUP
 	WHERE	IDN = PDACO_V6_1.IDN)

 /* CDEF_FLAG_1M   */
 UPDATE PDACO_V6_1
    SET	CDEF_FLAG_1M = 1
 WHERE EXISTS (SELECT *
               FROM  KRM023_DEDUP AS A
               WHERE INQUIRY_MON - 1 - MON_SINCE <= 1 
                 AND (PAY_CODE IN ('C','D','E','F') OR
		      (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                 AND A.IDN = PDACO_V6_1.IDN)


 /* FS002_3M_1K    */
 UPDATE PDACO_V6_1
 SET FS002_3M_1K = (SELECT COUNT(DISTINCT MON_SINCE)
                    FROM KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE                */
                      AND BUCKET_EF_1K > 0
                      AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                    FROM KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE                */
                      AND BUCKET_EF_1K > 0
                      AND A.IDN = PDACO_V6_1.IDN)
 

 /* FS014_6M       */
 UPDATE PDACO_V6_1
 SET FS014_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = PDACO_V6_1.IDN)

/* FS016C_9M      */
 UPDATE PDACO_V6_1
 SET FS016C_9M = (SELECT COUNT(DISTINCT ISSUE)
                  FROM KRM023_DEDUP AS A
                  WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE */
                    AND CASH = 'Y'
                    AND PAY_CODE IN ('C','D','E','F')
                    AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                  FROM KRM023_DEDUP AS A
                  WHERE INQUIRY_MON-1 - MON_SINCE <= 9 
                    AND CASH = 'Y'
                    AND PAY_CODE IN ('C','D','E','F')
                    AND A.IDN = PDACO_V6_1.IDN)
 
 /* FS016F_12M  */
 UPDATE PDACO_V6_1
 SET FS016F_12M = (SELECT COUNT(*)
                   FROM KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(*)
               FROM KRM023_DEDUP AS A
               WHERE CASH = 'Y'
                 AND A.IDN = PDACO_V6_1.IDN)
 
 /* FS018_12M    */
 UPDATE PDACO_V6_1
 SET FS018_12M = (SELECT COUNT(DISTINCT MON_SINCE)
                   FROM KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT MON_SINCE)
                   FROM KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = PDACO_V6_1.IDN)
/* FS021_9M       */
 UPDATE PDACO_V6_1
 SET FS021_9M = (SELECT COUNT(DISTINCT MON_SINCE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                 AND  PAY_CODE IN ('C','D','E','F')
                 AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT MON_SINCE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                 AND  PAY_CODE IN ('C','D','E','F')
                 AND IDN = PDACO_V6_1.IDN)

/* FS059_12M_1K   */
 UPDATE PDACO_V6_1
 SET FS059_12M_1K = (SELECT COUNT(DISTINCT ISSUE)
                     FROM KRM023_DEDUP AS A
                     WHERE BUCKET_EF_1K > 0
                       AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
               FROM KRM023_DEDUP AS A
               WHERE BUCKET_EF_1K > 0
                 AND IDN = PDACO_V6_1.IDN)

/* FS059_3M_1K    */
 UPDATE PDACO_V6_1
 SET FS059_3M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = PDACO_V6_1.IDN)
/* FS061_6M_1K    */
 UPDATE PDACO_V6_1
 SET FS061_6M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                    FROM KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = PDACO_V6_1.IDN)
 
 /* FS073B_12M     */
 DELETE FROM OPEN_LINE;
 DELETE FROM TMP;
 INSERT INTO OPEN_LINE(IDN, ISSUE, BUCKET)
    SELECT IDN, ISSUE, MAX(BUCKET_EF_1K) 
    FROM KRM023_DEDUP
    GROUP BY IDN, ISSUE
 
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, SUM(BUCKET)
    FROM OPEN_LINE
    GROUP BY IDN
 
 UPDATE PDACO_V6_1
    SET FS073B_12M = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP)
 
 /* FS101_6M       */
 UPDATE PDACO_V6_1
 SET FS101_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                   AND IDN = PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT COUNT(DISTINCT ISSUE)
                 FROM KRM023_DEDUP
                 WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                   AND IDN = PDACO_V6_1.IDN)
 
  /*---OPEN_CARD AND OPEN_LINE CONTAIN MONTHS WHICH SHOULD HAVE TRANSACTION RECORDS BASED ON
     KRM001, OPEN_LINE CONTAINS ONE RECORD FOR EACH CREDIT LINE EACH MONTH. ONE-CARD-ONE-LINE
     ISSUERS, I.E. 021(CITI) IS PROCESSED SEPERATELY.  THE OTHER TWO ONE-CARD-ONE-LINE ISSUERS,
     I.E. 081(HSBC) ,974(AIG), FOR THEIR KRM023 DATA ARE CONSOLIDATED, ARE TREATED AS
     MULTI-CARD-ONE-LINE ISSERS---*/
 /* ---PREPARE INTERMEDIATE TABLES FOR KRM023 AND KRM021 VARIABLES --- */
 DELETE FROM OPEN_CARD;
 DELETE FROM OPEN_LINE;
 DELETE FROM LATEST_STMT_MON;
 DELETE FROM LATEST_LINE;
 DECLARE @I INT
   SET @I = 0
   WHILE @I <= 13
    BEGIN
     INSERT INTO OPEN_CARD (IDN, ISSUE, MON, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'A' AND ISSUE = 'A82' THEN 'AEA'
                   ELSE ISSUE END),
             (INQUIRY_MON-1 - @I), INQUIRY_MON-1
      FROM KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON-1 - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON-1 - @I))
        AND ISSUE != '021'
     SET @I = @I + 1
    END;
   INSERT INTO OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
    SELECT IDN, ISSUE, MON, COUNT(*), NOW
    FROM OPEN_CARD
    GROUP BY IDN, ISSUE, MON, NOW;
   SET @I = 0
   WHILE @I <= 13
    BEGIN
     INSERT INTO OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'M' THEN 'CTM'
                   WHEN CARD_BRAND = 'V' THEN 'CTV'
                   WHEN CARD_BRAND = 'D' THEN 'CTD' END),
             (INQUIRY_MON-1 - @I), 1, INQUIRY_MON-1
      FROM KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON-1 - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON-1 - @I))
        AND ISSUE = '021'
     SET @I = @I + 1
    END;
   UPDATE OPEN_LINE
    SET BUCKET = 1;
 /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
   UPDATE OPEN_LINE
    SET BUCKET = 100  /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
    WHERE MON = (NOW - 13);
   SET @I = 13;
   WHILE @I > 0
    BEGIN
     UPDATE OPEN_LINE
      SET BUCKET = A.BUCKET + 1
      FROM OPEN_LINE AS A INNER JOIN OPEN_LINE
        ON A.IDN = OPEN_LINE.IDN
       AND A.ISSUE = OPEN_LINE.ISSUE
       AND A.MON = (OPEN_LINE.MON - 1)
      WHERE (A.NOW - A.MON) = @I
     SET @I = @I - 1
    END;
   INSERT INTO LATEST_STMT_MON (IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON)
    FROM OPEN_LINE
    WHERE MON <= NOW
    GROUP BY IDN, ISSUE;
   INSERT INTO LATEST_LINE (IDN, ISSUE, MON, MOB)
    SELECT A.IDN, A.ISSUE, A.MON, A.BUCKET
    FROM OPEN_LINE AS A INNER JOIN LATEST_STMT_MON AS B
      ON A.IDN = B.IDN
     AND A.ISSUE = B.ISSUE
     AND A.MON = B.MON;

 /* FS205_3M_1K_Q_TRAN	 OF DELINQUNT LINES OPENED LESS THAN A YEAR */
 /*----FS205_1K----*/
 DELETE FROM TMP;
 INSERT INTO TMP (IDN, MON, V1)
   SELECT IDN, 3, COUNT(*)
   FROM KRM023_DEDUP AS A
   WHERE ISSUE IN (SELECT ISSUE FROM LATEST_LINE
                   WHERE MOB <= 12 AND IDN = A.IDN)
     AND PAY_CODE IN ('C', 'D', 'E', 'F')
     AND PAYMENT_AMT > 1
     AND (INQUIRY_MON-1 - MON_SINCE) <= 3
   GROUP BY IDN;
 UPDATE PDACO_V6_1
   SET FS205_3M_1K = V1
   FROM TMP AS A
   WHERE A.IDN = PDACO_V6_1.IDN
     AND A.MON = 3;
 /* MS001_12M_1K   */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0))
    FROM KRM023_DEDUP
    WHERE BUCKET_EF_1K > 0
    GROUP BY IDN, MON_SINCE;
 
 UPDATE PDACO_V6_1
    SET MS001_12M_1K = (SELECT MAX(V1)
                        FROM TMP
                        WHERE IDN = PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT MAX(V1)
                        FROM TMP
                        WHERE IDN = PDACO_V6_1.IDN);
 
 /* MS094B          */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
         THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
         ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 
 UPDATE PDACO_V6_1
    SET MS094B = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);
 
 /* MS118_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, 
      MIN((ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)) / CAST(LIMIT AS FLOAT))
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=9  /* NO   30-DAY RULE */
    AND  CAST(LIMIT AS FLOAT) > 0
    AND  PAY_CODE IN ('C','D','E','F')
    AND  PAYMENT_AMT+ISNULL(SPREAD_PAYMENT,0) > 1    /* TO ELIMINATE THOSE SMALL REVOLING LINES */
    GROUP BY IDN

 UPDATE PDACO_V6_1
    SET MS118_9M = (
     SELECT V1
     FROM TMP
     WHERE IDN = PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM TMP);


 /* MS601          */
 DELETE FROM OPEN_LINE;
 DELETE FROM TMP;
 INSERT INTO OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
    GROUP BY IDN, ISSUE;
 
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, SUM(ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)) AS MS601
    FROM KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM OPEN_LINE 
                  WHERE IDN = A.IDN
                  AND  ISSUE = A.ISSUE
                  AND  MON = A.MON_SINCE)
      AND PAY_CODE IN ('C','D','E','F')
    GROUP BY IDN;

 UPDATE PDACO_V6_1
 SET MS601 = (SELECT V1
              FROM TMP
              WHERE IDN = PDACO_V6_1.IDN)
 WHERE IDN IN (SELECT IDN
               FROM TMP);

 /* MS605          */
 DELETE FROM OPEN_LINE;
 DELETE FROM TMP;
 INSERT INTO OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=3  /* NO   30-DAY RULE */
    AND  CAST(LIMIT AS FLOAT) > 0
    GROUP BY IDN, ISSUE;
 INSERT INTO TMP(IDN, V1)
    SELECT IDN, AVG(CAST(LIMIT AS FLOAT))
    FROM KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM OPEN_LINE
                  WHERE IDN = A.IDN
                  AND  ISSUE = A.ISSUE
                  AND  MON = A.MON_SINCE)
    GROUP BY IDN; 
 UPDATE PDACO_V6_1
 SET MS605 = (SELECT V1
              FROM TMP
              WHERE IDN = PDACO_V6_1.IDN)
 WHERE IDN IN (SELECT IDN
               FROM TMP);

 /* WI001_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, COUNT(DISTINCT ISSUE)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI001_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 /* WI003_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CASE WHEN CAST(LIMIT AS FLOAT) > 200 THEN 1.0 ELSE 0.0 END)
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI003_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 /* WI004_9M       */
 DELETE FROM TMP;
 INSERT INTO TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CAST(LIMIT AS FLOAT))
    FROM KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE PDACO_V6_1
    SET WI004_9M = 
        (SELECT SUM(V1) / 9.0
         FROM TMP A
         WHERE PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM TMP A
                 WHERE PDACO_V6_1.IDN = A.IDN);
 
 UPDATE PDACO_V6_1
   SET FT102_42 = FS102_3M - (FS102_9M - FS102_6M),
       INT015_3 = (CASE WHEN FS101_3M = 0 THEN NULL ELSE FS016_3M / FS101_3M END),
       FT059_1K_43 = FS059_1K_3M - (FS059_1K_6M - FS059_1K_3M),
       FT059_1K_42 = FS059_1K_3M - (FS059_1K_9M - FS059_1K_6M),
       FT212_1K_43 = FS212_1K_3M - (FS212_1K_6M - FS212_1K_3M),
       INT028_9 = (CASE WHEN FS101_9M = 0 THEN NULL ELSE FS014_9M / FS101_9M END);
 UPDATE PDACO_V6_1
   SET FT059_1K_43_R = POWER((CASE WHEN FT059_1K_43 < 0 THEN NULL ELSE FT059_1K_43 END), 0.5),
       FT059_1K_42_Q = POWER (FT059_1K_42, 2),
       FT102_42_R = POWER((CASE WHEN FT102_42 < 0 THEN NULL ELSE FT102_42 END), 0.5),
       FT212_1K_43_Q = POWER (FT212_1K_43, 2),
       FS205_3M_1K_Q = POWER (FS205_3M_1K, 2);
 UPDATE PDACO_V6_1
   SET INT015_3_TRAN = (CASE WHEN INT015_3 IS NULL THEN 1
      			    WHEN INT015_3 > 1 THEN 1
      			    ELSE INT015_3 END),
       FT102_42_R_TRAN = (CASE WHEN FT102_42_R IS NULL THEN -0.2
      			    WHEN FT102_42_R > 1.7 THEN 1.7
      			    ELSE FT102_42_R END),
       FT212_1K_43_Q_TRAN = (CASE WHEN FT212_1K_43_Q IS NULL THEN 0
      			    ELSE FT212_1K_43_Q END),
       FT059_1K_42_Q_TRAN = (CASE WHEN FT059_1K_42_Q > 16 THEN 16
      			       ELSE FT059_1K_42_Q END),
       FS031_TRAN = (CASE WHEN FS031 IS NULL THEN -1
      		       WHEN FS031 > 9 THEN 9
      		       ELSE FS031 END),
       SEX_TRAN = (CASE WHEN SEX = 1 THEN 1 ELSE 0 END),
       APP_LAST_MONTH_BUCKET_TRAN = (CASE WHEN APP_LAST_MONTH_BUCKET IS NULL THEN 1
      			    WHEN APP_LAST_MONTH_BUCKET > 2 THEN 2
      			    ELSE APP_LAST_MONTH_BUCKET END),
       FS205_3M_1K_Q_TRAN = (CASE WHEN FS205_3M_1K_Q IS NULL THEN 0
      		       WHEN FS205_3M_1K_Q > 60 THEN 60
      		       ELSE FS205_3M_1K_Q END),
       INT028_9_TRAN = (CASE WHEN INT028_9 IS NULL THEN 0.3
      		       WHEN INT028_9 > 0.3 THEN 0.3
      		       ELSE INT028_9 END),
       FT059_1K_43_R_TRAN = (CASE WHEN FT059_1K_43_R IS NULL THEN 1
      			       ELSE FT059_1K_43_R END),
       FS051_TRAN = (CASE WHEN FS051 IS NULL THEN 2
      		       WHEN FS051 > 5 THEN 5
      		       ELSE FS051 END);
 UPDATE PDACO_V6_1
   SET PDACO_SCORE= 0.01474		+
   	     INT015_3_TRAN		*	0.04190 +
   	     FT059_1K_42_Q_TRAN		*	0.00964 +
   	     FT212_1K_43_Q_TRAN		*	0.01186 +
   	     FT102_42_R_TRAN		*	-0.02683 +
   	     FS031_TRAN			*	0.00573 +
   	     MS117_6M			*	0.04292 +
   	     FS005_1K_3M		*	0.12726 +
   	     SEX_TRAN 			*	0.02654 +
   	     APP_LAST_MONTH_BUCKET_TRAN	*	0.05866 +
   	     FS205_3M_1K_Q_TRAN		*	0.00058973 +
   	     INT028_9_TRAN		*	-0.08045 +
   	     FT059_1K_43_R_TRAN		*	0.01873 +
   	     FS051_TRAN 		*	0.00345;
 UPDATE PDACO_V6_1
   SET PDACO_TWEN = (CASE
                     WHEN PDACO_SCORE IS NULL THEN 0
                     WHEN PDACO_SCORE <= -0.03231 THEN 1
                     WHEN PDACO_SCORE <= -0.02275 THEN 2
                     WHEN PDACO_SCORE <= -0.01479 THEN 3
                     WHEN PDACO_SCORE <= -0.00919 THEN 4
                     WHEN PDACO_SCORE <= -0.00438 THEN 5
                     WHEN PDACO_SCORE <= 0.00101 THEN 6
                     WHEN PDACO_SCORE <= 0.00624 THEN 7
                     WHEN PDACO_SCORE <= 0.01245 THEN 8
                     WHEN PDACO_SCORE <= 0.01836 THEN 9
                     WHEN PDACO_SCORE <= 0.02482 THEN 10
                     WHEN PDACO_SCORE <= 0.03219 THEN 11
                     WHEN PDACO_SCORE <= 0.03963 THEN 12
                     WHEN PDACO_SCORE <= 0.04759 THEN 13
                     WHEN PDACO_SCORE <= 0.05585 THEN 14
                     WHEN PDACO_SCORE <= 0.06657 THEN 15
                     WHEN PDACO_SCORE <= 0.07865 THEN 16
                     WHEN PDACO_SCORE <= 0.09435 THEN 17
                     WHEN PDACO_SCORE <= 0.11509 THEN 18
                     WHEN PDACO_SCORE <= 0.15002 THEN 19
                     ELSE 20
   		  END)
 UPDATE PDACO_V6_1
   SET PB_IN = (CASE
                WHEN PDACO_TWEN = 0  THEN NULL
                WHEN PDACO_TWEN = 1  THEN 0.0070
                WHEN PDACO_TWEN = 2  THEN 0.0080
                WHEN PDACO_TWEN = 3  THEN 0.0095
                WHEN PDACO_TWEN = 4  THEN 0.0105
                WHEN PDACO_TWEN = 5  THEN 0.0120
                WHEN PDACO_TWEN = 6  THEN 0.0135
                WHEN PDACO_TWEN = 7  THEN 0.0155
                WHEN PDACO_TWEN = 8  THEN 0.0175
                WHEN PDACO_TWEN = 9  THEN 0.0205
                WHEN PDACO_TWEN = 10 THEN 0.0235
                WHEN PDACO_TWEN = 11 THEN 0.0265
                WHEN PDACO_TWEN = 12 THEN 0.0300
                WHEN PDACO_TWEN = 13 THEN 0.0340
                WHEN PDACO_TWEN = 14 THEN 0.0385
                WHEN PDACO_TWEN = 15 THEN 0.0430
                WHEN PDACO_TWEN = 16 THEN 0.0500
                WHEN PDACO_TWEN = 17 THEN 0.0640
                WHEN PDACO_TWEN = 18 THEN 0.0885
                WHEN PDACO_TWEN = 19 THEN 0.1190
                WHEN PDACO_TWEN = 20 THEN 0.1800
     	     END);


GO
/* END_OF_CREATE_PROCEDURE_GENERATE_PDACO_SCORE */


CREATE PROCEDURE KTBFM_PDACO_RSCORE
 AS

DECLARE @MSN VARCHAR(20)
DECLARE @IDN     CHAR(11)
DECLARE @INQUIRY_DATE CHAR(8)
DECLARE @YEAR INT
DECLARE @MONTH INT
DECLARE @DAY INT
DECLARE @NOW INT


---------CREATE WORKING TABLE -----
--------------------------------
DECLARE CURSOR1 CURSOR FOR
SELECT MSN, IDN, INQUIRY_DATE
FROM APP_INFO

OPEN CURSOR1

FETCH NEXT FROM CURSOR1
INTO @MSN, @IDN, @INQUIRY_DATE

WHILE @@FETCH_STATUS = 0
BEGIN

   SET @YEAR = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 1, 4))
   SET @MONTH = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 5, 2))
   SET @DAY = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 7,2))

   IF (@DAY <= 15)
     BEGIN
       SET @MONTH = @MONTH - 1
     END
   IF (@MONTH = 0)
     BEGIN
       SET @MONTH = 12;
       SET @YEAR = @YEAR - 1
     END

   SET @NOW = (@YEAR - 1911) * 12 + @MONTH;

   EXEC PREPARE_PDACO_JCIC_DATA @MSN, @IDN,@NOW
   EXEC GENERATE_PDACO_SCORE @NOW

   INSERT INTO PDACO_SCORE_NEW_DEFINITION
     SELECT * FROM PDACO_V6_1

 DELETE FROM BAM086_DEDUP;
 DELETE FROM BAM086_BUCKET;
 DELETE FROM KRM021_DEDUP;
 DELETE FROM KRM023_DEDUP;
 DELETE FROM KRM037_DEDUP;
 DELETE FROM STM007_DEDUP;
 DELETE FROM JAS002_T;
 DELETE FROM JAS002_T_DEDUP;
 DELETE FROM BASE;
 DELETE FROM TMP;
 DELETE FROM TMP1;
 DELETE FROM OPEN_CARD;
 DELETE FROM OPEN_LINE;
 DELETE FROM LATEST_STMT_MON;
 DELETE FROM LATEST_LINE;
 DELETE FROM KRM023_TMP;
 DELETE FROM KRM023_TMP1;
 DELETE FROM PDACO_V6_1;

   FETCH NEXT FROM CURSOR1
   INTO @MSN, @IDN, @INQUIRY_DATE
END

CLOSE CURSOR1
DEALLOCATE CURSOR1


 DROP TABLE BAM086_DEDUP;
 DROP TABLE BAM086_BUCKET;
 DROP TABLE KRM021_DEDUP;
 DROP TABLE KRM023_DEDUP;
 DROP TABLE KRM037_DEDUP;
 DROP TABLE STM007_DEDUP;
 DROP TABLE JAS002_T;
 DROP TABLE JAS002_T_DEDUP;
 DROP TABLE BASE;
 DROP TABLE TMP;
 DROP TABLE TMP1;
 DROP TABLE OPEN_CARD;
 DROP TABLE OPEN_LINE;
 DROP TABLE LATEST_STMT_MON;
 DROP TABLE LATEST_LINE;
 DROP TABLE KRM023_TMP;
 DROP TABLE KRM023_TMP1;
 DROP TABLE PDACO_V6_1;

GO

-- EXEC KTBFM_PDACO_RSCORE

