--USE KTB_PLOAN_20060710
GO

/* CREATE_WORKING_TABLE */
 CREATE TABLE #BAM086_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN 		CHAR(11),
	DATA_YYY        CHAR(3),
	DATA_MM         CHAR(2),
	BANK_CODE       CHAR(7),
	BANK_NAME       CHAR(40),
	ACCOUNT_CODE    CHAR(1),
	ACCOUNT_CODE2   CHAR(1),
	PURPOSE_CODE    CHAR(1),
	CONTRACT_AMT    DECIMAL (10),
	LOAN_AMT        DECIMAL (10),
	PASS_DUE_AMT    DECIMAL (10),
	PAY_CODE_12     CHAR(12),
	CO_LOAN         CHAR(1),
	UN_MARK         CHAR(1),
	U_YYYMMDD       CHAR(8),
	U_RATE          CHAR(3),
	IB_MARK         CHAR(1),
	IAB_BAN         CHAR(8),
	IAB_NAME        CHAR(60),
	R_YYYMMDD       CHAR(7),
	REFUND_AMT      CHAR(10),
	CK_REF          CHAR(1),
 	BANK_CODE2	CHAR (3),
 	MON_SINCE	INT,
 	CYCLE		INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 CREATE TABLE #BAM086_BUCKET (
 	IDN		CHAR(14),
 	BANK_CODE	CHAR(3),
 	MON_SINCE	INT,
 	BUCKET		FLOAT);
 CREATE TABLE #KRM021_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN		CHAR (11),
 	CARD_BRAND	CHAR (1),
 	CARD_TYPE	CHAR (1),
 	ISSUE		CHAR (3),
 	ISSUE_NAME	CHAR (40),
 	START_DATE	CHAR (7),
 	STOP_DATE	CHAR (7),
 	STOP_CODE	CHAR (1),
 	AB_CODE		CHAR (1),
 	M_S		CHAR (1),
        RELA		CHAR(1),
        LIMIT		CHAR(6),
        RISK		CHAR(6),
        CLEAR_DATE	CHAR(7),
        IDN_PRI		CHAR(10),
        CNAME		CHAR(12),
        REMARK		CHAR(40),
 	START_MON_SINCE	INT,
 	END_MON_SINCE	INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 CREATE TABLE #KRM023_DEDUP (
 	MSN		VARCHAR(20),
 	INQUIRY_DATE	CHAR(10),
 	IDN		CHAR (11),
	YRMON 		CHAR (5),
	ISSUE 		CHAR (3),
	ISSUE_NAME 	CHAR (40),
	KR_CODE 	CHAR (7),
	LIMIT 		CHAR (5),
	PAYMENT 	CHAR (3),
	CASH 		CHAR (1),
	PAY_CODE 	CHAR (1),
 	MON_SINCE	INT,
 	PAYMENT_AMT	FLOAT,
	SPREAD_PAYMENT	FLOAT DEFAULT 0.0,
 	BUCKET_DEF_1K	INT DEFAULT 0,
 	BUCKET_EF_1K	INT DEFAULT 0,
 	BUCKET_F_1K	INT DEFAULT 0,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 CREATE TABLE #KRM037_DEDUP (
	MSN		VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
	IDN		CHAR(10),
	IDN_BAN		CHAR(10),
	BILL_DATE	CHAR(7),
	ISSUE		CHAR(3),
	ISSUE_NAME 	CHAR(40),
	CARD_TYPE 	CHAR(7),
	PERM_LIMIT 	DECIMAL(7),
	TEMP_LIMIT 	DECIMAL(7),
	CASH_LIMIT 	DECIMAL(7),
	PAYABLE 	CHAR(3),
	CASH_LENT 	DECIMAL(8),
	LAST_PAYA 	CHAR(3),
	REVOL_BAL 	DECIMAL(9),
	PAY_STAT 	CHAR(1),
	PAY_CODE 	CHAR(1),
	REVOL_RATE 	DECIMAL(4),
	PRE_OWED 	DECIMAL(8),
	DEBT_CODE 	CHAR(1),
	CLOSE_CODE 	CHAR(1),
	CLEAR_DATE 	CHAR(7),
	MON_SINCE	INT,
 	PAYMENT_AMT	FLOAT,
 	BUCKET_DEF_1K	INT DEFAULT 0,
 	BUCKET_EF_1K	INT DEFAULT 0,
 	BUCKET_F_1K	INT DEFAULT 0,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT		INT);
 CREATE TABLE #VAM102_DEDUP (
 	MSN		CHAR(14),
 	IDN		CHAR(11),
 	INQUIRY_DATE	CHAR(8),
 	INPUT_TIME	CHAR(12),
 	DATA_DATE	CHAR(7),
 	MAINCODE	CHAR(1),
 	MAINNOTE	CHAR(36),
 	SUBCODE		CHAR(1),
 	SUBNOTE		CHAR(60),
 	NOTE		CHAR(512),
 	CNT		INT);
 CREATE TABLE #STM007_DEDUP (
 	MSN VARCHAR(20),
 	INQUIRY_DATE	    CHAR(10),
 	IDN CHAR (11),
 	BANK_CODE CHAR (7),
 	BANK_NAME CHAR (40),
 	QUERY_DATE CHAR (7),
 	ITEM_LIST CHAR (10),
	INQ_PURPOSE_1	CHAR(1),
	INQ_PURPOSE	CHAR(30),
 	QUERY_MON_SINCE INT,
 	INPUT_TIME	CHAR(12),
 	INQUIRY_MON	INT,
 	CNT INT);
 CREATE TABLE #JAS002_T (
 	MSN VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
 	IDN CHAR (11),
 	REASON CHAR (1),
 	DATE_HAPPEN CHAR (7),
 	MON_SINCE INT);
 CREATE TABLE #JAS002_T_DEDUP (
 	MSN VARCHAR(20),
	INQUIRY_DATE	CHAR(10),
 	IDN CHAR (11),
 	REASON CHAR (1),
 	DATE_HAPPEN CHAR (7),
 	MON_SINCE INT,
 	INQUIRY_MON	INT,
 	CNT INT);
 CREATE TABLE #BASE_TMP (
 	IDN CHAR (11),
 	AVAIL_FLAG INT);
 CREATE TABLE #BASE (
  	IDN VARCHAR (11),
 	AVAIL_FLAG INT DEFAULT 0,
 	JAS002_DEFECT INT DEFAULT 0,
 	KRM021_HIT INT DEFAULT 0,
 	KRM023_HIT INT DEFAULT 0,
 	MAX_BUCKET INT DEFAULT 0,
 	FS044 INT DEFAULT 0,
 	CASH_MAX_BUCKET INT DEFAULT 0,
 	CASH_UTILIZATION INT DEFAULT 0,
        IND001 INT DEFAULT 0);
 CREATE TABLE #TMP (
	IDN CHAR(11),
	MON INT,
	V1 DECIMAL (16, 8),
	V2 DECIMAL (16, 8),
	V3 DECIMAL (16, 8));
 CREATE TABLE #TMP1 (
	IDN CHAR(11),
	MON INT,
	V1 DECIMAL (16, 8));
 CREATE TABLE #OPEN_ISSUE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT);
 CREATE TABLE #OPEN_CARD (
	IDN CHAR(11),
	ISSUE CHAR(3),
	NOW   INT,
	MON INT);
 CREATE TABLE #OPEN_LINE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT,
	NOW   INT,
	CARDS INT,
	BUCKET INT);
 CREATE TABLE #LATEST_STMT_MON (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT);
 CREATE TABLE #LATEST_LINE (
	IDN CHAR(11),
	ISSUE CHAR(3),
	MON INT,
	MOB INT);
 CREATE TABLE #KRM023_TMP (
	MSN VARCHAR(20),
	IDN CHAR(11),
	INQUIRY_DATE	CHAR(10),
        YRMON CHAR(5),
	MON_SINCE INT,
	ISSUE CHAR(3),
	ISSUE_NAME CHAR(40),
	LIMIT CHAR(5),
	PAYMENT CHAR(3),
	PAYMENT_AMT FLOAT,
	CASH CHAR,
	PAY_CODE CHAR,
	SPREAD_PAYMENT FLOAT);
 CREATE TABLE #KRM023_TMP1 (
	MSN VARCHAR(20),
	IDN CHAR(11),
	INQUIRY_DATE	CHAR(10),
        YRMON CHAR(5),
	MON_SINCE INT,
	ISSUE CHAR(3),
	ISSUE_NAME CHAR(40),
	LIMIT CHAR(5),
	PAYMENT_AMT FLOAT,
	CASH CHAR,
	PAY_CODE CHAR,
	SPREAD_PAYMENT FLOAT,
        INQUIRY_MON INT);
 CREATE TABLE #PDACO_V6_1 (
	MSN		VARCHAR(20),
	INPUT_TIME	CHAR(12),
	IDN		CHAR (11),
	INQUIRY_DATE	CHAR(8),
	NOW		INT,
	REQUEST_AMT	INT,
	APR		DECIMAL(6,5),
	TOTAL_TERM	INT,
	APP_FEE 	INT,
	LOAN_AMT	INT,
	FSC_AMT		INT,
	MONTHLY_INCOME	INT,
	SCORECARD	INT,
	PB		DECIMAL(16,8),
	SCREEN_CODE	INT,
	SCREEN_MSG	VARCHAR(64),
	AVAIL_FLAG	INT,
	JAS002_DEFECT	INT DEFAULT 0,
	KRM021_HIT	INT DEFAULT 0,
	KRM023_HIT	INT DEFAULT 0,
	BAM086_HIT	INT DEFAULT 0,
	GRAY2_FLAG	INT DEFAULT 0,
	MAX_BUCKET	INT DEFAULT 0,
	FS044		INT DEFAULT 0,
	FS059_1K_12M	INT DEFAULT 0,
	FS302		INT DEFAULT 0,
	FS334		INT DEFAULT 0,
	CARD_FORCE_STOP INT DEFAULT 0,
	CASH_MAX_BUCKET INT DEFAULT 0,
	CASH_UTILIZATION INT DEFAULT 0,
	IND001		INT DEFAULT 0,
	CARD_REV_BAL	FLOAT DEFAULT 0,
	MS105		FLOAT DEFAULT 0,
	REVOLVING_AMT	FLOAT DEFAULT 0,
	DEBT_FLAG	FLOAT DEFAULT 0,
	NOTE_FLAG	FLOAT DEFAULT 0,
	P0_SCORE	DECIMAL(16,8),
	FS302_FG	DECIMAL(16,8),
	P2_SCORE	DECIMAL(16,8),
	FS016C_9M_T1	DECIMAL(16,8),
	LN001_9M	DECIMAL(16,8),
	LN001_9M_T2	DECIMAL(16,8),
	P3_SCORE	DECIMAL(16,8),
	SECURE_FLAG	DECIMAL(16,8),
	UNSECURE_FLAG	DECIMAL(16,8),
	LU_FLAG		DECIMAL(16,8),
	P4_SCORE	DECIMAL(16,8),
       RS017_R_TRAN	DECIMAL(16,8),
	MS604_R		DECIMAL(16,8),
	MS001_12M_1K_Q	DECIMAL(16,8),
	FS061_6M_1K	DECIMAL(16,8),
	FS018_12M_Z	DECIMAL(16,8),
	FS309_Z		DECIMAL(16,8),
	INT053_6	DECIMAL(16,8),
	INT053_6_Q	DECIMAL(16,8),
	LN004_9M	DECIMAL(16,8),
	LN004_9M_Q	DECIMAL(16,8),
	FS546_9M_TRAN	DECIMAL(16,8),
	FS3036_T5	DECIMAL(16,8),
	FS031_TRAN4	DECIMAL(16,8),
	P5_SCORE	DECIMAL(16,8),
        RS017_R		DECIMAL(16,8),
        RS017_R_TRAN2	DECIMAL(16,8),
        MS074_T2	DECIMAL(16,8),
        MS074_T3	DECIMAL(16,8),
        FS205_3M_1K_Q	DECIMAL(16,8),
        FS205_3M_1K_Q_TRAN2	DECIMAL(16,8),
        WI003_9M_T	DECIMAL(16,8),
        LN003_9M_T	DECIMAL(16,8),
        FS031_1M_Q	DECIMAL(16,8),
        FS031_1M_Q_TRAN2 DECIMAL(16,8),
        FS073B_12M_R	DECIMAL(16,8),
        PDACO_TWEN 	DECIMAL(16,8),
	MS093		DECIMAL(16,8),
	MS094B		DECIMAL(16,8),
	AMORTIZATION_RATE DECIMAL(16,8),
	MONTHLY_PAYMENT	DECIMAL(16,8),
	MS101		DECIMAL(16,8),
	FS031		DECIMAL(16,8) DEFAULT 0.0,
	FS031_1M	DECIMAL(16,8) DEFAULT 0.0,
	RS017		DECIMAL(16,8),
	STOP_CODE_FLAG	DECIMAL(16,8),
	FS036		DECIMAL(16,8),
	FS040		DECIMAL(16,8),
	MS063		DECIMAL(16,8) DEFAULT 0.0,
	MS074		DECIMAL(16,8),
	FS309		DECIMAL(16,8),
	FS334B_1M	DECIMAL(16,8) DEFAULT 0.0,
	FS546_9M	DECIMAL(16,8),
	FS314B		DECIMAL(16,8),
	APP_MAX_BUCKET	DECIMAL(16,8),
	CDEF_FLAG_1M	DECIMAL(16,8) DEFAULT 0,
	FS002_3M_1K	DECIMAL(16,8),
	FS014_6M	DECIMAL(16,8),
	FS016C_9M	DECIMAL(16,8),
	FS016F_12M	DECIMAL(16,8),
	FS018_12M	DECIMAL(16,8),
	FS021_9M	DECIMAL(16,8),
	FS059_12M_1K	DECIMAL(16,8),
	FS059_3M_1K	DECIMAL(16,8) DEFAULT 0.0,
	FS073B_12M	DECIMAL(16,8),
	FS101_6M	DECIMAL(16,8),
	FS205_3M_1K	DECIMAL(16,8),
	MS001_12M_1K	DECIMAL(16,8),
	MS118_9M	DECIMAL(16,8),
	MS601		DECIMAL(16,8),
	MS604		DECIMAL(16,8),
	MS605		DECIMAL(16,8) DEFAULT 0.0,
	MS606		DECIMAL(16,8) DEFAULT 0.0,
	WI001_9M	DECIMAL(16,8),
	WI003_9M	DECIMAL(16,8),
	WI004_9M	DECIMAL(16,8),
	RSCORE  	DECIMAL(16,8));

/* DROP_WORKING_TABLES */
 IF OBJECT_ID('tempdb..#BAM086_DEDUP') IS NOT NULL
    DROP TABLE #BAM086_DEDUP;
 IF OBJECT_ID('tempdb..#BAM086_BUCKET') IS NOT NULL
    DROP TABLE #BAM086_BUCKET;
 IF OBJECT_ID('tempdb..#KRM021_DEDUP') IS NOT NULL
    DROP TABLE #KRM021_DEDUP;
 IF OBJECT_ID('tempdb..#KRM023_DEDUP') IS NOT NULL
    DROP TABLE #KRM023_DEDUP;
 IF OBJECT_ID('tempdb..#KRM037_DEDUP') IS NOT NULL
    DROP TABLE #KRM037_DEDUP;
 IF OBJECT_ID('tempdb..#VAM102_DEDUP') IS NOT NULL
    DROP TABLE #VAM102_DEDUP;
 IF OBJECT_ID('tempdb..#STM007_DEDUP') IS NOT NULL
    DROP TABLE #STM007_DEDUP;
 IF OBJECT_ID('tempdb..#JAS002_T') IS NOT NULL
    DROP TABLE #JAS002_T;
 IF OBJECT_ID('tempdb..#JAS002_T_DEDUP') IS NOT NULL
    DROP TABLE #JAS002_T_DEDUP;
 IF OBJECT_ID('tempdb..#BASE_TMP') IS NOT NULL
    DROP TABLE #BASE_TMP;
 IF OBJECT_ID('tempdb..#BASE') IS NOT NULL
    DROP TABLE #BASE;
 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
    DROP TABLE #TMP;
 IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
    DROP TABLE #TMP1;
 IF OBJECT_ID('tempdb..#OPEN_ISSUE') IS NOT NULL
    DROP TABLE #OPEN_ISSUE;
 IF OBJECT_ID('tempdb..#OPEN_CARD') IS NOT NULL
    DROP TABLE #OPEN_CARD;
 IF OBJECT_ID('tempdb..#OPEN_LINE') IS NOT NULL
    DROP TABLE #OPEN_LINE;
 IF OBJECT_ID('tempdb..#LATEST_STMT_MON') IS NOT NULL
    DROP TABLE #LATEST_STMT_MON;
 IF OBJECT_ID('tempdb..#LATEST_LINE') IS NOT NULL
    DROP TABLE #LATEST_LINE;
 IF OBJECT_ID('tempdb..#KRM023_TMP') IS NOT NULL
    DROP TABLE #KRM023_TMP;
 IF OBJECT_ID('tempdb..#KRM023_TMP1') IS NOT NULL
    DROP TABLE #KRM023_TMP1;
 IF OBJECT_ID('tempdb..#PDACO_V6_1') IS NOT NULL
    DROP TABLE #PDACO_V6_1;
/*
 if exists (select * from dbo.sysobjects where id = object_id(N'BAM086_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE BAM086_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'BAM086_BUCKET') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE BAM086_BUCKET;
 if exists (select * from dbo.sysobjects where id = object_id(N'KRM021_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE KRM021_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'KRM023_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE KRM023_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'KRM037_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE KRM037_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'VAM102_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE VAM102_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'STM007_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE STM007_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'JAS002_T') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE JAS002_T;
 if exists (select * from dbo.sysobjects where id = object_id(N'JAS002_T_DEDUP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE JAS002_T_DEDUP;
 if exists (select * from dbo.sysobjects where id = object_id(N'BASE_TMP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE BASE_TMP;
 if exists (select * from dbo.sysobjects where id = object_id(N'BASE') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE BASE;
 if exists (select * from dbo.sysobjects where id = object_id(N'TMP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE TMP;
 if exists (select * from dbo.sysobjects where id = object_id(N'TMP1') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE TMP1;
 if exists (select * from dbo.sysobjects where id = object_id(N'OPEN_ISSUE') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE OPEN_ISSUE;
 if exists (select * from dbo.sysobjects where id = object_id(N'OPEN_CARD') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE OPEN_CARD;
 if exists (select * from dbo.sysobjects where id = object_id(N'OPEN_LINE') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE OPEN_LINE;
 if exists (select * from dbo.sysobjects where id = object_id(N'LATEST_STMT_MON') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE LATEST_STMT_MON;
 if exists (select * from dbo.sysobjects where id = object_id(N'LATEST_LINE') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE LATEST_LINE;
 if exists (select * from dbo.sysobjects where id = object_id(N'KRM023_TMP') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE KRM023_TMP;
 if exists (select * from dbo.sysobjects where id = object_id(N'KRM023_TMP1') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE KRM023_TMP1;
 if exists (select * from dbo.sysobjects where id = object_id(N'#PDACO_V6_1') and OBJECTPROPERTY(id, N'IsUserTable') = 1) 
    DROP TABLE PDACO_V6_1;
*/
GO
/* CREATE_PROCEDURE_PREPARE_JCIC_DATA */
 CREATE PROCEDURE PREPARE_PDACO_JCIC_DATA
  (@MSN VARCHAR(20),
   @INPUT_TIME CHAR(12))
  AS
 INSERT INTO #PDACO_V6_1(MSN, IDN, INPUT_TIME, REQUEST_AMT, APR, TOTAL_TERM, MONTHLY_INCOME)
    SELECT	MSN, IDN, INPUT_TIME, APPLICATION_AMOUNT, APPLICATION_RATE, APPLICATION_TERMS, MONTHLY_INCOME
    FROM	APPLICANT
    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME;
 INSERT INTO #KRM021_DEDUP (MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME, COUNT(*)
  FROM KRM021
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, CARD_BRAND, CARD_TYPE, ISSUE, ISSUE_NAME, START_DATE, STOP_DATE, STOP_CODE, AB_CODE, M_S, LIMIT, INPUT_TIME;

 INSERT INTO #KRM023_DEDUP (MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME, COUNT(*)
  FROM KRM023
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, ISSUE, ISSUE_NAME, LIMIT, YRMON, KR_CODE, PAYMENT, CASH, PAY_CODE, INPUT_TIME;
 INSERT INTO #STM007_DEDUP (MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME, COUNT(*)
  FROM STM007
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, BANK_CODE, BANK_NAME, QUERY_DATE, ITEM_LIST, INPUT_TIME;
 INSERT INTO #BAM086_DEDUP (MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, INPUT_TIME, CNT)
  SELECT MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CAST(CONTRACT_AMT AS INT), CAST(LOAN_AMT AS INT), CAST(PASS_DUE_AMT AS INT), PAY_CODE_12, CO_LOAN, INPUT_TIME, COUNT(*)
  FROM BAM086
--  WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, DATA_YYY, DATA_MM, BANK_CODE, BANK_NAME, ACCOUNT_CODE, ACCOUNT_CODE2, PURPOSE_CODE, CONTRACT_AMT, LOAN_AMT, PASS_DUE_AMT, PAY_CODE_12, CO_LOAN, INPUT_TIME;
 INSERT INTO #VAM102_DEDUP (MSN, IDN, INQUIRY_DATE, INPUT_TIME, DATA_DATE, MAINCODE, MAINNOTE, SUBCODE, SUBNOTE, NOTE, CNT)
    SELECT MSN, IDN, INQUIRY_DATE, INPUT_TIME, DATA_DATE, MAINCODE, MAINNOTE, SUBCODE, SUBNOTE, NOTE, COUNT(*)
    FROM VAM102
    WHERE MSN= @MSN AND INPUT_TIME = @INPUT_TIME
    GROUP BY MSN, IDN, INQUIRY_DATE, INPUT_TIME, DATA_DATE, MAINCODE, MAINNOTE, SUBCODE, SUBNOTE, NOTE
 INSERT INTO #JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'D', DELINQUENT_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_DELINQUENT = 'Y';
    WHERE  EVER_DELINQUENT = 'Y';
 INSERT INTO #JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'B', BAD_CHECK_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_BAD_CHECK = 'Y';
    WHERE  EVER_BAD_CHECK = 'Y';
 INSERT INTO #JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'R', REJECT_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_REJECT = 'Y';
    WHERE EVER_REJECT = 'Y';
 INSERT INTO #JAS002_T (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN)
    SELECT MSN, INQUIRY_DATE, IDN, 'S', STOP_CARD_DATE
    FROM JAS002
--    WHERE MSN = @MSN AND INPUT_TIME = @INPUT_TIME AND EVER_STOP_CARD = 'Y';
    WHERE  EVER_STOP_CARD = 'Y';
 INSERT INTO #KRM037_DEDUP(MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME)
  SELECT MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME
  FROM KRM037
  WHERE ISSUE != 'TOT'
--    AND MSN = @MSN AND INPUT_TIME = @INPUT_TIME
  GROUP BY MSN, INQUIRY_DATE, IDN, BILL_DATE, ISSUE, ISSUE_NAME, CARD_TYPE, PERM_LIMIT, TEMP_LIMIT, CASH_LIMIT, PAYABLE, CASH_LENT, LAST_PAYA, REVOL_BAL, PAY_STAT, PAY_CODE, REVOL_RATE, PRE_OWED, DEBT_CODE, CLOSE_CODE, CLEAR_DATE, INPUT_TIME;
 UPDATE #KRM021_DEDUP
    SET MSN      = (CASE WHEN MSN =      '' THEN NULL ELSE MSN END),
        INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
        IDN          = (CASE WHEN IDN =          '' THEN NULL ELSE IDN END),
        CARD_BRAND   = (CASE WHEN CARD_BRAND   = '' THEN NULL ELSE CARD_BRAND END),
        CARD_TYPE    = (CASE WHEN CARD_TYPE    = '' THEN NULL ELSE CARD_TYPE  END),
        ISSUE        = (CASE WHEN ISSUE        = '' THEN NULL ELSE ISSUE      END),
        ISSUE_NAME   = (CASE WHEN ISSUE_NAME   = '' THEN NULL ELSE ISSUE_NAME END),
        START_DATE   = (CASE WHEN START_DATE   = '' THEN NULL ELSE START_DATE END),
        STOP_DATE    = (CASE WHEN STOP_DATE    = '' THEN NULL ELSE STOP_DATE  END),
        STOP_CODE    = (CASE WHEN STOP_CODE    = '' THEN NULL ELSE STOP_CODE  END),
        AB_CODE      = (CASE WHEN AB_CODE      = '' THEN NULL ELSE AB_CODE    END),
        M_S          = (CASE WHEN M_S          = '' THEN NULL ELSE M_S        END),
        LIMIT        = (CASE WHEN LIMIT        = '' THEN NULL ELSE LIMIT      END);
 UPDATE #KRM023_DEDUP
   SET MSN      = (CASE WHEN MSN =      '' THEN NULL ELSE MSN END),
       INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN          = (CASE WHEN IDN =          '' THEN NULL ELSE IDN END),
       YRMON        = (CASE WHEN YRMON =        '' THEN NULL ELSE YRMON END),
       ISSUE        = (CASE WHEN ISSUE =        '' THEN NULL ELSE ISSUE END),
       ISSUE_NAME   = (CASE WHEN ISSUE_NAME =   '' THEN NULL ELSE ISSUE_NAME END),
       KR_CODE      = (CASE WHEN KR_CODE =      '' THEN NULL ELSE KR_CODE END),
       LIMIT        = (CASE WHEN LIMIT =        '' THEN NULL ELSE LIMIT END),
       PAYMENT      = (CASE WHEN PAYMENT =      '' THEN NULL ELSE PAYMENT END),
       CASH         = (CASE WHEN CASH =         '' THEN NULL ELSE CASH END),
       PAY_CODE     = (CASE WHEN PAY_CODE =     '' THEN NULL ELSE PAY_CODE END);
 UPDATE #STM007_DEDUP
   SET MSN     = (CASE WHEN MSN      = '' THEN NULL ELSE MSN END),
       INQUIRY_DATE = (CASE WHEN INQUIRY_DATE = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN          = (CASE WHEN IDN          = '' THEN NULL ELSE IDN END),
       BANK_CODE    = (CASE WHEN BANK_CODE    = '' THEN NULL ELSE BANK_CODE  END),
       BANK_NAME    = (CASE WHEN BANK_NAME    = '' THEN NULL ELSE BANK_NAME  END),
       QUERY_DATE   = (CASE WHEN QUERY_DATE   = '' THEN NULL ELSE QUERY_DATE END),
       ITEM_LIST    = (CASE WHEN ITEM_LIST    = '' THEN NULL ELSE ITEM_LIST  END);
 UPDATE #BAM086_DEDUP
   SET MSN      = (CASE WHEN MSN       = '' THEN NULL ELSE MSN END),
       INQUIRY_DATE  = (CASE WHEN INQUIRY_DATE  = '' THEN NULL ELSE INQUIRY_DATE END),
       IDN           = (CASE WHEN IDN           = '' THEN NULL ELSE IDN END),
       DATA_YYY      = (CASE WHEN DATA_YYY      = '' THEN NULL ELSE DATA_YYY      END),
       DATA_MM       = (CASE WHEN DATA_MM       = '' THEN NULL ELSE DATA_MM       END),
       BANK_CODE     = (CASE WHEN BANK_CODE     = '' THEN NULL ELSE BANK_CODE     END),
       BANK_NAME     = (CASE WHEN BANK_NAME     = '' THEN NULL ELSE BANK_NAME     END),
       ACCOUNT_CODE  = (CASE WHEN ACCOUNT_CODE  = '' THEN NULL ELSE ACCOUNT_CODE  END),
       ACCOUNT_CODE2 = (CASE WHEN ACCOUNT_CODE2 = '' THEN NULL ELSE ACCOUNT_CODE2 END),
       PURPOSE_CODE  = (CASE WHEN PURPOSE_CODE  = '' THEN NULL ELSE PURPOSE_CODE  END),
       PAY_CODE_12   = (CASE WHEN PAY_CODE_12   = '' THEN NULL ELSE PAY_CODE_12   END),
       CO_LOAN       = (CASE WHEN CO_LOAN       = '' THEN NULL ELSE CO_LOAN       END);
 UPDATE #KRM037_DEDUP
   SET BILL_DATE  = (CASE WHEN LTRIM(BILL_DATE)  = '' THEN NULL ELSE LTRIM(RTRIM(BILL_DATE)) END),
       ISSUE      = (CASE WHEN LTRIM(ISSUE)      = '' THEN NULL ELSE ISSUE END),
       ISSUE_NAME = (CASE WHEN LTRIM(ISSUE_NAME) = '' THEN NULL ELSE ISSUE_NAME END),
       CARD_TYPE  = (CASE WHEN LTRIM(CARD_TYPE)  = '' THEN NULL ELSE CARD_TYPE END),
       PERM_LIMIT = (CASE WHEN LTRIM(PERM_LIMIT) = '' THEN NULL ELSE PERM_LIMIT END),
       TEMP_LIMIT = (CASE WHEN LTRIM(TEMP_LIMIT) = '' THEN NULL ELSE TEMP_LIMIT END),
       CASH_LIMIT = (CASE WHEN LTRIM(CASH_LIMIT) = '' THEN NULL ELSE CASH_LIMIT END),
       PAYABLE    = (CASE WHEN LTRIM(PAYABLE)    = '' THEN NULL ELSE PAYABLE END),
       CASH_LENT  = (CASE WHEN LTRIM(CASH_LENT)  = '' THEN NULL ELSE CASH_LENT END),
       LAST_PAYA  = (CASE WHEN LTRIM(LAST_PAYA)  = '' THEN NULL ELSE LAST_PAYA END),
       REVOL_BAL  = (CASE WHEN LTRIM(REVOL_BAL)  = '' THEN NULL ELSE REVOL_BAL END),
       PAY_STAT   = (CASE WHEN LTRIM(PAY_STAT)   = '' THEN NULL ELSE PAY_STAT END),
       PAY_CODE   = (CASE WHEN LTRIM(PAY_CODE)   = '' THEN NULL ELSE PAY_CODE END),
       REVOL_RATE = (CASE WHEN LTRIM(REVOL_RATE) = '' THEN NULL ELSE REVOL_RATE END),
       PRE_OWED   = (CASE WHEN LTRIM(PRE_OWED)   = '' THEN NULL ELSE PRE_OWED END),
       DEBT_CODE  = (CASE WHEN LTRIM(DEBT_CODE)  = '' THEN NULL ELSE DEBT_CODE END),
       CLOSE_CODE = (CASE WHEN LTRIM(CLOSE_CODE) = '' THEN NULL ELSE CLOSE_CODE END),
       CLEAR_DATE = (CASE WHEN LTRIM(CLEAR_DATE) = '' THEN NULL ELSE CLEAR_DATE END);
 INSERT INTO #KRM023_TMP (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT)
   SELECT MSN, INQUIRY_DATE, IDN,
          (CASE WHEN LEFT(BILL_DATE,1) = '*' THEN NULL
                WHEN LEN(BILL_DATE) = 4 AND LEFT(BILL_DATE,1) BETWEEN '1' AND '9'
                     THEN '0'+BILL_DATE
                WHEN LEN(BILL_DATE) = 5 AND LEFT(BILL_DATE,1) BETWEEN '0' AND '9'
                     THEN BILL_DATE
                WHEN LEN(BILL_DATE) = 7
                     THEN LEFT(BILL_DATE, 5)
                ELSE NULL END),
          (CASE WHEN LEFT(BILL_DATE,1) = '*' THEN NULL
                WHEN LEN(BILL_DATE) = 4 AND LEFT(BILL_DATE,1) BETWEEN '1' AND '9'
                     THEN CONVERT(INT, LEFT(BILL_DATE, 2)) * 12 + CONVERT(INT, RIGHT(BILL_DATE, 2))
                WHEN LEN(BILL_DATE) = 5 AND LEFT(BILL_DATE,1) BETWEEN '0' AND '9'
                     THEN CONVERT(INT, LEFT(BILL_DATE, 3)) * 12 + CONVERT(INT, RIGHT(BILL_DATE, 2))
                WHEN LEN(BILL_DATE) = 7
                     THEN CONVERT(INT, LEFT(BILL_DATE, 3)) * 12 + CONVERT(INT, SUBSTRING(BILL_DATE, 4, 2))
                ELSE NULL END),
          (CASE WHEN ISSUE = '021' AND CARD_TYPE = 'V' THEN 'CTV'
                WHEN ISSUE = '021' AND CARD_TYPE = 'M' THEN 'CTM'
                WHEN ISSUE = '021' AND CARD_TYPE = 'D' THEN 'CTD'
                WHEN ISSUE = 'A82' AND CARD_TYPE = 'A' THEN 'AEA'
                WHEN ISSUE = 'A82' AND CARD_TYPE = 'E' THEN 'AEE' ELSE ISSUE END),
          ISSUE_NAME, PERM_LIMIT, LAST_PAYA, REVOL_BAL / 1000.0,
          (CASE WHEN CASH_LENT > 0 THEN 'Y' ELSE 'N' END),
          (CASE WHEN DEBT_CODE IN ('A', 'B') THEN 'F'
                WHEN PAY_STAT = 'X' AND PAY_CODE = 'X' THEN 'X'
                WHEN PAY_STAT = '1' AND PAY_CODE = 'N' THEN 'A'
                WHEN PAY_STAT = '1' AND PAY_CODE = '0' THEN 'B'
                WHEN PAY_STAT = '2' AND PAY_CODE = 'N' THEN 'C'
                WHEN PAY_STAT = '2' AND PAY_CODE = '0' THEN 'D'
                WHEN PAY_STAT = '3' AND PAY_CODE BETWEEN '1' AND '7' THEN 'E'
                WHEN PAY_STAT = '4' AND PAY_CODE BETWEEN '1' AND '7' THEN 'F' ELSE NULL END),
          PRE_OWED / 1000.0
   FROM #KRM037_DEDUP;
 UPDATE #KRM023_TMP
   SET PAYMENT_AMT = (CASE RIGHT(PAYMENT,1) WHEN 'L' THEN 2 WHEN 'M' THEN 5 WHEN 'H' THEN 8
                      ELSE 0 END) * POWER(10, ISNULL(LEFT(PAYMENT,2),0)-1) / 1000.0
   WHERE ((PAYMENT_AMT IS NULL) OR (PAYMENT_AMT = 0));
 INSERT INTO #KRM023_TMP1 (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT)
   SELECT MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, SUM(CONVERT(INT, LIMIT)), SUM(PAYMENT_AMT),
           MAX(CASH), MAX(CASE WHEN PAY_CODE = 'X' THEN '0' ELSE PAY_CODE END), SUM(SPREAD_PAYMENT)
   FROM #KRM023_TMP
   GROUP BY MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME;
 UPDATE #KRM023_TMP1
   SET CASH = A.CASH
   FROM #KRM023_TMP1 AS A INNER JOIN #KRM023_TMP1
   ON #KRM023_TMP1.IDN = A.IDN AND
      #KRM023_TMP1.MON_SINCE = A.MON_SINCE + 1 AND
      #KRM023_TMP1.ISSUE = A.ISSUE AND
      #KRM023_TMP1.MSN = A.MSN;
 UPDATE #KRM023_TMP1
    SET INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 INSERT INTO #JAS002_T_DEDUP (MSN, INQUIRY_DATE, IDN,  REASON, DATE_HAPPEN, CNT)
    SELECT MSN, INQUIRY_DATE, IDN, REASON, DATE_HAPPEN, COUNT(*)
    FROM #JAS002_T
    GROUP BY MSN, INQUIRY_DATE, IDN, REASON, DATE_HAPPEN;



 UPDATE #KRM021_DEDUP
  SET START_DATE = (CASE WHEN (LEFT(LTRIM(RTRIM(START_DATE)),1) BETWEEN '1' AND '9') AND (LEN(LTRIM(RTRIM(START_DATE)))<7)
                         THEN '0' + LTRIM(RTRIM(START_DATE)) ELSE LTRIM(RTRIM(START_DATE)) END),
      STOP_DATE =  (CASE WHEN (LEFT(LTRIM(RTRIM(STOP_DATE)),1) BETWEEN '1' AND '9') AND
                         (LEN(LTRIM(RTRIM(STOP_DATE)))<7) AND STOP_DATE != '9991231'
                          THEN '0' + LTRIM(RTRIM(STOP_DATE)) ELSE LTRIM(RTRIM(STOP_DATE)) END);
 UPDATE #KRM021_DEDUP SET STOP_DATE = '9991231'
  WHERE ((STOP_DATE = '') OR (STOP_DATE IS NULL));
 UPDATE #KRM021_DEDUP
   SET START_MON_SINCE = (CASE WHEN LEFT(START_DATE,1) NOT BETWEEN '0' AND '9' THEN NULL
                         ELSE CAST(LEFT(START_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(START_DATE, 5), 2) AS INT) END),
      END_MON_SINCE =   (CASE WHEN LEFT(STOP_DATE, 1) NOT BETWEEN '0' AND '9' THEN NULL
                         ELSE CAST(LEFT(STOP_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(STOP_DATE, 5), 2) AS INT) END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE #JAS002_T_DEDUP
   SET DATE_HAPPEN = (CASE
 		    WHEN LEFT(LTRIM(DATE_HAPPEN),1) NOT IN ('1', '0', '*') THEN '0' + (LTRIM(DATE_HAPPEN))
  		    ELSE DATE_HAPPEN
  		   END);
 UPDATE #JAS002_T_DEDUP
   SET MON_SINCE = (CASE
    		  WHEN LEFT(LTRIM(DATE_HAPPEN),1) = '*' THEN NULL
    		  ELSE CAST(LEFT(LTRIM(DATE_HAPPEN), 3) AS INT) * 12 + CAST(RIGHT(LEFT(RTRIM(DATE_HAPPEN), 5), 2) AS INT)
  		 END),
       INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE #KRM023_DEDUP
 SET YRMON = (CASE
 	      WHEN LEFT(LTRIM(RTRIM(YRMON)),1) NOT IN ('1', '0', '*') THEN '0' + LTRIM(RTRIM(YRMON))
 	      ELSE LTRIM(RTRIM(YRMON))
 	     END);
 UPDATE #KRM023_DEDUP
 SET MON_SINCE = (CASE
 		   WHEN LEFT(YRMON,1) = '*' THEN NULL
 		   ELSE CAST(LEFT(YRMON, 3) AS INT) * 12 + CAST(RIGHT(LEFT(YRMON, 5), 2) AS INT)
 		 END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE #STM007_DEDUP
   SET QUERY_DATE = (CASE
 		   WHEN LEFT(QUERY_DATE,1) NOT IN ('1', '0', '*') THEN '0' + LTRIM(RTRIM(QUERY_DATE))
 		   ELSE QUERY_DATE
 		  END);
 UPDATE #STM007_DEDUP
   SET QUERY_MON_SINCE = (CASE
 			WHEN LEFT(QUERY_DATE,1) = '*' THEN NULL
 			ELSE CAST(LEFT(QUERY_DATE, 3) AS INT) * 12 + CAST(RIGHT(LEFT(QUERY_DATE, 5), 2) AS INT)
 		       END),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT);
 UPDATE #KRM023_DEDUP
  SET PAYMENT =
   (CASE WHEN RIGHT(LEFT(PAYMENT,2),1) IN ('H', 'M', 'L') THEN '0' + (LEFT(PAYMENT,2))
         ELSE PAYMENT END);
 UPDATE #KRM023_DEDUP
  SET PAYMENT_AMT =
   (CASE RIGHT(PAYMENT,1) WHEN 'L' THEN 2 WHEN 'M' THEN 5 WHEN 'H' THEN 8
   ELSE 0 END) * POWER(10, ISNULL(LEFT(PAYMENT,2),0)-1) / 1000.0;
 UPDATE #KRM023_DEDUP
   SET PAYMENT_AMT = CAST(LIMIT AS INT)
   WHERE PAYMENT_AMT > CAST(LIMIT AS INT)
     AND CAST(LIMIT AS INT) > 0
 INSERT INTO #KRM023_DEDUP (MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT, INQUIRY_MON)
   SELECT MSN, INQUIRY_DATE, IDN, YRMON, MON_SINCE, ISSUE, ISSUE_NAME, LIMIT, PAYMENT_AMT, CASH, PAY_CODE, SPREAD_PAYMENT, INQUIRY_MON
   FROM #KRM023_TMP1
   WHERE MON_SINCE > 1140;
 UPDATE  #KRM023_DEDUP
 SET BUCKET_DEF_1K = (CASE WHEN PAY_CODE IN ('D', 'E', 'F') AND (PAYMENT_AMT + SPREAD_PAYMENT)> 1 THEN 1
                       ELSE 0 END),
     BUCKET_EF_1K = (CASE WHEN PAY_CODE IN ('E', 'F') AND (PAYMENT_AMT + SPREAD_PAYMENT) > 1 THEN 1
                      ELSE 0 END),
     BUCKET_F_1K = (CASE WHEN PAY_CODE = 'F' AND (PAYMENT_AMT + SPREAD_PAYMENT) > 1 THEN 1
                     ELSE 0 END);
 DECLARE @I INT
 SET @I=12
 WHILE @I >= 0
 BEGIN
   UPDATE #KRM023_DEDUP
   SET
   BUCKET_DEF_1K =(CASE WHEN #KRM023_DEDUP.PAY_CODE IN ('D', 'E', 'F') AND
                             (#KRM023_DEDUP.PAYMENT_AMT + #KRM023_DEDUP.SPREAD_PAYMENT)> 1
                        THEN A.BUCKET_DEF_1K + 1
                        ELSE 0 END),
   BUCKET_EF_1K =(CASE WHEN  #KRM023_DEDUP.PAY_CODE IN ('E', 'F') AND
                             (#KRM023_DEDUP.PAYMENT_AMT + #KRM023_DEDUP.SPREAD_PAYMENT)> 1
                       THEN A.BUCKET_EF_1K + 1
                       ELSE 0 END),
   BUCKET_F_1K =(CASE WHEN  #KRM023_DEDUP.PAY_CODE = 'F' AND
                            (#KRM023_DEDUP.PAYMENT_AMT + #KRM023_DEDUP.SPREAD_PAYMENT) > 1
                      THEN A.BUCKET_F_1K + 1
                      ELSE 0 END)
   FROM  #KRM023_DEDUP AS A INNER JOIN  #KRM023_DEDUP ON
         A.IDN =  #KRM023_DEDUP.IDN AND
         A.ISSUE =  #KRM023_DEDUP.ISSUE AND
         A.MON_SINCE = ( #KRM023_DEDUP.MON_SINCE - 1)
   WHERE (A.INQUIRY_MON - A.MON_SINCE) = @I
 SET @I = @I - 1
 END;
 UPDATE #BAM086_DEDUP
  SET BANK_CODE2 = LEFT(BANK_CODE,3),
      MON_SINCE = CAST(DATA_YYY AS INT)* 12 + CAST(DATA_MM AS INT),
      INQUIRY_MON = (CAST(LEFT(INQUIRY_DATE,4) AS INT) - 1911) * 12 + CAST(SUBSTRING(INQUIRY_DATE, 5, 2) AS INT),
      CYCLE = LEN(LTRIM(RTRIM(PAY_CODE_12)));
 SET @I=1;
 WHILE @I <= 12
    BEGIN
       INSERT INTO #BAM086_BUCKET (IDN, BANK_CODE, MON_SINCE, BUCKET)
          SELECT IDN, BANK_CODE2, (MON_SINCE - @I + 1),
                 (CASE WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'A' THEN 0.25
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'B' THEN 0.5
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'X' THEN 0
                       ELSE CONVERT(FLOAT, SUBSTRING(RTRIM(PAY_CODE_12), @I, 1)) END)
          FROM #BAM086_DEDUP
          WHERE CYCLE >= @I
       SET @I = @I + 1
    END
/*
-- ALTER TABLE #BAM086_DEDUP ADD MON_SINCE INT

 DECLARE @I INT
 UPDATE #BAM086_DEDUP
  SET BANK_CODE2 = LEFT(BANK_CODE,3),
      MON_SINCE = CAST(DATA_YYY AS INT)* 12 + CAST(DATA_MM AS INT),
      CYCLES = LEN(LTRIM(RTRIM(PAY_CODE_12)));
 SET @I=1;
 WHILE @I <= 12
    BEGIN
       INSERT INTO #BAM086_BUCKET (IDN, BANK_CODE, MON_SINCE, BUCKET)
          SELECT IDN, BANK_CODE2, (MON_SINCE - @I + 1),
                 (CASE WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'A' THEN 0.25
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'B' THEN 0.5
                       WHEN SUBSTRING(RTRIM(PAY_CODE_12), @I, 1) = 'X' THEN 0
                       ELSE CONVERT(FLOAT, SUBSTRING(RTRIM(PAY_CODE_12), @I, 1)) END)
          FROM #BAM086_DEDUP
          WHERE CYCLES >= @I
       SET @I = @I + 1
    END
*/
 /* RISK FILTER PROCESS */
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
    SELECT IDN, 0 FROM #PDACO_V6_1;
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 1
   FROM #KRM023_DEDUP;
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 2
   FROM #KRM021_DEDUP;
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 4
   FROM #BAM086_DEDUP;
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 8
   FROM #JAS002_T;
 INSERT INTO #BASE_TMP(IDN, AVAIL_FLAG)
   SELECT DISTINCT IDN, 16
   FROM #STM007_DEDUP;
 INSERT INTO #BASE (IDN, AVAIL_FLAG)
   SELECT IDN, SUM(AVAIL_FLAG)
   FROM #BASE_TMP
  GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET AVAIL_FLAG = A.AVAIL_FLAG
   FROM #BASE A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 UPDATE #PDACO_V6_1
   SET KRM023_HIT = 1
   WHERE AVAIL_FLAG & 0X01 = 0X01;
 UPDATE #PDACO_V6_1
   SET KRM021_HIT = 1
   WHERE AVAIL_FLAG & 0X02 = 0X02;
 UPDATE #PDACO_V6_1
   SET BAM086_HIT = 1
   WHERE AVAIL_FLAG & 0X04 = 0X04;
 UPDATE #PDACO_V6_1
    SET FS036 = 0,
	FS040 = 0,
	FS044 = 0,
	MS063 = 0,
	MS074 = 0,
	MS093 = 0,
	FS302 = 0,
	FS309 = 0,
	FS334 = 0,
	FS334B_1M = 0,
	FS546_9M = 0,
	FS314B = 0
 WHERE	BAM086_HIT = 1;
 /*INIT KRM023 VARIABLES*/
 UPDATE #PDACO_V6_1
 SET APP_MAX_BUCKET = 0,
     CDEF_FLAG_1M   = 0,
     FS002_3M_1K    = 0,
     FS014_6M	    = 0,
     FS016C_9M	    = 0,
     FS016F_12M	    = 0,
     FS018_12M	    = 0,
     FS021_9M	    = 0,
     FS059_12M_1K   = 0,
     FS059_3M_1K    = 0,
     FS061_6M_1K    = 0,
     FS073B_12M	    = 0,
     FS101_6M	    = 0,
     FS205_3M_1K    = 0,
     MS001_12M_1K   = 0,
     MS094B	    = 0,
     MS118_9M	    = 0,
     MS601	    = 0,
     MS605	    = 0,
     WI001_9M	    = 0,
     WI003_9M	    = 0,
     WI004_9M	    = 0
 WHERE KRM023_HIT = 1;
 /*INIT KRM021 AND KRM023 VARIABLES*/
 UPDATE #PDACO_V6_1
   SET FS205_3M_1K = 0
   FROM #KRM021_DEDUP AS A, #KRM023_DEDUP AS B
   WHERE A.IDN = B.IDN
     AND A.IDN = #PDACO_V6_1.IDN
     AND ((A.ISSUE = B.ISSUE)
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'V') AND (B.ISSUE = 'CTV'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'M') AND (B.ISSUE = 'CTM'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'D') AND (B.ISSUE = 'CTD'))
           OR ((A.ISSUE = 'A82' AND A.CARD_BRAND = 'A') AND (B.ISSUE = 'AEA'))
         );
 /* UPDATE PRESCREEN VARIABLE*/
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
 SELECT IDN, COUNT(*)
   FROM #JAS002_T_DEDUP
   WHERE INQUIRY_MON - MON_SINCE <= 36
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET JAS002_DEFECT = 1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN AND
         A.V1 > 0;
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
   SELECT IDN, MAX(BUCKET_EF_1K)
   FROM #KRM023_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET MAX_BUCKET = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /*----FS044----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
  SELECT IDN, COUNT(*)
  FROM #BAM086_DEDUP
  WHERE PASS_DUE_AMT > 0
  GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS044 = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN, MAX(BUCKET)
     FROM #BAM086_BUCKET
     GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS334 = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN, SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X')
                     THEN 1 ELSE 0 END)
   FROM #BAM086_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS302 = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /*----LOAN MAX BUCKET----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN, COUNT(*)
   FROM #BAM086_DEDUP
   WHERE ISNULL(LEFT(PAY_CODE_12, 1),'0') NOT IN ('0', 'X')
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS334B_1M = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /*----CASH CARD UTILIZATION----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN, COUNT(*)
   FROM #BAM086_DEDUP
   WHERE ACCOUNT_CODE = 'Y'
     AND (ISNULL(LOAN_AMT,0)+ ISNULL(PASS_DUE_AMT,0))/ CAST(CONTRACT_AMT AS FLOAT) >= 0.95
     AND CONTRACT_AMT > 0
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET CASH_UTILIZATION = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /*----CREDIT CARD FORCE STOP ----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
    SELECT IDN, COUNT(*)
    FROM #KRM021_DEDUP
    WHERE STOP_CODE = '3' GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET CARD_FORCE_STOP = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /*----Number of credit lines with EF_1K Delinquent in past 12 months ----*/
 UPDATE #PDACO_V6_1
    SET FS059_12M_1K = (SELECT COUNT(DISTINCT ISSUE)
                     FROM #KRM023_DEDUP AS A
                     WHERE BUCKET_EF_1K > 0
                       AND IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM #KRM023_DEDUP AS A
               WHERE BUCKET_EF_1K > 0
                 AND IDN = #PDACO_V6_1.IDN);
 /* FS059_3M_1K   */
 UPDATE #PDACO_V6_1
    SET FS059_3M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN);
 /*----MS601 CREDIT CARD REVOLVING BALANCE ----*/
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
			 WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0)>0 THEN ISNULL(SPREAD_PAYMENT,0)
			 ELSE 0 END)
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE 
                  WHERE IDN = A.IDN
                  AND  ISSUE = A.ISSUE
                  AND  MON = A.MON_SINCE)
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET CARD_REV_BAL = A.V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /* MS605          */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
      AND CAST(LIMIT AS FLOAT) > 0
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, AVG(CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE
                  WHERE IDN = A.IDN
                    AND  ISSUE = A.ISSUE
                    AND  MON = A.MON_SINCE)
    GROUP BY IDN; 
 UPDATE #PDACO_V6_1
 SET MS605 = (SELECT V1
              FROM #TMP
              WHERE IDN = #PDACO_V6_1.IDN)
 WHERE IDN IN (SELECT IDN FROM #TMP);
 /*----MS063 UNSECURED LOAN BALANCE ----*/
 UPDATE #PDACO_V6_1
       SET MS063 = 
           (SELECT SUM(CAST(ISNULL(LOAN_AMT, 0) AS INT) + CAST(ISNULL(PASS_DUE_AMT, 0) AS INT))
            FROM #BAM086_DEDUP S
            WHERE ((ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE = 'N'))
              AND #PDACO_V6_1.IDN = S.IDN
            GROUP BY S.IDN)
       WHERE EXISTS (SELECT *
                     FROM #BAM086_DEDUP S
                     WHERE ((ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE = 'N'))
                       AND #PDACO_V6_1.IDN = S.IDN);
 /* MS606          */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM((CASE WHEN PAY_CODE IN ('C','D','E','F') THEN ISNULL(PAYMENT_AMT,0) ELSE 0 END)
		    + ISNULL(SPREAD_PAYMENT,0))
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE 
                  WHERE IDN = A.IDN
                    AND ISSUE = A.ISSUE
                    AND MON = A.MON_SINCE)
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET MS606 = (SELECT V1
                 FROM #TMP
                 WHERE IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP
                 WHERE IDN = #PDACO_V6_1.IDN)
 UPDATE #PDACO_V6_1
    SET MS606 = isnull(MS606,0)+isnull(MS063,0);
 /*---- MS105 CASH CARD REVOLVING BALANCE ----*/
 UPDATE #PDACO_V6_1
       SET MS105 = 
           (SELECT SUM(CAST(ISNULL(LOAN_AMT, 0) AS INT) + CAST(ISNULL(PASS_DUE_AMT, 0) AS INT))
            FROM #BAM086_DEDUP S
            WHERE ACCOUNT_CODE = 'Y'
              AND #PDACO_V6_1.IDN = S.IDN
            GROUP BY S.IDN)
       WHERE EXISTS (SELECT *
                     FROM #BAM086_DEDUP S
                     WHERE ACCOUNT_CODE = 'Y'
                       AND #PDACO_V6_1.IDN = S.IDN);
 /*-- REVOLVING_AMT (MS602)*/
 UPDATE #PDACO_V6_1
   SET REVOLVING_AMT = CARD_REV_BAL + MS105;
 /*----IND001----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1, V2)
   SELECT IDN, MIN(INQUIRY_MON)-1 - MIN(MON_SINCE), MAX(INQUIRY_MON) - MAX(MON_SINCE)
   FROM #KRM023_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET IND001 = (CASE WHEN A.V1 < 6 OR A.V2 >= 3 THEN 1 ELSE 0 END)
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 INSERT INTO #TMP1 (IDN, V1)
   SELECT IDN, (CASE WHEN (MIN(INQUIRY_MON)-1 - MIN(START_MON_SINCE)) <= 6 THEN 1 ELSE 0 END)
   FROM #KRM021_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET IND001 = (CASE WHEN (IND001 + A.V1) > 0 THEN 1 ELSE 0 END)
   FROM #TMP1 AS A
   WHERE A.IDN = #PDACO_V6_1.IDN;
 /* CDEF_FLAG_1M   */
 UPDATE #PDACO_V6_1
    SET	CDEF_FLAG_1M = 1
 WHERE EXISTS (SELECT *
               FROM  #KRM023_DEDUP AS A
               WHERE INQUIRY_MON-1 - MON_SINCE <= 1 
                 AND (PAY_CODE IN ('C','D','E','F') OR
		      (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                 AND A.IDN = #PDACO_V6_1.IDN);
 /* DEBT_FLAG   */
 UPDATE #PDACO_V6_1
    SET	DEBT_FLAG = 1
 WHERE EXISTS (SELECT *
               FROM  #KRM037_DEDUP AS A
               WHERE DEBT_CODE IS NOT NULL
                 AND A.IDN = #PDACO_V6_1.IDN);
 /* NOTE_FLAG   */
 UPDATE #PDACO_V6_1
    SET	NOTE_FLAG = 1
 WHERE EXISTS (SELECT *
               FROM  VAM102 AS A
               WHERE NOTE IS NOT NULL
                 AND A.IDN = #PDACO_V6_1.IDN);

GO
/* END_OF_CREATE_PROCEDURE_PREPARE_JCIC_DATA */


-----------------------------------------------------------------------------------------------------------------------
-- P0, Screen #1-5
 UPDATE #PDACO_V6_1
   SET FS302_FG = (CASE WHEN FS302 >= 1 THEN 1 ELSE 0 END);
GO   		  
-----------------------------------------------------------------------------------------------------------------------
-- P1, Data insufficient
 /*---START MAKING FS031---*/
 UPDATE #PDACO_V6_1
   SET FS031 = (SELECT COUNT(*)
                FROM #STM007_DEDUP A
                WHERE ITEM_LIST IS NOT NULL
                  AND ITEM_LIST <> ''
                  AND A.IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM #STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = #PDACO_V6_1.IDN);
 UPDATE #PDACO_V6_1
    SET GRAY2_FLAG = BAM086_HIT+KRM021_HIT;
GO
-----------------------------------------------------------------------------------------------------------------------
-- P2, w/o guarantor, CC limit (MS605) <=50K
/* FS016C_9M      */
 UPDATE #PDACO_V6_1
   SET FS016C_9M = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE */
                      AND CASH = 'Y'
                      AND (PAY_CODE IN ('C','D','E','F') OR
                         (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                    AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                  FROM #KRM023_DEDUP AS A
                  WHERE INQUIRY_MON-1 - MON_SINCE <= 9 
                    AND CASH = 'Y'
                    AND (PAY_CODE IN ('C','D','E','F') OR
                         (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                    AND A.IDN = #PDACO_V6_1.IDN);
 /*----MONTHLY DEBT ----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM #BAM086_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN; 
 /* MS094B          */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
          ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET MS094B = (SELECT V1
                  FROM #TMP
                  WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 UPDATE #PDACO_V6_1
   SET MS093  = ISNULL(MS093, 0),
       MS094B = ISNULL(MS094B, 0),
       MS105  = ISNULL(MS105, 0);                       
 /* WI001_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, COUNT(DISTINCT ISSUE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI001_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);
 UPDATE #PDACO_V6_1
   SET FS016C_9M_T1 = (CASE WHEN FS016C_9M = 0 THEN 0 ELSE 1 END);
GO
-----------------------------------------------------------------------------------------------------------------------
-- P3, w/o guarantor, 50K < CC limit (MS605) <= 100K, not revolve in last month (CDEF_FLAG_1M = 0)
 UPDATE #PDACO_V6_1
    SET FS036 = A.FS036,
	FS040 = A.FS040
 FROM (SELECT IDN, 
	SUM(CASE WHEN ((ACCOUNT_CODE2 IN ('S', 'W', 'M')) OR 
			       (ACCOUNT_CODE = 'K'))
		 THEN 1
		 ELSE 0 END) AS FS036,
	SUM(CASE WHEN (((ACCOUNT_CODE2 IS NULL) OR 
				    (ACCOUNT_CODE2 = '') OR 
				    (ACCOUNT_CODE2 = 'N')) AND 
				     ACCOUNT_CODE != 'K') 
		 THEN 1
		 ELSE 0 END) AS FS040
       FROM	#BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = #PDACO_V6_1.IDN;
 /* MS118_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      MIN((CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
               ELSE 0 END) / CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=9  /* NO   30-DAY RULE */
      AND CAST(LIMIT AS FLOAT) > 0
      AND ((PAY_CODE IN ('C','D','E','F') AND ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0) > 1)
            OR (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0)>1))   /* TO ELIMINATE THOSE SMALL REVOLING LINES */		
    GROUP BY IDN;

 UPDATE #PDACO_V6_1
    SET MS118_9M = (
     SELECT V1
     FROM #TMP
     WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM #TMP);
 /* FS014_6M       */
 UPDATE #PDACO_V6_1
 SET FS014_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM #KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                 FROM #KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = #PDACO_V6_1.IDN);
 /* FS021_9M       */
 UPDATE #PDACO_V6_1
   SET FS021_9M = (SELECT COUNT(DISTINCT MON_SINCE)
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND (PAY_CODE IN ('C','D','E','F') OR
                          (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                   AND IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND (PAY_CODE IN ('C','D','E','F') OR
                          (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                   AND IDN = #PDACO_V6_1.IDN);
 UPDATE #PDACO_V6_1
   SET SECURE_FLAG = (CASE WHEN FS036 > 0 THEN 1 ELSE 0 END),
       UNSECURE_FLAG = (CASE WHEN FS040 > 0 THEN 1 ELSE 0 END);
 UPDATE #PDACO_V6_1
   SET LU_FLAG = (CASE WHEN (MS118_9M <= 0.2 AND FS014_6M >= 2) OR
                            (SECURE_FLAG = 1 AND UNSECURE_FLAG = 0) THEN 1 ELSE 0 END);
GO
-----------------------------------------------------------------------------------------------------------------------
-- P4, w/o guarantor, 50K < CC limit (MS605) <= 100K, revolve in last month (CDEF_FLAG_1M = 1)
-- CREDIT CARD AND UNSECURED REVOLVING_AMT (MS604)
 UPDATE #PDACO_V6_1
   SET MS604 = CARD_REV_BAL + MS063;
/* RS017 */ 
 UPDATE #PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM #KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM #KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = #PDACO_V6_1.IDN);
 /* MS001_12M_1K   */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0))
    FROM #KRM023_DEDUP
    WHERE BUCKET_EF_1K > 0
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET MS001_12M_1K = (SELECT MAX(V1)
                        FROM #TMP
                        WHERE IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                        FROM #TMP
                        WHERE IDN = #PDACO_V6_1.IDN);
 /* FS018_12M    */
 UPDATE #PDACO_V6_1
    SET FS018_12M = (SELECT COUNT(DISTINCT MON_SINCE)
                      FROM #KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                      FROM #KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = #PDACO_V6_1.IDN);
 /*----FS309 °Ê¥Îµ§¼Æ----*/
 UPDATE #PDACO_V6_1
    SET FS309 = (SELECT COUNT(*)
                 FROM #BAM086_DEDUP AS A
                 WHERE ACCOUNT_CODE = 'Y' AND
                       (CAST(ISNULL(LOAN_AMT,0) AS INT) + CAST(ISNULL(PASS_DUE_AMT,0) AS INT)) > 0
                   AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                 FROM #BAM086_DEDUP AS A
                 WHERE ACCOUNT_CODE = 'Y' AND
                       (CAST(ISNULL(LOAN_AMT,0) AS INT) + CAST(ISNULL(PASS_DUE_AMT,0) AS INT)) > 0
                   AND A.IDN = #PDACO_V6_1.IDN);
 /*---START MAKING FS031---*/
 UPDATE #PDACO_V6_1
   SET FS031 = (SELECT COUNT(*)
                FROM #STM007_DEDUP A
                WHERE ITEM_LIST IS NOT NULL
                  AND ITEM_LIST <> ''
                  AND A.IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM #STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = #PDACO_V6_1.IDN);
/* FS061_6M_1K    */
 UPDATE #PDACO_V6_1
 SET FS061_6M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN);
 /* FS101_6M       */
 UPDATE #PDACO_V6_1
   SET FS101_6M = (SELECT COUNT(DISTINCT ISSUE)
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE */
                     AND IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                     AND IDN = #PDACO_V6_1.IDN);
 /*----MONTHLY DEBT ----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM #BAM086_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN; 
 /* MS094B          */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
          ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET MS094B = (SELECT V1
                  FROM #TMP
                  WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 UPDATE #PDACO_V6_1
   SET MS093  = ISNULL(MS093, 0),
       MS094B = ISNULL(MS094B, 0),
       MS105  = ISNULL(MS105, 0);
 /* WI004_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI004_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);
 UPDATE #PDACO_V6_1
    SET FS546_9M = A.FS546_9M
    FROM (SELECT IDN, 
   	  SUM(CASE WHEN PURPOSE_CODE = '4' AND
   		      LEN(LTRIM(RTRIM(PAY_CODE_12))) + INQUIRY_MON - 1 -
   	  	      CAST(ISNULL(DATA_YYY, 0) AS INT)*12-CAST(ISNULL(DATA_MM, 0) AS INT) <= 9
   		 THEN 1
   		 ELSE 0 END) AS FS546_9M
          FROM	#BAM086_DEDUP
          GROUP BY IDN) AS A
    WHERE  A.IDN = #PDACO_V6_1.IDN;	
 UPDATE #PDACO_V6_1
   SET FS018_12M_Z = (CASE WHEN FS018_12M = 0 THEN 1 ELSE 0 END),
       FS309_Z = (CASE WHEN FS309 = 0 THEN 1 ELSE 0 END),
       MS604_R = POWER((CASE WHEN MS604 < 0 THEN NULL ELSE MS604 END), 0.5),
       RS017_R = POWER((CASE WHEN RS017 < 0 THEN NULL ELSE RS017 END), 0.5),
       MS001_12M_1K_Q = MS001_12M_1K * MS001_12M_1K,
       INT053_6 = FS061_6M_1K / FS101_6M,
       FS546_9M_TRAN = ISNULL(FS546_9M, 0);
 UPDATE #PDACO_V6_1
   SET FS3036_T5 = (CASE WHEN BAM086_HIT = 1 AND (FS018_12M_Z = 0 OR FS309_Z = 0) THEN 1
                         WHEN BAM086_HIT = 0 AND FS018_12M_Z = 0 THEN 1 
                         ELSE 0 END),
       RS017_R_TRAN = (CASE WHEN RS017_R > 5 THEN 5
                            ELSE RS017_R END),
       FS031_TRAN4 = (CASE WHEN FS031 IS NULL THEN 0
                           WHEN FS031 > 10 THEN 10
                           ELSE FS031 END),
       INT053_6_Q = INT053_6 * INT053_6;
GO   		  
-----------------------------------------------------------------------------------------------------------------------
-- P5, w/o guarantor, 100K < CC limit (MS605) <= 100K
 CREATE PROCEDURE PDACO61_P5
  AS
 /* FS016F_12M  */
 UPDATE #PDACO_V6_1
 SET FS016F_12M = (SELECT COUNT(*)
                   FROM #KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
               FROM #KRM023_DEDUP AS A
               WHERE CASH = 'Y'
                 AND A.IDN = #PDACO_V6_1.IDN);
 UPDATE #PDACO_V6_1
   SET FS031_1M = (SELECT SUM(CASE WHEN DATEDIFF(DAY,
				CAST(RTRIM(CAST(CAST(LEFT(QUERY_DATE,3) AS INT)+1911 AS CHAR)) + SUBSTRING(QUERY_DATE,4,4) AS DATETIME),
				CAST(INQUIRY_DATE AS DATETIME)) < = 31
				THEN 1
				ELSE 0
			      END)
                   FROM #STM007_DEDUP A
                   WHERE ITEM_LIST IS NOT NULL
                     AND ITEM_LIST <> ''
                     AND A.IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM #STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = #PDACO_V6_1.IDN);
/* RS017 */ 
 UPDATE #PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM #KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM #KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = #PDACO_V6_1.IDN);
 -- MS074
 UPDATE #PDACO_V6_1
    SET MS074 = ISNULL(A.MS074, 0)
 FROM (SELECT IDN, 
	SUM(CASE WHEN PURPOSE_CODE = '4'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS074
       FROM	#BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = #PDACO_V6_1.IDN;
 /* FS073B_12M     */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, BUCKET)
    SELECT IDN, ISSUE, MAX(BUCKET_EF_1K) 
    FROM #KRM023_DEDUP
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM(BUCKET)
    FROM #OPEN_LINE
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET FS073B_12M = (
                SELECT V1
                FROM #TMP
                WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 /* ---PREPARE INTERMEDIATE TABLES FOR KRM023 AND KRM021 VARIABLES --- */
 DELETE FROM #OPEN_CARD;
 DELETE FROM #OPEN_LINE;
 DELETE FROM #LATEST_STMT_MON;
 DELETE FROM #LATEST_LINE;
 DECLARE @I INT
   SET @I = 0
   WHILE @I <= 13
    BEGIN
     INSERT INTO #OPEN_CARD (IDN, ISSUE, MON, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'A' AND ISSUE = 'A82' THEN 'AEA'
                   ELSE ISSUE END),
             (INQUIRY_MON-1 - @I), INQUIRY_MON-1
      FROM #KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON-1 - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON-1 - @I))
        AND ISSUE != '021'
     SET @I = @I + 1
    END;
   INSERT INTO #OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
    SELECT IDN, ISSUE, MON, COUNT(*), NOW
    FROM #OPEN_CARD
    GROUP BY IDN, ISSUE, MON, NOW;
   SET @I = 0
   WHILE @I <= 13
    BEGIN
     INSERT INTO #OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'M' THEN 'CTM'
                   WHEN CARD_BRAND = 'V' THEN 'CTV'
                   WHEN CARD_BRAND = 'D' THEN 'CTD' END),
             (INQUIRY_MON-1 - @I), 1, INQUIRY_MON-1
      FROM #KRM021_DEDUP
      WHERE (END_MON_SINCE > (INQUIRY_MON-1 - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON-1 - @I))
        AND ISSUE = '021'
     SET @I = @I + 1
    END;
   UPDATE #OPEN_LINE
    SET BUCKET = 1;
 /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
   UPDATE #OPEN_LINE
    SET BUCKET = 100  /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
    WHERE MON = (NOW - 14);
   SET @I = 13;
   WHILE @I > 0
    BEGIN
     UPDATE #OPEN_LINE
      SET BUCKET = A.BUCKET + 1
      FROM #OPEN_LINE AS A INNER JOIN #OPEN_LINE
        ON A.IDN = #OPEN_LINE.IDN
       AND A.ISSUE = #OPEN_LINE.ISSUE
       AND A.MON = (#OPEN_LINE.MON - 1)
      WHERE (A.NOW - A.MON) = @I
     SET @I = @I - 1
    END;
   INSERT INTO #LATEST_STMT_MON (IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON)
    FROM #OPEN_LINE
    WHERE MON <= NOW
    GROUP BY IDN, ISSUE;
   INSERT INTO #LATEST_LINE (IDN, ISSUE, MON, MOB)
    SELECT A.IDN, A.ISSUE, A.MON, A.BUCKET
    FROM #OPEN_LINE AS A INNER JOIN #LATEST_STMT_MON AS B
      ON A.IDN = B.IDN
     AND A.ISSUE = B.ISSUE
     AND A.MON = B.MON;
 /* FS205_3M_1K_Q_TRAN	 OF DELINQUNT LINES OPENED LESS THAN A YEAR */
 /*----FS205_1K----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, MON, V1)
   SELECT IDN, 3, COUNT(*)
   FROM #KRM023_DEDUP AS A
   WHERE ISSUE IN (SELECT ISSUE FROM #LATEST_LINE
                   WHERE MOB <= 13 AND IDN = A.IDN)
     AND (PAY_CODE IN ('C', 'D', 'E','F') OR
	  (CASH='Y' AND ISNULL(SPREAD_PAYMENT,0)>0))
     AND ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0) > 1
     AND (INQUIRY_MON-1 - MON_SINCE) <= 3
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS205_3M_1K = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN
     AND A.MON = 3;
 /*----MONTHLY DEBT ----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, V1)
   SELECT IDN,
          SUM(CASE 
             WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 150 / 1000.0
             WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 100 / 1000.0          
             WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 127 / 1000.0
             WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 72 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10.0 * 177 / 1000.0
             WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10.0 * 238 / 1000.0
             WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10.0 * 17 / 1000.0
             WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10.0 * 213 / 1000.0
           END)
   FROM #BAM086_DEDUP
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET MS093 = ISNULL(V1, 0)
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN; 
 /* MS094B          */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
          ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET MS094B = (SELECT V1
                  FROM #TMP
                  WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 /*----CASH CARD REVOLVING BALANCE ----*/
 UPDATE #PDACO_V6_1
   SET MS093  = ISNULL(MS093, 0),
       MS094B = ISNULL(MS094B, 0),
       MS105  = ISNULL(MS105, 0);
 /* WI003_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CASE WHEN CAST(LIMIT AS FLOAT) > 200 THEN 1.0 ELSE 0.0 END)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI003_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);
 UPDATE #PDACO_V6_1
   SET RS017_R = POWER((CASE WHEN RS017 < 0 THEN NULL ELSE RS017 END), 0.5),
       MS074_T2 = REQUEST_AMT/1000.0 + ISNULL(MS074, 0),
       FS205_3M_1K_Q = FS205_3M_1K * FS205_3M_1K,
       WI003_9M_T = (CASE WHEN WI003_9M = 0 THEN 0.1 ELSE WI003_9M END),
       FS546_9M_TRAN = ISNULL(FS546_9M, 0),
       FS031_1M_Q = FS031_1M * FS031_1M,
       FS073B_12M_R = POWER((CASE WHEN FS073B_12M < 0 THEN NULL ELSE FS073B_12M END), 0.5);
 UPDATE #PDACO_V6_1
   SET RS017_R_TRAN2 = (CASE WHEN RS017_R > 8 THEN 8
                         ELSE RS017_R END),
       MS074_T3 = (CASE WHEN MS074_T2 > 2250 THEN 2250
                           ELSE MS074_T2 END),
       FS205_3M_1K_Q_TRAN2 = ISNULL(FS205_3M_1K_Q, 0),
       FS031_1M_Q_TRAN2 = (CASE WHEN FS031_1M_Q IS NULL THEN 0
                                WHEN FS031_1M_Q > 100 THEN 100
                                ELSE FS031_1M_Q END);
GO

/* CREATE_PROCEDURE_GENERATE_PDACO_SCORE */
 CREATE PROCEDURE GENERATE_PDACO6_1_SCORE
  AS
 /* CREATE TEMPORTARY INTERMEDIATE TABLES */
 UPDATE	#PDACO_V6_1
    SET	REQUEST_AMT = (
	SELECT	MAX(APPLICATION_AMOUNT)
	FROM	APPLICANT
	WHERE	MSN = #PDACO_V6_1.MSN
	AND	INPUT_TIME = #PDACO_V6_1.INPUT_TIME
	GROUP BY MSN),
	APR = (
	SELECT	MAX(APPLICATION_RATE)
	FROM	APPLICANT
	WHERE	MSN = #PDACO_V6_1.MSN
	AND	INPUT_TIME = #PDACO_V6_1.INPUT_TIME
	GROUP BY MSN),
	TOTAL_TERM = (
	SELECT	MAX(APPLICATION_TERMS)
	FROM	APPLICANT
	WHERE	MSN = #PDACO_V6_1.MSN
	AND	INPUT_TIME = #PDACO_V6_1.INPUT_TIME
	GROUP BY MSN)

 /*INIT VARIABLES*/
 /*INIT BAM086 VARIABLES*/
 UPDATE #PDACO_V6_1
    SET FS036 = 0,
	FS040 = 0,
	FS044 = 0,
	MS063 = 0,
	MS074 = 0,
	MS093 = 0,
	MS105 = 0,
	FS302 = 0,
	FS309 = 0,
	FS334 = 0,
	FS334B_1M = 0,
	FS546_9M = 0,
	FS314B = 0
 WHERE	IDN IN (SELECT	IDN
		FROM	#BAM086_DEDUP)
 /*INIT KRM023 VARIABLES*/
 UPDATE #PDACO_V6_1
 SET APP_MAX_BUCKET = 0,
     CDEF_FLAG_1M   = 0,
     FS002_3M_1K    = 0,
     FS014_6M	    = 0,
     FS016C_9M	    = 0,
     FS016F_12M	    = 0,
     FS018_12M	    = 0,
     FS021_9M	    = 0,
     FS059_12M_1K   = 0,
     FS059_3M_1K    = 0,
     FS061_6M_1K    = 0,
     FS073B_12M	    = 0,
     FS101_6M	    = 0,
     FS205_3M_1K    = 0,
     MS001_12M_1K   = 0,
     MS094B	    = 0,
     MS118_9M	    = 0,
     MS601	    = 0,
     MS605	    = 0,
     WI001_9M	    = 0,
     WI003_9M	    = 0,
     WI004_9M	    = 0
 FROM #KRM023_DEDUP AS A
 WHERE A.IDN = #PDACO_V6_1.IDN;
 /*INIT KRM021 AND KRM023 VARIABLES*/
 UPDATE #PDACO_V6_1
   SET FS205_3M_1K = 0
   FROM #KRM021_DEDUP AS A, #KRM023_DEDUP AS B
   WHERE A.IDN = B.IDN
     AND A.IDN = #PDACO_V6_1.IDN
     AND ((A.ISSUE = B.ISSUE)
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'V') AND (B.ISSUE = 'CTV'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'M') AND (B.ISSUE = 'CTM'))
           OR ((A.ISSUE = '021' AND A.CARD_BRAND = 'D') AND (B.ISSUE = 'CTD'))
           OR ((A.ISSUE = 'A82' AND A.CARD_BRAND = 'A') AND (B.ISSUE = 'AEA'))
         );
 /*---START MAKING FS031---*/
 UPDATE #PDACO_V6_1
   SET FS031 = (SELECT COUNT(*)
                FROM #STM007_DEDUP A
                WHERE ITEM_LIST IS NOT NULL
                  AND ITEM_LIST <> ''
                  AND A.IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM #STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = #PDACO_V6_1.IDN);
 UPDATE #PDACO_V6_1
   SET FS031_1M = (SELECT SUM(CASE WHEN DATEDIFF(DAY,
				CAST(RTRIM(CAST(CAST(LEFT(QUERY_DATE,3) AS INT)+1911 AS CHAR)) + SUBSTRING(QUERY_DATE,4,4) AS DATETIME),
				CAST(INQUIRY_DATE AS DATETIME)) < = 31
				THEN 1
				ELSE 0
			      END)
                   FROM #STM007_DEDUP A
                   WHERE ITEM_LIST IS NOT NULL
                     AND ITEM_LIST <> ''
                     AND A.IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                 FROM #STM007_DEDUP A
                 WHERE ITEM_LIST IS NOT NULL
                   AND ITEM_LIST <> ''
                   AND A.IDN = #PDACO_V6_1.IDN);
/*BEGINNING KRM021-RELATED *****************************************/
/* RS017 */ 
 UPDATE #PDACO_V6_1
    SET RS017 = (SELECT MAX(INQUIRY_MON - START_MON_SINCE)
              FROM #KRM021_DEDUP A
              WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
               FROM #KRM021_DEDUP A
               WHERE (INQUIRY_MON - START_MON_SINCE) > 0
                 AND A.IDN = #PDACO_V6_1.IDN);

/*BEGINNING BAM086-RELATED *****************************************/
 UPDATE #PDACO_V6_1
    SET FS036 = A.FS036,
	FS040 = A.FS040,
	FS044 = A.FS044,
	MS063 = A.MS063,
	MS074 = A.MS074,
	MS093 = A.MS093,
	MS105 = A.MS105,
	FS302 = A.FS302,
	FS309 = A.FS309,
	FS334B_1M = A.FS334B_1M,
	FS546_9M = A.FS546_9M,
	FS314B = A.FS314B
 FROM (SELECT IDN, 
	SUM(CASE WHEN ((ACCOUNT_CODE2 IN ('S', 'W', 'M')) OR 
			       (ACCOUNT_CODE = 'K'))
		 THEN 1
		 ELSE 0 END) AS FS036,
	SUM(CASE WHEN (((ACCOUNT_CODE2 IS NULL) OR 
				    (ACCOUNT_CODE2 = '') OR 
				    (ACCOUNT_CODE2 = 'N')) AND 
				     ACCOUNT_CODE != 'K') 
		 THEN 1
		 ELSE 0 END) AS FS040,
	SUM(CASE WHEN PASS_DUE_AMT > 0 
		 THEN 1
		 ELSE 0 END) AS FS044,
	SUM(CASE WHEN ((ACCOUNT_CODE2 = '') OR
				   (ACCOUNT_CODE2 IS NULL) OR 
				   (ACCOUNT_CODE = 'N'))
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS063,
	SUM(CASE WHEN PURPOSE_CODE = '4'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS074,
        SUM(CASE   /* MONTHLY PAYMENT IN K PER 10K LOAN  */
			 WHEN ACCOUNT_CODE = 'C' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10* 150 / 1000
			 WHEN ACCOUNT_CODE = 'C' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 100 / 1000
			 WHEN ACCOUNT_CODE = 'E' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 150 / 1000
			 WHEN ACCOUNT_CODE = 'E' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 100 / 1000          
			 WHEN ACCOUNT_CODE = 'H' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 238 / 1000
			 WHEN ACCOUNT_CODE = 'H' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 177 / 1000
			 WHEN ACCOUNT_CODE = 'I' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 127 / 1000
			 WHEN ACCOUNT_CODE = 'I' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 72 / 1000
			 WHEN ACCOUNT_CODE = 'O' AND ((ACCOUNT_CODE2 IS NULL) OR (ACCOUNT_CODE2 = '') OR (ACCOUNT_CODE2 = 'N')) THEN (CONTRACT_AMT) / 10 * 177 / 1000
			 WHEN ACCOUNT_CODE = 'O' AND ACCOUNT_CODE2 IN ('S', 'W', 'M') THEN (CONTRACT_AMT) / 10 * 238 / 1000
			 WHEN ACCOUNT_CODE = 'K' THEN (CONTRACT_AMT) / 10 * 17 / 1000
			 WHEN ACCOUNT_CODE = 'Z' THEN (CONTRACT_AMT) / 10 * 213 / 1000
			 ELSE 0 END) AS MS093,
	SUM(CASE WHEN ACCOUNT_CODE='Y'
		 THEN LOAN_AMT + PASS_DUE_AMT
		 ELSE 0 END) AS MS105,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X') 
		 THEN 1
		 ELSE 0 END) AS FS302,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND
		         (ISNULL(LOAN_AMT,0) + ISNULL(PASS_DUE_AMT,0)) > 0
		 THEN 1
		 ELSE 0 END) AS FS309,
	SUM(CASE WHEN ISNULL(LEFT(PAY_CODE_12,1), '0') NOT IN ('0', 'X')
		 THEN 1
		 ELSE 0 END) AS FS334B_1M,
	SUM(CASE WHEN PURPOSE_CODE = '4' AND
		      LEN(LTRIM(RTRIM(PAY_CODE_12))) + INQUIRY_MON - 1 -
	  	      CAST(ISNULL(DATA_YYY, 0) AS INT)*12-CAST(ISNULL(DATA_MM, 0) AS INT) <= 9
		 THEN 1
		 ELSE 0 END) AS FS546_9M,
	SUM(CASE WHEN ACCOUNT_CODE = 'Y' AND
	            (CAST(ISNULL(LOAN_AMT,0) + ISNULL(PASS_DUE_AMT,0) AS DECIMAL) / 
                    (CASE WHEN ISNULL(CONTRACT_AMT,0) = 0 THEN NULL
					   ELSE CONTRACT_AMT END)) >= 0.95
		 THEN 1
		 ELSE 0 END) AS FS314B
       FROM	#BAM086_DEDUP
       GROUP BY IDN) AS A
  WHERE  A.IDN = #PDACO_V6_1.IDN	

 UPDATE #PDACO_V6_1
   SET MS093  = ISNULL(MS093, 0),
       MS094B = ISNULL(MS094B, 0),
       MS105  = ISNULL(MS105, 0);
	
 /* APP_MAX_BUCKET */
 UPDATE #PDACO_V6_1
 SET	APP_MAX_BUCKET = (
 	SELECT MAX(BUCKET_EF_1K)
 	FROM	#KRM023_DEDUP
 	WHERE	IDN = #PDACO_V6_1.IDN)
 WHERE	EXISTS (
 	SELECT *
 	FROM	#KRM023_DEDUP
 	WHERE	IDN = #PDACO_V6_1.IDN);

 /* CDEF_FLAG_1M   */
 UPDATE #PDACO_V6_1
    SET	CDEF_FLAG_1M = 1
 WHERE EXISTS (SELECT *
               FROM  #KRM023_DEDUP AS A
               WHERE INQUIRY_MON-1 - MON_SINCE <= 1 
                 AND (PAY_CODE IN ('C','D','E','F') OR
		      (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                 AND A.IDN = #PDACO_V6_1.IDN);


 /* FS002_3M_1K    */
 UPDATE #PDACO_V6_1
 SET FS002_3M_1K = (SELECT COUNT(DISTINCT MON_SINCE)
                    FROM #KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE                */
                      AND BUCKET_EF_1K > 0
                      AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                    FROM #KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE                */
                      AND BUCKET_EF_1K > 0
                      AND A.IDN = #PDACO_V6_1.IDN);
 

 /* FS014_6M       */
 UPDATE #PDACO_V6_1
 SET FS014_6M = (SELECT COUNT(DISTINCT ISSUE)
                 FROM #KRM023_DEDUP AS A
                 WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                   AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                   AND PAY_CODE IN ('A','B')
                   AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                 FROM #KRM023_DEDUP AS A
                   WHERE INQUIRY_MON - MON_SINCE <= 6 /* NO 30-DAY RULE                */
                     AND INQUIRY_MON - MON_SINCE > 0  /* ELIMINATE MOST RECENT 1 MONTH */
                     AND PAY_CODE IN ('A','B')
                     AND A.IDN = #PDACO_V6_1.IDN);
   
/* FS016C_9M      */
   UPDATE #PDACO_V6_1
   SET FS016C_9M = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP AS A
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE */
                      AND CASH = 'Y'
                      AND (PAY_CODE IN ('C','D','E','F') OR
                         (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                    AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                  FROM #KRM023_DEDUP AS A
                  WHERE INQUIRY_MON-1 - MON_SINCE <= 9 
                    AND CASH = 'Y'
                    AND (PAY_CODE IN ('C','D','E','F') OR
                         (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                    AND A.IDN = #PDACO_V6_1.IDN);
 
 /* FS016F_12M  */
 UPDATE #PDACO_V6_1
 SET FS016F_12M = (SELECT COUNT(*)
                   FROM #KRM023_DEDUP AS A
                   WHERE CASH = 'Y'
                   AND A.IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
               FROM #KRM023_DEDUP AS A
               WHERE CASH = 'Y'
                 AND A.IDN = #PDACO_V6_1.IDN);
 
 /* FS018_12M    */
 UPDATE #PDACO_V6_1
    SET FS018_12M = (SELECT COUNT(DISTINCT MON_SINCE)
                      FROM #KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                      FROM #KRM023_DEDUP AS A
                      WHERE CASH = 'Y'
                      AND A.IDN = #PDACO_V6_1.IDN);
/* FS021_9M       */
 UPDATE #PDACO_V6_1
   SET FS021_9M = (SELECT COUNT(DISTINCT MON_SINCE)
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND (PAY_CODE IN ('C','D','E','F') OR
                          (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                   AND IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 9 /* WITH 30-DAY RULE            */
                     AND (PAY_CODE IN ('C','D','E','F') OR
                          (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0))
                   AND IDN = #PDACO_V6_1.IDN);

/* FS059_12M_1K   */
 UPDATE #PDACO_V6_1
 SET FS059_12M_1K = (SELECT COUNT(DISTINCT ISSUE)
                     FROM #KRM023_DEDUP AS A
                     WHERE BUCKET_EF_1K > 0
                       AND IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
               FROM #KRM023_DEDUP AS A
               WHERE BUCKET_EF_1K > 0
                 AND IDN = #PDACO_V6_1.IDN);

/* FS059_3M_1K    */
 UPDATE #PDACO_V6_1
 SET FS059_3M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 3 /* WITH 30-DAY RULE            */
                      AND BUCKET_EF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN);
/* FS061_6M_1K    */
 UPDATE #PDACO_V6_1
 SET FS061_6M_1K = (SELECT COUNT(DISTINCT ISSUE)
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN)
 WHERE EXISTS (SELECT *
                    FROM #KRM023_DEDUP
                    WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                      AND BUCKET_DEF_1K > 0
                      AND IDN = #PDACO_V6_1.IDN);
 
 /* FS073B_12M     */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, BUCKET)
    SELECT IDN, ISSUE, MAX(BUCKET_EF_1K) 
    FROM #KRM023_DEDUP
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM(BUCKET)
    FROM #OPEN_LINE
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET FS073B_12M = (
                SELECT V1
                FROM #TMP
                WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 
 /* FS101_6M       */
 UPDATE #PDACO_V6_1
   SET FS101_6M = (SELECT COUNT(DISTINCT ISSUE)
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                     AND IDN = #PDACO_V6_1.IDN)
   WHERE EXISTS (SELECT *
                   FROM #KRM023_DEDUP
                   WHERE INQUIRY_MON-1 - MON_SINCE <= 6 /* WITH 30-DAY RULE            */
                     AND IDN = #PDACO_V6_1.IDN);
   
  /*---#OPEN_CARD AND #OPEN_LINE CONTAIN MONTHS WHICH SHOULD HAVE TRANSACTION RECORDS #BASED ON
     KRM001, #OPEN_LINE CONTAINS ONE RECORD FOR EACH CREDIT LINE EACH MONTH. ONE-CARD-ONE-LINE
     ISSUERS, I.E. 021(CITI) IS PROCESSED SEPERATELY.  THE OTHER TWO ONE-CARD-ONE-LINE ISSUERS,
     I.E. 081(HSBC) ,974(AIG), FOR THEIR KRM023 DATA ARE CONSOLIDATED, ARE TREATED AS
     MULTI-CARD-ONE-LINE ISSERS---*/
 /* ---PREPARE INTERMEDIATE TABLES FOR KRM023 AND KRM021 VARIABLES --- */
 DELETE FROM #OPEN_CARD;
 DELETE FROM #OPEN_LINE;
 DELETE FROM #LATEST_STMT_MON;
 DELETE FROM #LATEST_LINE;
 DECLARE @I INT
   SET @I = 0
   WHILE @I <= 14
    BEGIN
     INSERT INTO #OPEN_CARD (IDN, ISSUE, MON, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'A' AND ISSUE = 'A82' THEN 'AEA'
                   ELSE ISSUE END),
             (INQUIRY_MON - @I), INQUIRY_MON
      FROM #KRM021_DEDUP
      WHERE (END_MON_SINCE >= (INQUIRY_MON - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON - @I))
        AND ISSUE != '021'
     SET @I = @I + 1
    END;
   INSERT INTO #OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
    SELECT IDN, ISSUE, MON, COUNT(*), NOW
    FROM #OPEN_CARD
    GROUP BY IDN, ISSUE, MON, NOW;
   SET @I = 0
   WHILE @I <= 14
    BEGIN
     INSERT INTO #OPEN_LINE (IDN, ISSUE, MON, CARDS, NOW)
      SELECT IDN,
             (CASE WHEN CARD_BRAND = 'M' THEN 'CTM'
                   WHEN CARD_BRAND = 'V' THEN 'CTV'
                   WHEN CARD_BRAND = 'D' THEN 'CTD' END),
             (INQUIRY_MON - @I), 1, INQUIRY_MON
      FROM #KRM021_DEDUP
      WHERE (END_MON_SINCE >= (INQUIRY_MON - @I))
        AND (START_MON_SINCE <= (INQUIRY_MON - @I))
        AND ISSUE = '021'
     SET @I = @I + 1
    END;
   UPDATE #OPEN_LINE
    SET BUCKET = 1;
 /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
   UPDATE #OPEN_LINE
    SET BUCKET = 100  /*ARBITRARY NUMBER, JUST TO MAKE SURE IT WILL OUT-OF-RANGE*/
    WHERE MON = (NOW - 14);
   SET @I = 14;
   WHILE @I > 0
    BEGIN
     UPDATE #OPEN_LINE
      SET BUCKET = A.BUCKET + 1
      FROM #OPEN_LINE AS A INNER JOIN #OPEN_LINE
        ON A.IDN = #OPEN_LINE.IDN
       AND A.ISSUE = #OPEN_LINE.ISSUE
       AND A.MON = (#OPEN_LINE.MON - 1)
      WHERE (A.NOW - A.MON) = @I
     SET @I = @I - 1
    END;
   INSERT INTO #LATEST_STMT_MON (IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON)
    FROM #OPEN_LINE
    WHERE MON < NOW
    GROUP BY IDN, ISSUE;
   INSERT INTO #LATEST_LINE (IDN, ISSUE, MON, MOB)
    SELECT A.IDN, A.ISSUE, A.MON, A.BUCKET
    FROM #OPEN_LINE AS A INNER JOIN #LATEST_STMT_MON AS B
      ON A.IDN = B.IDN
     AND A.ISSUE = B.ISSUE
     AND A.MON = B.MON;

 /* FS205_3M_1K_Q_TRAN	 OF DELINQUNT LINES OPENED LESS THAN A YEAR */
 /*----FS205_1K----*/
 DELETE FROM #TMP;
 INSERT INTO #TMP (IDN, MON, V1)
   SELECT IDN, 3, COUNT(*)
   FROM #KRM023_DEDUP AS A
   WHERE ISSUE IN (SELECT ISSUE FROM #LATEST_LINE
                   WHERE MOB <= 12 AND IDN = A.IDN)
     AND (PAY_CODE IN ('C', 'D', 'E','F') OR
	  (CASH='Y' AND ISNULL(SPREAD_PAYMENT,0)>0))
     AND ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0) > 1
     AND (INQUIRY_MON-1 - MON_SINCE) <= 3
   GROUP BY IDN;
 UPDATE #PDACO_V6_1
   SET FS205_3M_1K = V1
   FROM #TMP AS A
   WHERE A.IDN = #PDACO_V6_1.IDN
     AND A.MON = 3;
 /* MS001_12M_1K   */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0))
    FROM #KRM023_DEDUP
    WHERE BUCKET_EF_1K > 0
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET MS001_12M_1K = (SELECT MAX(V1)
                        FROM #TMP
                        WHERE IDN = #PDACO_V6_1.IDN)
    WHERE EXISTS (SELECT *
                        FROM #TMP
                        WHERE IDN = #PDACO_V6_1.IDN);
 
 /* MS094B          */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
          ELSE 0 END) / COUNT(DISTINCT MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=3  /* WITH 30-DAY RULE */
    AND  INQUIRY_MON   - MON_SINCE > 1  /* TRUNCATE THE TRIALING 2 MONTHS */
    GROUP BY IDN;
 
 UPDATE #PDACO_V6_1
    SET MS094B = (SELECT V1
                  FROM #TMP
                  WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 
 /* MS118_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, 
      MIN((CASE WHEN PAY_CODE IN ('C','D','E','F') 
                    THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
	       WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0) > 0 
                    THEN ISNULL(SPREAD_PAYMENT,0)
               ELSE 0 END) / CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=9  /* NO   30-DAY RULE */
      AND CAST(LIMIT AS FLOAT) > 0
      AND ((PAY_CODE IN ('C','D','E','F') AND ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0) > 1)
            OR (CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0)>1))   /* TO ELIMINATE THOSE SMALL REVOLING LINES */	
    GROUP BY IDN;

 UPDATE #PDACO_V6_1
    SET MS118_9M = (
     SELECT V1
     FROM #TMP
     WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (
     SELECT IDN
     FROM #TMP);


 /* MS601          */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
    GROUP BY IDN, ISSUE; 
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM(CASE WHEN PAY_CODE IN ('C','D','E','F') THEN ISNULL(PAYMENT_AMT,0)+ISNULL(SPREAD_PAYMENT,0)
			 WHEN CASH = 'Y' AND ISNULL(SPREAD_PAYMENT,0)>0 THEN ISNULL(SPREAD_PAYMENT,0)
			 ELSE 0 END)
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE 
                  WHERE IDN = A.IDN
                  AND  ISSUE = A.ISSUE
                  AND  MON = A.MON_SINCE)
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
 SET MS601 = (SELECT V1
              FROM #TMP
              WHERE IDN = #PDACO_V6_1.IDN)
 WHERE IDN IN (SELECT IDN FROM #TMP);
 /* MS605          */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON   - MON_SINCE <=3  /* NO   30-DAY RULE */
    AND  CAST(LIMIT AS FLOAT) > 0
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, AVG(CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE
                  WHERE IDN = A.IDN
                    AND  ISSUE = A.ISSUE
                    AND  MON = A.MON_SINCE)
    GROUP BY IDN; 
 UPDATE #PDACO_V6_1
 SET MS605 = (SELECT V1
              FROM #TMP
              WHERE IDN = #PDACO_V6_1.IDN)
 WHERE IDN IN (SELECT IDN FROM #TMP);

 /* MS606 Total unsecured revolving bal (credit card + cash card + loan) */
 DELETE FROM #OPEN_LINE;
 DELETE FROM #TMP;
 INSERT INTO #OPEN_LINE(IDN, ISSUE, MON)
    SELECT IDN, ISSUE, MAX(MON_SINCE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON  - MON_SINCE <=3  /* NO   30-DAY RULE */
    GROUP BY IDN, ISSUE;
 INSERT INTO #TMP(IDN, V1)
    SELECT IDN, SUM((CASE WHEN PAY_CODE IN ('C','D','E','F') THEN ISNULL(PAYMENT_AMT,0) ELSE 0 END)
		    + ISNULL(SPREAD_PAYMENT,0))
    FROM #KRM023_DEDUP AS A
    WHERE EXISTS (SELECT *
                  FROM #OPEN_LINE 
                  WHERE IDN = A.IDN
                    AND ISSUE = A.ISSUE
                    AND MON = A.MON_SINCE)
    GROUP BY IDN;
 UPDATE #PDACO_V6_1
    SET MS606 = (SELECT V1
                 FROM #TMP
                 WHERE IDN = #PDACO_V6_1.IDN)
    WHERE IDN IN (SELECT IDN FROM #TMP);
 UPDATE #PDACO_V6_1
    SET MS606 = isnull(MS606,0)+isnull(MS063,0);

 /* WI001_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, COUNT(DISTINCT ISSUE)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI001_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);
 /* WI003_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CASE WHEN CAST(LIMIT AS FLOAT) > 200 THEN 1.0 ELSE 0.0 END)
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI003_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);
 /* WI004_9M       */
 DELETE FROM #TMP;
 INSERT INTO #TMP(IDN, MON, V1)
    SELECT IDN, MON_SINCE, SUM(CAST(LIMIT AS FLOAT))
    FROM #KRM023_DEDUP
    WHERE INQUIRY_MON-1 - MON_SINCE <=9  /* WITH 30-DAY RULE */
      AND INQUIRY_MON - MON_SINCE > 1    /* CUT LAST 2 MONTHS */
    GROUP BY IDN, MON_SINCE;
 UPDATE #PDACO_V6_1
    SET WI004_9M = 
        (SELECT SUM(V1) / 9.0
         FROM #TMP A
         WHERE #PDACO_V6_1.IDN = A.IDN)
    WHERE EXISTS (SELECT *
                 FROM #TMP A
                 WHERE #PDACO_V6_1.IDN = A.IDN);

GO
/* END_OF_CREATE_PROCEDURE_GENERATE_PDACO_SCORE */


CREATE PROCEDURE KTBFM_PDACO_RSCORE
 AS

DECLARE @MSN VARCHAR(20)
DECLARE @IDN     CHAR(11)
DECLARE @INQUIRY_DATE CHAR(8)
DECLARE @YEAR INT
DECLARE @MONTH INT
DECLARE @DAY INT
DECLARE @NOW INT


---------CREATE WORKING TABLE -----
--------------------------------
DECLARE CURSOR1 CURSOR FOR
SELECT MSN, IDN, INQUIRY_DATE
FROM APP_INFO

OPEN CURSOR1

FETCH NEXT FROM CURSOR1
INTO @MSN, @IDN, @INQUIRY_DATE

WHILE @@FETCH_STATUS = 0
BEGIN

   SET @YEAR = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 1, 4))
   SET @MONTH = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 5, 2))
   SET @DAY = CONVERT (INT, SUBSTRING(@INQUIRY_DATE, 7,2))

   IF (@DAY <= 15)
     BEGIN
       SET @MONTH = @MONTH - 1
     END
   IF (@MONTH = 0)
     BEGIN
       SET @MONTH = 12;
       SET @YEAR = @YEAR - 1
     END

   SET @NOW = (@YEAR - 1911) * 12 + @MONTH;

   EXEC PREPARE_PDACO_JCIC_DATA @MSN, @IDN,@NOW
   EXEC GENERATE_PDACO_SCORE @NOW

   INSERT INTO PDACO_SCORE_NEW_DEFINITION
     SELECT * FROM #PDACO_V6_1

 DELETE FROM #BAM086_DEDUP;
 DELETE FROM #BAM086_BUCKET;
 DELETE FROM #KRM021_DEDUP;
 DELETE FROM #KRM023_DEDUP;
 DELETE FROM #KRM037_DEDUP;
 DELETE FROM #STM007_DEDUP;
 DELETE FROM #JAS002_T;
 DELETE FROM #JAS002_T_DEDUP;
 DELETE FROM #BASE;
 DELETE FROM #TMP;
 DELETE FROM #TMP1;
 DELETE FROM #OPEN_CARD;
 DELETE FROM #OPEN_LINE;
 DELETE FROM #LATEST_STMT_MON;
 DELETE FROM #LATEST_LINE;
 DELETE FROM #KRM023_TMP;
 DELETE FROM #KRM023_TMP1;
 DELETE FROM #PDACO_V6_1;

   FETCH NEXT FROM CURSOR1
   INTO @MSN, @IDN, @INQUIRY_DATE
END

CLOSE CURSOR1
DEALLOCATE CURSOR1


 DROP TABLE #BAM086_DEDUP;
 DROP TABLE #BAM086_BUCKET;
 DROP TABLE #KRM021_DEDUP;
 DROP TABLE #KRM023_DEDUP;
 DROP TABLE #KRM037_DEDUP;
 DROP TABLE #STM007_DEDUP;
 DROP TABLE #JAS002_T;
 DROP TABLE #JAS002_T_DEDUP;
 DROP TABLE #BASE;
 DROP TABLE #TMP;
 DROP TABLE #TMP1;
 DROP TABLE #OPEN_CARD;
 DROP TABLE #OPEN_LINE;
 DROP TABLE #LATEST_STMT_MON;
 DROP TABLE #LATEST_LINE;
 DROP TABLE #KRM023_TMP;
 DROP TABLE #KRM023_TMP1;
 DROP TABLE #PDACO_V6_1;

GO

-- EXEC KTBFM_PDACO_RSCORE

