USE TNB_PLOAN_TEST
GO

SELECT TOP 1 * INTO KRM021 FROM SYSCOM_BOOC_TEST.DBO.KRM021
SELECT TOP 1 * INTO KRM001 FROM BOOC.DBO.KRM001
SELECT TOP 1 * INTO KRM023 FROM BOOC.DBO.KRM023 
SELECT TOP 1 * INTO BAM086 FROM BOOC.DBO.BAM086 
--SELECT TOP 1 * INTO BAM087 FROM SYSCOM_BOOC_TEST.DBO.BAM087
SELECT TOP 1 * INTO STM007 FROM SYSCOM_BOOC_TEST.DBO.STM007 
SELECT TOP 1 * INTO JAS002 FROM BOOC.DBO.JAS002 
GO

DELETE FROM KRM021
DELETE FROM KRM001
DELETE FROM KRM023
DELETE FROM BAM086
--DELETE FROM BAM087
DELETE FROM STM007
DELETE FROM JAS002
GO

ALTER TABLE KRM021 ADD INPUT_TIME CHAR(12), MSN CHAR(14) 
ALTER TABLE KRM021 ALTER COLUMN INQUIRY_DATE CHAR(8)
GO
ALTER TABLE KRM023 ADD INPUT_TIME CHAR(12)), MSN CHAR(14)
ALTER TABLE KRM023 ALTER COLUMN INQUIRY_DATE CHAR(8)
GO
ALTER TABLE STM007 ADD INPUT_TIME CHAR(12)), MSN CHAR(14)
ALTER TABLE STM007 ALTER COLUMN INQUIRY_DATE CHAR(8)
GO
ALTER TABLE BAM086 ADD INPUT_TIME CHAR(12)), MSN CHAR(14)
ALTER TABLE BAM086 ALTER COLUMN INQUIRY_DATE CHAR(8)
GO
ALTER TABLE JAS002 ADD INPUT_TIME CHAR(12)), MSN CHAR(14)
ALTER TABLE JAS002 ALTER COLUMN INQUIRY_DATE CHAR(8)
GO

CREATE TABLE APPLICANT
(MSN CHAR(14), IDN CHAR(11), INPUT_TIME CHAR(12), CNAME VARCHAR(20), PHONE CHAR(10), CELL_PHONE CHAR(10),  
 APPLICATION_AMOUNT INT, PRODUCT_CODE CHAR(3), APPLICATION_RATE DECIMAL(6,5), APPLICATION_TERMS INT, APPLICATION_FEE INT)
GO

--Suggestion Code: 1: Module approved "模組建議核准" ; 2: Module declined "模組建議婉拒"; 3: Module manual "模組建議人工審核"; 
--                 4: Directly approved "模組建議人工試算"
CREATE TABLE RESULT
(MSN CHAR(20), IDN CHAR(11), INPUT_TIME CHAR(12), PB DECIMAL(6,5), NPV INT, SUGGESTION CHAR(60), SUGGESTION_CODE INT, Result_File_GEN_Time Char(12))
GO

CREATE TABLE PRODUCT_LOOKUP(CODE CHAR(3), RATE DECIMAL(6,5), APPLICATION_FEE INT)
GO

INSERT INTO PRODUCT_LOOKUP(CODE, RATE, APPLICATION_FEE)
VALUES('001', 0.0599, 0)
GO

INSERT INTO PRODUCT_LOOKUP(CODE, RATE, APPLICATION_FEE)
VALUES('002', 0.0599, 5000)
GO

INSERT INTO PRODUCT_LOOKUP(CODE, RATE, APPLICATION_FEE)
VALUES('003', 0.1099, 0)
GO

INSERT INTO PRODUCT_LOOKUP(CODE, RATE, APPLICATION_FEE)
VALUES('004', 0.1099, 5000)
GO

CREATE TABLE MAIL_LIST(MSN Char(14), IDN Char(11), CNAME VARCHAR(20), ADDRESS Char(80))
GO