USE PLOAN
GO
ALTER TABLE dbo.APPLICANT DROP COLUMN PHONE
GO
ALTER TABLE dbo.APPLICANT DROP COLUMN JOB
GO
ALTER TABLE dbo.APPLICANT DROP COLUMN ON_BOARD_YM 
GO
ALTER TABLE dbo.APPLICANT DROP COLUMN OCCUPATION
GO

ALTER TABLE dbo.APPLICANT ADD MONTHLY_INCOME INT, PRODUCT_TYPE INT, BRANCH CHAR(4)
GO

ALTER TABLE dbo.APPLICANT ADD MARRIAGE INT, CHILDREN INT, EDUCATION INT, INPUT_USER VARCHAR(40), FIXED_LINE_PHONE VARCHAR(10), CELL_PHONE VARCHAR(10)
GO

CREATE TABLE dbo.MARRIAGE_LOOKUP(CODE INT, DES VARCHAR(4))
GO
INSERT INTO MARRIAGE_LOOKUP(CODE, DES) VALUES(1, '未婚')
GO
INSERT INTO MARRIAGE_LOOKUP(CODE, DES) VALUES(2, '已婚')
GO
INSERT INTO MARRIAGE_LOOKUP(CODE, DES) VALUES(3, '離婚')
GO
INSERT INTO MARRIAGE_LOOKUP(CODE, DES) VALUES(4, '其他')
GO

CREATE TABLE dbo.CHILDREN_LOOKUP(CODE INT, DES VARCHAR(8))
GO
INSERT INTO CHILDREN_LOOKUP(CODE, DES) VALUES(1, '無')
GO
INSERT INTO CHILDREN_LOOKUP(CODE, DES) VALUES(2, '一個')
GO
INSERT INTO CHILDREN_LOOKUP(CODE, DES) VALUES(3, '兩個')
GO
INSERT INTO CHILDREN_LOOKUP(CODE, DES) VALUES(4, '三個以上')
GO
INSERT INTO CHILDREN_LOOKUP(CODE, DES) VALUES(5, '其他')
GO

CREATE TABLE dbo.EDUCATION_LOOKUP(CODE INT, DES VARCHAR(4))
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(1, '國中')
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(2, '高中')
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(3, '大專')
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(4, '碩士')
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(5, '博士')
GO
INSERT INTO EDUCATION_LOOKUP(CODE, DES) VALUES(6, '其他')
GO

ALTER TABLE dbo.RESULT ADD UNSECURED_BALANCE INT, APPROVED_AMOUNT_FSC INT