USE BSP_T
GO

DROP TABLE Applicants
GO

SELECT * INTO Applicants FROM Applicants_TMP
GO

DELETE FROM APP_INFO
DELETE RESULT
DELETE RESULT_R
DELETE FROM Applicants WHERE NAV <= 0 /*150*/
GO

SELECT COUNT(*) FROM Applicants
GO
/*791*/

UPDATE Applicants
SET
PRINCIPAL = 0
GO

ALTER TABLE Applicants ADD Taken int, Secured int, Old_Module int
GO
UPDATE Applicants
SET
Taken = 0,
Secured = 1,
Old_Module = 0
GO

UPDATE Applicants
SET
Old_Module = 1
FROM BSP_SML_20040830.dbo.RESULT_BSP AS A
WHERE Applicants.MSN = A.MSN COLLATE CHINESE_TAIWAN_STROKE_CI_AS AND
      HIGHEST_1 > 0
GO
/*481*/
SELECT * FROM BSP_SML_20040830.dbo.APP_R WHERE APP_RESULT = 0 AND PRINCIPAL_OR_LIMIT IS NOT NULL
SELECT * FROM BSP_SML_20040830.dbo.APP_R WHERE APP_RESULT = 1 AND PRINCIPAL_OR_LIMIT IS NULL

--Actual taken down cases as of 20040830
UPDATE Applicants
SET
PRINCIPAL = PRINCIPAL_OR_LIMIT,
TAKEN = 1
FROM BSP_SML_20040830.dbo.APP_R AS A
WHERE Applicants.MSN = A.MSN COLLATE CHINESE_TAIWAN_STROKE_CI_AS AND
      Applicants.PRINCIPAL = 0 AND
      A.PRINCIPAL_OR_LIMIT > 0
GO
/*327*/

SELECT A.MSN, B.MSN, A.AMOUNT, B.PRINCIPAL, A.REASON 
FROM BSP_SML_20040830.dbo.E_LOAN AS A INNER JOIN BSP_SML_20040830.dbo.APP_INFO_BSP AS B
ON LEFT(B.MSN,12) = A.MSN
GO

SELECT REASON, COUNT(*)
FROM BSP_SML_20040830.dbo.E_LOAN
GROUP BY REASON
ORDER BY REASON

SELECT * FROM BSP_SML_20040830.dbo.E_LOAN WHERE REASON IS NULL AND AMOUNT IS NOT NULL

--Shown in E-loan as an open account
UPDATE Applicants
SET
PRINCIPAL = AMOUNT,
TAKEN = 1
FROM BSP_SML_20040830.dbo.E_LOAN AS A
WHERE LEFT(Applicants.MSN,12) = A.MSN COLLATE CHINESE_TAIWAN_STROKE_CI_AS AND
      AMOUNT IS NOT NULL AND 
      Old_Module = 1 AND 
      PRINCIPAL = 0 AND 
      (LEFT(REASON, 1) IN ('1', 'A', 'C') OR REASON IS NULL)
GO
/*16*/

--The new model (v2.0) approved
UPDATE Applicants
SET
PRINCIPAL = HIGHEST_1
FROM RESULT_M3_NEW3 AS A
WHERE A.MSN = Applicants.MSN AND
      A.HIGHEST_1 > 0 AND
      PRINCIPAL = 0
GO
/*275*/

--Take the lower of the new model approved amount and old models approved amount
UPDATE Applicants
SET
PRINCIPAL = (CASE WHEN HIGHEST_1 < PRINCIPAL THEN HIGHEST_1 ELSE PRINCIPAL END)
FROM RESULT_M3_NEW3 AS A
WHERE A.MSN = Applicants.MSN AND
      A.HIGHEST_1 > 0
GO

UPDATE Applicants
SET
SECURED = LIEN
FROM BSP_SML_20040830.dbo.APP_R AS A
WHERE Applicants.MSN = A.MSN COLLATE CHINESE_TAIWAN_STROKE_CI_AS AND
      LIEN IS NOT NULL
GO
/*327*/

SELECT SECURED, COUNT(*)
FROM Applicants
GROUP BY SECURED
ORDER BY SECURED
GO

SELECT * FROM Applicants WHERE PRINCIPAL = 0

DELETE FROM APPLICANTS WHERE PRINCIPAL = 0
/*173*/
SELECT COUNT(*) FROM APPLICANTS
/*618*/

------Monitoring module running
SELECT COUNT(*) FROM RESULT
SELECT DECLINE_REASON, COUNT(*)
FROM RESULT
GROUP BY DECLINE_REASON
ORDER BY DECLINE_REASON
SELECT COUNT(*) FROM RESULT WHERE HIGHEST_1 = 0
SELECT COUNT(*) FROM RESULT WHERE HIGHEST_1 != HIGHEST_2

DROP TABLE RESULT_NPV
GO
SELECT * INTO RESULT_NPV FROM RESULT
GO

DROP TABLE APP_NPV
GO
SELECT * INTO App_NPV FROM Applicants
GO

SELECT * FROM RESULT WHERE HIGHEST_1 != HIGHEST_2 

DELETE FROM Applicants WHERE MSN NOT IN
(
'0001-1025425-AA-07-1',
'0001-1069069-AA-19-3',
'0001-0780130-BC-29-3',
'0002-0798358-BC-06-2',
'0001-0893573-BB-06-2',
'0001-0755015-BB-16-2')
GO

DELETE FROM APP_INFO
DELETE FROM RESULT
DELETE FROM RESULT_R



ALTER TABLE Applicants
DROP COLUMN Taken, Secured, old_Module

SELECT * INTO RESULT_NPV FROM RESULT

---------------

SELECT COUNT(*) FROM RESULT_NPV AS A INNER JOIN RESULT_M3_NEW3 AS B
ON A.MSN = B.MSN
WHERE A.HIGHEST_1 = 0 AND B.HIGHEST_1 > 0
/*0*/
SELECT COUNT(*) FROM RESULT_NPV AS A INNER JOIN RESULT_M3_NEW3 AS B
ON A.MSN = B.MSN
WHERE A.HIGHEST_1 > 0 AND B.HIGHEST_1 = 0
/*0*/

SELECT A.MSN, A.HIGHEST_1, A.HIGHEST_2, A.SECURED_NPV, A.UNSECURED_NPV, A.RESERVED4, A.UNSECURED_PB, A.DECLINE_REASON, B.Taken, B.Secured, B.old_Module
FROM RESULT_NPV AS A INNER JOIN APP_NPV As B
ON A.MSN = B.MSN


SELECT A.MSN, A.HIGHEST_1, A.HIGHEST_2, A.SECURED_NPV, A.UNSECURED_NPV, A.RESERVED4, A.UNSECURED_PB, A.DECLINE_REASON, B.Taken, B.Secured, B.Module
FROM RESULT AS A INNER JOIN APPLICANTS As B
ON A.MSN = B.MSN

SELECT A.MSN, A.HIGHEST_1, B.HIGHEST_1, A.SECURED_NPV, B.SECURED_NPV, A.RESERVED4, B.RESERVED4
FROM RESULT AS A INNER JOIN RESULT_M3_NEW3_REL AS B
ON A.MSN = B.MSN
WHERE A.HIGHEST_1 = B.HIGHEST_1 AND
      A.SECURED_NPV != B.SECURED_NPV

SELECT * FROM RESULT AS A INNER JOIN RESULT_M3_NEW3_REL AS B
ON A.MSN = B.MSN
WHERE B.HIGHEST_1 = 0 AND A.HIGHEST_1 > 0 

SELECT * FROM (RESULT AS A INNER JOIN RESULT_M3_NEW3_REL AS B
ON A.MSN = B.MSN) INNER JOIN Applicants AS C ON A.MSN = C.MSN
WHERE B.HIGHEST_1 > 0 AND A.HIGHEST_1 = 0 AND
      C.PRINCIPAL <= B.HIGHEST_1

DELETE FROM APP_INFO
DELETE FROM RESULT
DELETE FROM RESULT_R
DELETE FROM Applicants WHERE MSN NOT IN
(
'0001-0401351-SS-05-1',
'0001-0755015-BB-16-2',
'0001-0841361-BC-01-1',
'0001-1033723-BC-02-2',
'0001-1025425-AA-07-1',
'0002-0758818-BC-31-3',
'0001-0893573-BB-06-2')

INSERT INTO Applicants SELECT * FROM APP_NPV

SELECT COUNT(*) FROM RESULT