USE BSP_SML_20040830
GO

SELECT A.MSN, A.IDN, A.TIME_STAMP, A.TEST_CELL, A.GAV, A.FIRST_LIEN_VALUE / 1.2 AS First_Mortgage, A.NAV, B.SCORE, A.ZIP
FROM APP_INFO As A INNER JOIN PDACO_V1_00_CAL AS B
ON A.MSN = B.CASE_NO AND
   A.IDN = B.IDN AND
   A.TIME_STAMP = B.TIME_STAMP
GO

SELECT A.MSN, A.IDN, A.TIME_STAMP, A.TEST_CELL, A.GAV / 1000.0, A.FIRST_LIEN_VALUE / 1200.0 AS First_Mortgage, A.NAV / 1000.0, A.ZIP, (CASE 
                                                                                                                    WHEN A.ZIP > 253 THEN 2
                                                                                                                    WHEN A.ZIP BETWEEN 200 AND 206 THEN 2
                                                                                                                    ELSE 1
                                                                                                                  END) AS T_ZIP                                   
FROM APP_INFO As A 

DROP TABLE UNSECURED_DEBT
GO

CREATE TABLE UNSECURED_DEBT
(MSN Char(20), IDN Char(14), TIME_STAMP Char(12), APP_MON Char(6), APP_MON_SINCE int, KRM023_BAL float, BAM009_BAL float, TOTAL_BAL float)
GO

INSERT INTO UNSECURED_DEBT(MSN, IDN, TIME_STAMP, KRM023_BAL, BAM009_BAL, TOTAL_BAL)
SELECT MSN, IDN, TIME_STAMP, 0, 0, 0
FROM APP_INFO
GO

UPDATE UNSECURED_DEBT
SET
APP_MON = (CASE 
             WHEN SUBSTRING(TIME_STAMP, 7,2) > 15 THEN SUBSTRING(TIME_STAMP, 1, 6)
             ELSE SUBSTRING(TIME_STAMP, 1,6) - 1
           END) 
GO

UPDATE UNSECURED_DEBT
SET
APP_MON_SINCE = (CONVERT(INT, SUBSTRING(APP_MON,1,4)) - 1911) * 12 + SUBSTRING(APP_MON,5,2)
GO

SELECT * FROM UNSECURED_DEBT

DROP TABLE UDB_TMP1
GO

CREATE TABLE UDB_TMP1(MSN Char(20), IDN Char(14), TIME_STAMP Char(12), BAL FLOAT)
GO

INSERT INTO UDB_TMP1
SELECT A.MSN, A.IDN, A.TIME_STAMP, SUM(CASE 
                                         WHEN PAYMENT IS NULL THEN 0  
                                         ELSE (CASE WHEN RIGHT(PAYMENT,1) = 'L' THEN 2 WHEN RIGHT(PAYMENT,1) = 'M' THEN 5 WHEN RIGHT(PAYMENT,1) = 'H' THEN 8 END) * POWER(10, CONVERT(INT, LEFT(PAYMENT,2))-1) / 1000.0
                                       END)
FROM KRM023 AS A INNER JOIN UNSECURED_DEBT AS B
ON A.MSN = B.MSN AND
   A.IDN = B.IDN AND
   A.TIME_STAMP = B.TIME_STAMP
WHERE (LTRIM(RTRIM(LEFT(YRMON,2))) * 12 + LTRIM(RTRIM(RIGHT(YRMON,2)))) = (B.APP_MON_SINCE - 1) AND
      PAY_CODE IN ('C', 'D', 'E', 'F')
GROUP BY A.MSN, A.IDN, A.TIME_STAMP
GO

UPDATE UNSECURED_DEBT
SET
KRM023_BAL = A.BAL
FROM UDB_TMP1 AS A
WHERE A.MSN = UNSECURED_DEBT.MSN AND
      A.IDN = UNSECURED_DEBT.IDN AND
      A.TIME_STAMP = UNSECURED_DEBT.TIME_STAMP
GO

DELETE FROM UDB_TMP1
GO

INSERT INTO UDB_TMP1
SELECT MSN, IDN, TIME_STAMP, SUM(ISNULL(LOAN_AMT,0) + ISNULL(PASS_DUE_AMT,0))
FROM BAM086
WHERE ACCOUNT_CODE2 = '' OR ACCOUNT_CODE2 IS NULL
GROUP BY MSN, IDN, TIME_STAMP
GO

UPDATE UNSECURED_DEBT
SET
BAM009_BAL = A.BAL
FROM UDB_TMP1 AS A
WHERE A.MSN = UNSECURED_DEBT.MSN AND
      A.IDN = UNSECURED_DEBT.IDN AND
      A.TIME_STAMP = UNSECURED_DEBT.TIME_STAMP
GO

UPDATE UNSECURED_DEBT
SET
TOTAL_BAL = BAM009_BAL + KRM023_BAL
GO

SELECT * FROM UNSECURED_DEBT

SELECT MSN, IDN, TIME_STAMP, TOTAL_BAL FROM UNSECURED_DEBT

SELECT * FROM KRM023 WHERE MSN = '0001-0011061-CC-29-3' ORDER BY YRMON

SELECT * FROM BAM086 WHERE MSN = '0001-0223043-CC-04-2'




