USE DAC_SML_20050328
GO

SELECT COUNT(*) FROM RESULT

SELECT * INTO RESULT_FIX_0314 FROM RESULT
GO

DELETE FROM APP_INFO
DELETE FROM RESULT
DELETE FROM RESULT_R
GO

ALTER TABLE RESULT ADD UNSECURED_BALANCE FLOAT
GO

SELECT A.MSN, A.SECURED_NPV, B.SECURED_NPV
FROM RESULT AS A INNER JOIN RESULT_FIX_0314 AS B
ON A.MSN = B.MSN
WHERE ((A.HIGHEST_1 != B.HIGHEST_1) OR
       (A.HIGHEST_2 != B.HIGHEST_2) OR
       (A.RISK_SCORE != B.RISK_SCORE) OR
       (A.SECURED_NPV - B.SECURED_NPV > 1000) OR
       (A.UNSECURED_NPV - B.UNSECURED_NPV > 1000))
GO

SELECT SUBSTRING(MSN, 17, 2), COUNT(*)
FROM APPLICANTS
GROUP BY SUBSTRING(MSN, 17, 2)
ORDER BY SUBSTRING(MSN, 17, 2)

SELECT 
A.MSN, A.IDN, A.TIME_STAMP, A.TEST_CELL, GAV / 1000.0, FIRST_LIEN_VALUE / 1000.0 / 1.2, NAV / 1000.0, RISK_SCORE, (CASE WHEN A.ZIP > 253 THEN 2 WHEN A.ZIP BETWEEN 200 AND 206 THEN 2 ELSE 1 END) AS T_ZIP, UNSECURED_BALANCE, DECLINE_REASON, B.SC
FROM APPLICANTS AS A INNER JOIN RESULT AS B
ON A.MSN = B.MSN
WHERE A.TEST_CELL < 17
ORDER BY MSN

SELECT 
A.MSN, A.IDN, A.TEST_CELL, GAV / 1000.0, FIRST_LIEN_VALUE / 1000.0 / 1.2, NAV / 1000.0, (CASE WHEN RISK_SCORE > 1 THEN NULL ELSE RISK_SCORE END), (CASE WHEN A.ZIP > 253 THEN 0 WHEN A.ZIP BETWEEN 200 AND 206 THEN 0 ELSE 1 END) AS T_ZIP, UNSECURED_BALANCE, DECLINE_REASON
FROM APPLICANTS AS A INNER JOIN RESULT AS B
ON A.MSN = B.MSN
WHERE A.TEST_CELL > 16
ORDER BY MSN

SELECT 
A.MSN, A.IDN, A.TIME_STAMP, HIGHEST_1 / 1000.0, HIGHEST_2 / 1000.0, SECURED_PB, UNSECURED_PB, SECURED_NPV / 1000.0, UNSECURED_NPV / 1000.0
FROM RESULT AS A
WHERE A.TEST_CELL < 17
ORDER BY MSN

SELECT 
A.MSN, A.IDN,  HIGHEST_1 / 1000.0, HIGHEST_2 / 1000.0, SECURED_PB, UNSECURED_PB, SECURED_NPV / 1000.0, UNSECURED_NPV / 1000.0
FROM RESULT AS A
WHERE A.TEST_CELL > 16
ORDER BY MSN