USE BSP_SML_TEST_200502
GO

SELECT A.TEST_CELL, B.TEST_CELL, COUNT(*)
FROM NEW_TEST_CELL AS A INNER JOIN APPLICANTS AS B
ON A.MSN = B.MSN
GROUP BY A.TEST_CELL, B.TEST_CELL
ORDER BY A.TEST_CELL
GO


SELECT TEST_CELL, COUNT(*)
FROM APPLICANTS
GROUP BY TEST_CELL
ORDER BY TEST_CELL
GO