@ECHO OFF
SET BSAUTO_HOME=c:\DAC\fuhwa\CreditCard\automate
SET BSAUTO_DATA=%BSAUTO_HOME%\data
CD %BSAUTO_DATA%

:: Set a lock to prevent the same batch run at the same time
IF EXIST ".lock" GOTO LOCK
TYPE NUL >.lock

:: Check if the control file was given
IF "%1"=="" GOTO DEFAULT
SET CTLFILE=%1
GOTO PROCESS

:DEFAULT
SET CTLFILE=%BSAUTO_DATA%\FHBSAUTO.CTL

:PROCESS
ECHO The control file is %CTLFILE%
IF NOT EXIST "%CTLFILE%" GOTO NOTFOUND

:: del result generated by previous run
del PROFILE*.csv
del PD*.csv

:: Execute automation program
ECHO fhauto -u oliver -p oliver -s oliver -d oliver

IF ERRORLEVEL 1 GOTO ERROR1
IF ERRORLEVEL 2 GOTO ERROR2
IF ERRORLEVEL 3 GOTO ERROR3
IF ERRORLEVEL 4 GOTO ERROR4
IF ERRORLEVEL 5 GOTO ERROR5
IF ERRORLEVEL 6 GOTO ERROR6
IF ERRORLEVEL 7 GOTO ERROR7
IF ERRORLEVEL 8 GOTO ERROR8

:: FTP result to host
:: Create the temporary script file
> script.ftp ECHO USER oliver
>>script.ftp ECHO oliver
>>script.ftp ECHO cd files/pictures
>>script.ftp ECHO ascii
>>script.ftp ECHO prompt n
>>script.ftp ECHO mput PD*.csv
>>script.ftp ECHO mput PROFILE*.csv
>>script.ftp ECHO put  BCRESULT.CTL
>>script.ftp ECHO quit
:: Use the temporary script for unattended FTP
FTP -v -s:script.ftp ftp.myhost.net
:: For the paranoid: overwrite the temporary file before deleting it
TYPE NUL >script.ftp
DEL script.ftp

ECHO *** Success!! > FHBSAUTO.LOG
GOTO DELLOCK

:NOTFOUND
ECHO "CONTROL FILE NOT FOUND" > FHBSAUTO.LOG
GOTO DELLOCK

:ERROR1
ECHO ERROR1 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR2
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR3
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR4
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR5
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR6
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR7
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR8
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK
:ERROR9
ECHO ERROR2 > FHBSAUTO.LOG
GOTO DELLOCK

:LOCK
ECHO The same job is currently running, you have to wait until it completes. > FHBSAUTO.LOG
GOTO END

:DELLOCK
DEL .lock

:END