USE BSP_SML_20040830
GO

SELECT * FROM DAM103 ORDER BY MSN, IDN, TIME_STAMP
SELECT * FROM DAM203 ORDER BY MSN, IDN, TIME_STAMP

DROP TABLE JAS002
GO

CREATE TABLE JAS002
(MSN Char(20) COLLATE Chinese_Taiwan_Stroke_CS_AS NULL , 
 IDN Char(14) COLLATE Chinese_Taiwan_Stroke_CS_AS NULL , 
 TIME_STAMP Char(12) COLLATE Chinese_Taiwan_Stroke_CS_AS NULL ,
 EVER_DELINQUENT CHAR, DELINQUENT_DATE CHAR(7),
 EVER_BAD_CHECK CHAR, BAD_CHECK_DATE CHAR(7),
 EVER_REJECT CHAR, REJECT_DATE CHAR(7),
 EVER_STOP_CARD CHAR, STOP_CARD_DATE CHAR(7))
GO

INSERT INTO JAS002
SELECT MSN, IDN, TIME_STAMP, 
       NULL, NULL, 
       'Y', CK_DATE,
       NULL, NULL,
       NULL, NULL
FROM DAM103
GO

UPDATE JAS002
SET
EVER_REJECT = 'Y',
REJECT_DATE = BEG_DATE
FROM DAM203 AS A
WHERE A.MSN = JAS002.MSN AND
      A.IDN = JAS002.MSN AND
      A.TIME_STAMP = JAS002.TIME_STAMP
GO

INSERT INTO JAS002
SELECT MSN, IDN, TIME_STAMP,
       NULL, NULL,
       NULL, NULL,
       'Y', BEG_DATE,
       NULL, NULL
FROM DAM203
WHERE NOT EXISTS
      (SELECT * FROM JAS002 AS A
       WHERE A.MSN = DAM203.MSN AND
             A.IDN = DAM203.IDN AND
             A.TIME_STAMP = DAM203.TIME_STAMP)
GO

SELECT * FROM JAS002 ORDER BY MSN, IDN, TIME_STAMP