USE FW_PLOAN
GO

--Must run WI_variables_200308 first

UPDATE WI_MASTER
SET
MS047 = A.MS047,
MS039 = A.MS039,
MS040 = A.MS040,
MS041 = A.MS041,
MS048 = A.MS048,
MS050 = A.MS050
FROM MASTER_200308_1 AS A
WHERE WI_MASTER.IDN = A.IDN
--7997

----WI001----
DELETE FROM WI_TMP1
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, COUNT(*)
FROM KRM023_200308_WITH_THREE_BUCKET
GROUP BY IDN, MON_SINCE
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI001_1 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI001_2 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI001_3 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI001_4 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI001_5 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI001_6 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI001_7 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI001_8 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI001_9 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI001_10 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI001_11 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI001_12 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI002----
DELETE FROM WI_TMP1
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, COUNT(*)
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE CONVERT(INT, LIMIT) > 100
GROUP BY IDN, MON_SINCE
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI002_1 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI002_2 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI002_3 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI002_4 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI002_5 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI002_6 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI002_7 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI002_8 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI002_9 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI002_10 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI002_11 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI002_12 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI003----
DELETE FROM WI_TMP1
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, COUNT(*)
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE CONVERT(INT, LIMIT) > 200
GROUP BY IDN, MON_SINCE
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI003_1 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI003_2 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI003_3 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI003_4 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI003_5 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI003_6 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI003_7 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI003_8 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI003_9 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI003_10 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI003_11 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI003_12 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI004----
DELETE FROM WI_TMP1
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, SUM(CONVERT(INT, LIMIT))
FROM KRM023_200308_WITH_THREE_BUCKET
GROUP BY IDN, MON_SINCE
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI004_1 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI004_2 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI004_3 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI004_4 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI004_5 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI004_6 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI004_7 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI004_8 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI004_9 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI004_10 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI004_11 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI004_12 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI005----
DELETE FROM WI_TMP1
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, SUM(PAYMENT_AMT)
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE PAY_CODE IN ('A', 'B')
GROUP BY IDN, MON_SINCE
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI005_1 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI005_2 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI005_3 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI005_4 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI005_5 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI005_6 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI005_7 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI005_8 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI005_9 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI005_10 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI005_11 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI005_12 = A.V1
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI006----
DELETE FROM WI_TMP1
GO
DELETE FROM WI_TMP2
GO
DELETE FROM WI_TMP3

INSERT INTO WI_TMP3
SELECT IDN
FROM KRM023_200308_WITH_THREE_BUCKET
GROUP BY IDN
HAVING MAX(BUCKET_EF_1K) = 0
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1, V2)
SELECT IDN, MON_SINCE, 0, 0
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE IDN IN
      (SELECT IDN FROM WI_TMP3)
GROUP BY IDN, MON_SINCE
GO

INSERT INTO WI_TMP2(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, SUM(PAYMENT_AMT)
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE PAY_CODE IN ('C', 'D') AND
      IDN IN
      (SELECT IDN FROM WI_TMP3)
GROUP BY IDN, MON_SINCE
GO

UPDATE WI_TMP1
SET
V1 = A.V1
FROM WI_TMP2 AS A
WHERE A.IDN = WI_TMP1.IDN AND
      A.MON_SINCE = WI_TMP1.MON_SINCE
GO

UPDATE WI_TMP1
SET
V2 = (CASE 
        WHEN (WI_TMP1.V1 - A.V1) >= 0 THEN 0
        ELSE (WI_TMP1.V1 - A.V1) * -1
      END) 
FROM WI_TMP1 AS A INNER JOIN WI_TMP1
ON A.IDN = WI_TMP1.IDN AND
   A.MON_SINCE = WI_TMP1.MON_SINCE - 1
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI006_1 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI006_2 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI006_3 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI006_4 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI006_5 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI006_6 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI006_7 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI006_8 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI006_9 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI006_10 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI006_11 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI006_12 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO

----WI007----
DELETE FROM WI_TMP1
GO
DELETE FROM WI_TMP2
GO

INSERT INTO WI_TMP1(IDN, MON_SINCE, V1, V2)
SELECT IDN, MON_SINCE, 0, 0
FROM KRM023_200308_WITH_THREE_BUCKET
GROUP BY IDN, MON_SINCE
GO

INSERT INTO WI_TMP2(IDN, MON_SINCE, V1)
SELECT IDN, MON_SINCE, SUM(PAYMENT_AMT)
FROM KRM023_200308_WITH_THREE_BUCKET
WHERE PAY_CODE IN ('C', 'D', 'E', 'F')
GROUP BY IDN, MON_SINCE
GO

UPDATE WI_TMP1
SET
V1 = A.V1
FROM WI_TMP2 AS A
WHERE A.IDN = WI_TMP1.IDN AND
      A.MON_SINCE = WI_TMP1.MON_SINCE
GO

UPDATE WI_TMP1
SET
V2 = (CASE 
        WHEN (WI_TMP1.V1 - A.V1) >= 0 THEN 0
        ELSE (WI_TMP1.V1 - A.V1) * -1
      END) 
FROM WI_TMP1 AS A INNER JOIN WI_TMP1
ON A.IDN = WI_TMP1.IDN AND
   A.MON_SINCE = WI_TMP1.MON_SINCE - 1
GO

DECLARE @NOW INT
SET @NOW = 92 * 12 + 8

UPDATE WI_MASTER
SET
WI007_1 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 1

UPDATE WI_MASTER
SET
WI007_2 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 2

UPDATE WI_MASTER
SET
WI007_3 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 3

UPDATE WI_MASTER
SET
WI007_4 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 4

UPDATE WI_MASTER
SET
WI007_5 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 5

UPDATE WI_MASTER
SET
WI007_6 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 6

UPDATE WI_MASTER
SET
WI007_7 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 7

UPDATE WI_MASTER
SET
WI007_8 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 8

UPDATE WI_MASTER
SET
WI007_9 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 9

UPDATE WI_MASTER
SET
WI007_10 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 10

UPDATE WI_MASTER
SET
WI007_11 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 11

UPDATE WI_MASTER
SET
WI007_12 = A.V2
FROM WI_TMP1 AS A
WHERE A.IDN = WI_MASTER.IDN AND
      @NOW - A.MON_SINCE = 12
GO